# gazelle:prefix github.com/tstapler/stapler-squad/server/web

load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "web",
    srcs = ["embed.go"],
    embedsrcs = [
        "dist/404.html",
        "dist/404/index.html",
        "dist/config/index.html",
        "dist/config/index.txt",
        "dist/debug/escape-codes/index.html",
        "dist/debug/escape-codes/index.txt",
        "dist/history/index.html",
        "dist/history/index.txt",
        "dist/index.html",
        "dist/index.txt",
        "dist/login/index.html",
        "dist/login/index.txt",
        "dist/logo.svg",
        "dist/logs/index.html",
        "dist/logs/index.txt",
        "dist/review-queue/index.html",
        "dist/review-queue/index.txt",
        "dist/rules/index.html",
        "dist/rules/index.txt",
        "dist/sessions/new/index.html",
        "dist/sessions/new/index.txt",
        "dist/test-terminal/index.html",
        "dist/test-terminal/index.txt",
        "dist/test/escape-codes/index.html",
        "dist/test/escape-codes/index.txt",
        "dist/test/terminal-stress/index.html",
        "dist/test/terminal-stress/index.txt",
    ],
    importpath = "github.com/tstapler/stapler-squad/server/web",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "dist_files",
    srcs = [
        "dist",
    ],
    visibility = ["//visibility:public"],
)
