// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tstapler/stapler-squad/session/ent/approvalrule"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
)

// ApprovalRuleDelete is the builder for deleting a ApprovalRule entity.
type ApprovalRuleDelete struct {
	config
	hooks    []Hook
	mutation *ApprovalRuleMutation
}

// Where appends a list predicates to the ApprovalRuleDelete builder.
func (_d *ApprovalRuleDelete) Where(ps ...predicate.ApprovalRule) *ApprovalRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ApprovalRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ApprovalRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ApprovalRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(approvalrule.Table, sqlgraph.NewFieldSpec(approvalrule.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ApprovalRuleDeleteOne is the builder for deleting a single ApprovalRule entity.
type ApprovalRuleDeleteOne struct {
	_d *ApprovalRuleDelete
}

// Where appends a list predicates to the ApprovalRuleDelete builder.
func (_d *ApprovalRuleDeleteOne) Where(ps ...predicate.ApprovalRule) *ApprovalRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ApprovalRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{approvalrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ApprovalRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
