// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tstapler/stapler-squad/session/ent/backlogactivitynote"
	"github.com/tstapler/stapler-squad/session/ent/backlogitem"
)

// BacklogActivityNote is the model entity for the BacklogActivityNote schema.
type BacklogActivityNote struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID uuid.UUID `json:"item_id,omitempty"`
	// Freeform note text posted via the ungated post_backlog_update tool. This is the note's only payload, unlike BacklogProgressNote.note which is secondary to a status change — required, not optional.
	Message string `json:"message,omitempty"`
	// Best-effort caller identity. Empty means no session (a manual/unlinked caller).
	AuthorSessionUUID string `json:"author_session_uuid,omitempty"`
	// Best-effort session title resolved from author_session_uuid. May be empty even when author_session_uuid is set.
	AuthorSessionTitle string `json:"author_session_title,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BacklogActivityNoteQuery when eager-loading is set.
	Edges        BacklogActivityNoteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BacklogActivityNoteEdges holds the relations/edges for other nodes in the graph.
type BacklogActivityNoteEdges struct {
	// Item holds the value of the item edge.
	Item *BacklogItem `json:"item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BacklogActivityNoteEdges) ItemOrErr() (*BacklogItem, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: backlogitem.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BacklogActivityNote) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backlogactivitynote.FieldMessage, backlogactivitynote.FieldAuthorSessionUUID, backlogactivitynote.FieldAuthorSessionTitle:
			values[i] = new(sql.NullString)
		case backlogactivitynote.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case backlogactivitynote.FieldID, backlogactivitynote.FieldItemID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BacklogActivityNote fields.
func (_m *BacklogActivityNote) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backlogactivitynote.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case backlogactivitynote.FieldItemID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value != nil {
				_m.ItemID = *value
			}
		case backlogactivitynote.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case backlogactivitynote.FieldAuthorSessionUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author_session_uuid", values[i])
			} else if value.Valid {
				_m.AuthorSessionUUID = value.String
			}
		case backlogactivitynote.FieldAuthorSessionTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author_session_title", values[i])
			} else if value.Valid {
				_m.AuthorSessionTitle = value.String
			}
		case backlogactivitynote.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BacklogActivityNote.
// This includes values selected through modifiers, order, etc.
func (_m *BacklogActivityNote) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItem queries the "item" edge of the BacklogActivityNote entity.
func (_m *BacklogActivityNote) QueryItem() *BacklogItemQuery {
	return NewBacklogActivityNoteClient(_m.config).QueryItem(_m)
}

// Update returns a builder for updating this BacklogActivityNote.
// Note that you need to call BacklogActivityNote.Unwrap() before calling this method if this BacklogActivityNote
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BacklogActivityNote) Update() *BacklogActivityNoteUpdateOne {
	return NewBacklogActivityNoteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BacklogActivityNote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BacklogActivityNote) Unwrap() *BacklogActivityNote {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BacklogActivityNote is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BacklogActivityNote) String() string {
	var builder strings.Builder
	builder.WriteString("BacklogActivityNote(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("item_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ItemID))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("author_session_uuid=")
	builder.WriteString(_m.AuthorSessionUUID)
	builder.WriteString(", ")
	builder.WriteString("author_session_title=")
	builder.WriteString(_m.AuthorSessionTitle)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BacklogActivityNotes is a parsable slice of BacklogActivityNote.
type BacklogActivityNotes []*BacklogActivityNote
