// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tstapler/stapler-squad/session/ent/backlogitem"
	"github.com/tstapler/stapler-squad/session/ent/backlogstatusevent"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
)

// BacklogStatusEventUpdate is the builder for updating BacklogStatusEvent entities.
type BacklogStatusEventUpdate struct {
	config
	hooks    []Hook
	mutation *BacklogStatusEventMutation
}

// Where appends a list predicates to the BacklogStatusEventUpdate builder.
func (_u *BacklogStatusEventUpdate) Where(ps ...predicate.BacklogStatusEvent) *BacklogStatusEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *BacklogStatusEventUpdate) SetItemID(v uuid.UUID) *BacklogStatusEventUpdate {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *BacklogStatusEventUpdate) SetNillableItemID(v *uuid.UUID) *BacklogStatusEventUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetFromStatus sets the "from_status" field.
func (_u *BacklogStatusEventUpdate) SetFromStatus(v string) *BacklogStatusEventUpdate {
	_u.mutation.SetFromStatus(v)
	return _u
}

// SetNillableFromStatus sets the "from_status" field if the given value is not nil.
func (_u *BacklogStatusEventUpdate) SetNillableFromStatus(v *string) *BacklogStatusEventUpdate {
	if v != nil {
		_u.SetFromStatus(*v)
	}
	return _u
}

// SetToStatus sets the "to_status" field.
func (_u *BacklogStatusEventUpdate) SetToStatus(v string) *BacklogStatusEventUpdate {
	_u.mutation.SetToStatus(v)
	return _u
}

// SetNillableToStatus sets the "to_status" field if the given value is not nil.
func (_u *BacklogStatusEventUpdate) SetNillableToStatus(v *string) *BacklogStatusEventUpdate {
	if v != nil {
		_u.SetToStatus(*v)
	}
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *BacklogStatusEventUpdate) SetTriggeredBy(v string) *BacklogStatusEventUpdate {
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *BacklogStatusEventUpdate) SetNillableTriggeredBy(v *string) *BacklogStatusEventUpdate {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// SetItem sets the "item" edge to the BacklogItem entity.
func (_u *BacklogStatusEventUpdate) SetItem(v *BacklogItem) *BacklogStatusEventUpdate {
	return _u.SetItemID(v.ID)
}

// Mutation returns the BacklogStatusEventMutation object of the builder.
func (_u *BacklogStatusEventUpdate) Mutation() *BacklogStatusEventMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the BacklogItem entity.
func (_u *BacklogStatusEventUpdate) ClearItem() *BacklogStatusEventUpdate {
	_u.mutation.ClearItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BacklogStatusEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BacklogStatusEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BacklogStatusEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BacklogStatusEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BacklogStatusEventUpdate) check() error {
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BacklogStatusEvent.item"`)
	}
	return nil
}

func (_u *BacklogStatusEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backlogstatusevent.Table, backlogstatusevent.Columns, sqlgraph.NewFieldSpec(backlogstatusevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FromStatus(); ok {
		_spec.SetField(backlogstatusevent.FieldFromStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToStatus(); ok {
		_spec.SetField(backlogstatusevent.FieldToStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(backlogstatusevent.FieldTriggeredBy, field.TypeString, value)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogstatusevent.ItemTable,
			Columns: []string{backlogstatusevent.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogstatusevent.ItemTable,
			Columns: []string{backlogstatusevent.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backlogstatusevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BacklogStatusEventUpdateOne is the builder for updating a single BacklogStatusEvent entity.
type BacklogStatusEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BacklogStatusEventMutation
}

// SetItemID sets the "item_id" field.
func (_u *BacklogStatusEventUpdateOne) SetItemID(v uuid.UUID) *BacklogStatusEventUpdateOne {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *BacklogStatusEventUpdateOne) SetNillableItemID(v *uuid.UUID) *BacklogStatusEventUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetFromStatus sets the "from_status" field.
func (_u *BacklogStatusEventUpdateOne) SetFromStatus(v string) *BacklogStatusEventUpdateOne {
	_u.mutation.SetFromStatus(v)
	return _u
}

// SetNillableFromStatus sets the "from_status" field if the given value is not nil.
func (_u *BacklogStatusEventUpdateOne) SetNillableFromStatus(v *string) *BacklogStatusEventUpdateOne {
	if v != nil {
		_u.SetFromStatus(*v)
	}
	return _u
}

// SetToStatus sets the "to_status" field.
func (_u *BacklogStatusEventUpdateOne) SetToStatus(v string) *BacklogStatusEventUpdateOne {
	_u.mutation.SetToStatus(v)
	return _u
}

// SetNillableToStatus sets the "to_status" field if the given value is not nil.
func (_u *BacklogStatusEventUpdateOne) SetNillableToStatus(v *string) *BacklogStatusEventUpdateOne {
	if v != nil {
		_u.SetToStatus(*v)
	}
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *BacklogStatusEventUpdateOne) SetTriggeredBy(v string) *BacklogStatusEventUpdateOne {
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *BacklogStatusEventUpdateOne) SetNillableTriggeredBy(v *string) *BacklogStatusEventUpdateOne {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// SetItem sets the "item" edge to the BacklogItem entity.
func (_u *BacklogStatusEventUpdateOne) SetItem(v *BacklogItem) *BacklogStatusEventUpdateOne {
	return _u.SetItemID(v.ID)
}

// Mutation returns the BacklogStatusEventMutation object of the builder.
func (_u *BacklogStatusEventUpdateOne) Mutation() *BacklogStatusEventMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the BacklogItem entity.
func (_u *BacklogStatusEventUpdateOne) ClearItem() *BacklogStatusEventUpdateOne {
	_u.mutation.ClearItem()
	return _u
}

// Where appends a list predicates to the BacklogStatusEventUpdate builder.
func (_u *BacklogStatusEventUpdateOne) Where(ps ...predicate.BacklogStatusEvent) *BacklogStatusEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BacklogStatusEventUpdateOne) Select(field string, fields ...string) *BacklogStatusEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BacklogStatusEvent entity.
func (_u *BacklogStatusEventUpdateOne) Save(ctx context.Context) (*BacklogStatusEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BacklogStatusEventUpdateOne) SaveX(ctx context.Context) *BacklogStatusEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BacklogStatusEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BacklogStatusEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BacklogStatusEventUpdateOne) check() error {
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BacklogStatusEvent.item"`)
	}
	return nil
}

func (_u *BacklogStatusEventUpdateOne) sqlSave(ctx context.Context) (_node *BacklogStatusEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backlogstatusevent.Table, backlogstatusevent.Columns, sqlgraph.NewFieldSpec(backlogstatusevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BacklogStatusEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backlogstatusevent.FieldID)
		for _, f := range fields {
			if !backlogstatusevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backlogstatusevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FromStatus(); ok {
		_spec.SetField(backlogstatusevent.FieldFromStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToStatus(); ok {
		_spec.SetField(backlogstatusevent.FieldToStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(backlogstatusevent.FieldTriggeredBy, field.TypeString, value)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogstatusevent.ItemTable,
			Columns: []string{backlogstatusevent.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogstatusevent.ItemTable,
			Columns: []string{backlogstatusevent.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BacklogStatusEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backlogstatusevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
