// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tstapler/stapler-squad/session/ent/backlogitem"
	"github.com/tstapler/stapler-squad/session/ent/backlogstuckstate"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
)

// BacklogStuckStateUpdate is the builder for updating BacklogStuckState entities.
type BacklogStuckStateUpdate struct {
	config
	hooks    []Hook
	mutation *BacklogStuckStateMutation
}

// Where appends a list predicates to the BacklogStuckStateUpdate builder.
func (_u *BacklogStuckStateUpdate) Where(ps ...predicate.BacklogStuckState) *BacklogStuckStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *BacklogStuckStateUpdate) SetItemID(v uuid.UUID) *BacklogStuckStateUpdate {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *BacklogStuckStateUpdate) SetNillableItemID(v *uuid.UUID) *BacklogStuckStateUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *BacklogStuckStateUpdate) SetReason(v string) *BacklogStuckStateUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *BacklogStuckStateUpdate) SetNillableReason(v *string) *BacklogStuckStateUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetFirstDetectedAt sets the "first_detected_at" field.
func (_u *BacklogStuckStateUpdate) SetFirstDetectedAt(v time.Time) *BacklogStuckStateUpdate {
	_u.mutation.SetFirstDetectedAt(v)
	return _u
}

// SetNillableFirstDetectedAt sets the "first_detected_at" field if the given value is not nil.
func (_u *BacklogStuckStateUpdate) SetNillableFirstDetectedAt(v *time.Time) *BacklogStuckStateUpdate {
	if v != nil {
		_u.SetFirstDetectedAt(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *BacklogStuckStateUpdate) SetLastCheckedAt(v time.Time) *BacklogStuckStateUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *BacklogStuckStateUpdate) SetNillableLastCheckedAt(v *time.Time) *BacklogStuckStateUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// SetNotifiedAt sets the "notified_at" field.
func (_u *BacklogStuckStateUpdate) SetNotifiedAt(v time.Time) *BacklogStuckStateUpdate {
	_u.mutation.SetNotifiedAt(v)
	return _u
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_u *BacklogStuckStateUpdate) SetNillableNotifiedAt(v *time.Time) *BacklogStuckStateUpdate {
	if v != nil {
		_u.SetNotifiedAt(*v)
	}
	return _u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (_u *BacklogStuckStateUpdate) ClearNotifiedAt() *BacklogStuckStateUpdate {
	_u.mutation.ClearNotifiedAt()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *BacklogStuckStateUpdate) SetResolvedAt(v time.Time) *BacklogStuckStateUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *BacklogStuckStateUpdate) SetNillableResolvedAt(v *time.Time) *BacklogStuckStateUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *BacklogStuckStateUpdate) ClearResolvedAt() *BacklogStuckStateUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetSnoozedUntil sets the "snoozed_until" field.
func (_u *BacklogStuckStateUpdate) SetSnoozedUntil(v time.Time) *BacklogStuckStateUpdate {
	_u.mutation.SetSnoozedUntil(v)
	return _u
}

// SetNillableSnoozedUntil sets the "snoozed_until" field if the given value is not nil.
func (_u *BacklogStuckStateUpdate) SetNillableSnoozedUntil(v *time.Time) *BacklogStuckStateUpdate {
	if v != nil {
		_u.SetSnoozedUntil(*v)
	}
	return _u
}

// ClearSnoozedUntil clears the value of the "snoozed_until" field.
func (_u *BacklogStuckStateUpdate) ClearSnoozedUntil() *BacklogStuckStateUpdate {
	_u.mutation.ClearSnoozedUntil()
	return _u
}

// SetContext sets the "context" field.
func (_u *BacklogStuckStateUpdate) SetContext(v string) *BacklogStuckStateUpdate {
	_u.mutation.SetContext(v)
	return _u
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (_u *BacklogStuckStateUpdate) SetNillableContext(v *string) *BacklogStuckStateUpdate {
	if v != nil {
		_u.SetContext(*v)
	}
	return _u
}

// ClearContext clears the value of the "context" field.
func (_u *BacklogStuckStateUpdate) ClearContext() *BacklogStuckStateUpdate {
	_u.mutation.ClearContext()
	return _u
}

// SetItem sets the "item" edge to the BacklogItem entity.
func (_u *BacklogStuckStateUpdate) SetItem(v *BacklogItem) *BacklogStuckStateUpdate {
	return _u.SetItemID(v.ID)
}

// Mutation returns the BacklogStuckStateMutation object of the builder.
func (_u *BacklogStuckStateUpdate) Mutation() *BacklogStuckStateMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the BacklogItem entity.
func (_u *BacklogStuckStateUpdate) ClearItem() *BacklogStuckStateUpdate {
	_u.mutation.ClearItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BacklogStuckStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BacklogStuckStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BacklogStuckStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BacklogStuckStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BacklogStuckStateUpdate) check() error {
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BacklogStuckState.item"`)
	}
	return nil
}

func (_u *BacklogStuckStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backlogstuckstate.Table, backlogstuckstate.Columns, sqlgraph.NewFieldSpec(backlogstuckstate.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(backlogstuckstate.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstDetectedAt(); ok {
		_spec.SetField(backlogstuckstate.FieldFirstDetectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(backlogstuckstate.FieldLastCheckedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NotifiedAt(); ok {
		_spec.SetField(backlogstuckstate.FieldNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.NotifiedAtCleared() {
		_spec.ClearField(backlogstuckstate.FieldNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(backlogstuckstate.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(backlogstuckstate.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SnoozedUntil(); ok {
		_spec.SetField(backlogstuckstate.FieldSnoozedUntil, field.TypeTime, value)
	}
	if _u.mutation.SnoozedUntilCleared() {
		_spec.ClearField(backlogstuckstate.FieldSnoozedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.Context(); ok {
		_spec.SetField(backlogstuckstate.FieldContext, field.TypeString, value)
	}
	if _u.mutation.ContextCleared() {
		_spec.ClearField(backlogstuckstate.FieldContext, field.TypeString)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogstuckstate.ItemTable,
			Columns: []string{backlogstuckstate.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogstuckstate.ItemTable,
			Columns: []string{backlogstuckstate.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backlogstuckstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BacklogStuckStateUpdateOne is the builder for updating a single BacklogStuckState entity.
type BacklogStuckStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BacklogStuckStateMutation
}

// SetItemID sets the "item_id" field.
func (_u *BacklogStuckStateUpdateOne) SetItemID(v uuid.UUID) *BacklogStuckStateUpdateOne {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *BacklogStuckStateUpdateOne) SetNillableItemID(v *uuid.UUID) *BacklogStuckStateUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *BacklogStuckStateUpdateOne) SetReason(v string) *BacklogStuckStateUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *BacklogStuckStateUpdateOne) SetNillableReason(v *string) *BacklogStuckStateUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetFirstDetectedAt sets the "first_detected_at" field.
func (_u *BacklogStuckStateUpdateOne) SetFirstDetectedAt(v time.Time) *BacklogStuckStateUpdateOne {
	_u.mutation.SetFirstDetectedAt(v)
	return _u
}

// SetNillableFirstDetectedAt sets the "first_detected_at" field if the given value is not nil.
func (_u *BacklogStuckStateUpdateOne) SetNillableFirstDetectedAt(v *time.Time) *BacklogStuckStateUpdateOne {
	if v != nil {
		_u.SetFirstDetectedAt(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *BacklogStuckStateUpdateOne) SetLastCheckedAt(v time.Time) *BacklogStuckStateUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *BacklogStuckStateUpdateOne) SetNillableLastCheckedAt(v *time.Time) *BacklogStuckStateUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// SetNotifiedAt sets the "notified_at" field.
func (_u *BacklogStuckStateUpdateOne) SetNotifiedAt(v time.Time) *BacklogStuckStateUpdateOne {
	_u.mutation.SetNotifiedAt(v)
	return _u
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_u *BacklogStuckStateUpdateOne) SetNillableNotifiedAt(v *time.Time) *BacklogStuckStateUpdateOne {
	if v != nil {
		_u.SetNotifiedAt(*v)
	}
	return _u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (_u *BacklogStuckStateUpdateOne) ClearNotifiedAt() *BacklogStuckStateUpdateOne {
	_u.mutation.ClearNotifiedAt()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *BacklogStuckStateUpdateOne) SetResolvedAt(v time.Time) *BacklogStuckStateUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *BacklogStuckStateUpdateOne) SetNillableResolvedAt(v *time.Time) *BacklogStuckStateUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *BacklogStuckStateUpdateOne) ClearResolvedAt() *BacklogStuckStateUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetSnoozedUntil sets the "snoozed_until" field.
func (_u *BacklogStuckStateUpdateOne) SetSnoozedUntil(v time.Time) *BacklogStuckStateUpdateOne {
	_u.mutation.SetSnoozedUntil(v)
	return _u
}

// SetNillableSnoozedUntil sets the "snoozed_until" field if the given value is not nil.
func (_u *BacklogStuckStateUpdateOne) SetNillableSnoozedUntil(v *time.Time) *BacklogStuckStateUpdateOne {
	if v != nil {
		_u.SetSnoozedUntil(*v)
	}
	return _u
}

// ClearSnoozedUntil clears the value of the "snoozed_until" field.
func (_u *BacklogStuckStateUpdateOne) ClearSnoozedUntil() *BacklogStuckStateUpdateOne {
	_u.mutation.ClearSnoozedUntil()
	return _u
}

// SetContext sets the "context" field.
func (_u *BacklogStuckStateUpdateOne) SetContext(v string) *BacklogStuckStateUpdateOne {
	_u.mutation.SetContext(v)
	return _u
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (_u *BacklogStuckStateUpdateOne) SetNillableContext(v *string) *BacklogStuckStateUpdateOne {
	if v != nil {
		_u.SetContext(*v)
	}
	return _u
}

// ClearContext clears the value of the "context" field.
func (_u *BacklogStuckStateUpdateOne) ClearContext() *BacklogStuckStateUpdateOne {
	_u.mutation.ClearContext()
	return _u
}

// SetItem sets the "item" edge to the BacklogItem entity.
func (_u *BacklogStuckStateUpdateOne) SetItem(v *BacklogItem) *BacklogStuckStateUpdateOne {
	return _u.SetItemID(v.ID)
}

// Mutation returns the BacklogStuckStateMutation object of the builder.
func (_u *BacklogStuckStateUpdateOne) Mutation() *BacklogStuckStateMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the BacklogItem entity.
func (_u *BacklogStuckStateUpdateOne) ClearItem() *BacklogStuckStateUpdateOne {
	_u.mutation.ClearItem()
	return _u
}

// Where appends a list predicates to the BacklogStuckStateUpdate builder.
func (_u *BacklogStuckStateUpdateOne) Where(ps ...predicate.BacklogStuckState) *BacklogStuckStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BacklogStuckStateUpdateOne) Select(field string, fields ...string) *BacklogStuckStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BacklogStuckState entity.
func (_u *BacklogStuckStateUpdateOne) Save(ctx context.Context) (*BacklogStuckState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BacklogStuckStateUpdateOne) SaveX(ctx context.Context) *BacklogStuckState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BacklogStuckStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BacklogStuckStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BacklogStuckStateUpdateOne) check() error {
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BacklogStuckState.item"`)
	}
	return nil
}

func (_u *BacklogStuckStateUpdateOne) sqlSave(ctx context.Context) (_node *BacklogStuckState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backlogstuckstate.Table, backlogstuckstate.Columns, sqlgraph.NewFieldSpec(backlogstuckstate.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BacklogStuckState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backlogstuckstate.FieldID)
		for _, f := range fields {
			if !backlogstuckstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backlogstuckstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(backlogstuckstate.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstDetectedAt(); ok {
		_spec.SetField(backlogstuckstate.FieldFirstDetectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(backlogstuckstate.FieldLastCheckedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NotifiedAt(); ok {
		_spec.SetField(backlogstuckstate.FieldNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.NotifiedAtCleared() {
		_spec.ClearField(backlogstuckstate.FieldNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(backlogstuckstate.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(backlogstuckstate.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SnoozedUntil(); ok {
		_spec.SetField(backlogstuckstate.FieldSnoozedUntil, field.TypeTime, value)
	}
	if _u.mutation.SnoozedUntilCleared() {
		_spec.ClearField(backlogstuckstate.FieldSnoozedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.Context(); ok {
		_spec.SetField(backlogstuckstate.FieldContext, field.TypeString, value)
	}
	if _u.mutation.ContextCleared() {
		_spec.ClearField(backlogstuckstate.FieldContext, field.TypeString)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogstuckstate.ItemTable,
			Columns: []string{backlogstuckstate.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogstuckstate.ItemTable,
			Columns: []string{backlogstuckstate.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BacklogStuckState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backlogstuckstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
