// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tstapler/stapler-squad/session/ent/backlogitem"
	"github.com/tstapler/stapler-squad/session/ent/backlogstuckstate"
)

// BacklogStuckState is the model entity for the BacklogStuckState schema.
type BacklogStuckState struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID uuid.UUID `json:"item_id,omitempty"`
	// Validated in Go by domain.StuckReason.IsValid(); stored as a plain string to match the house BacklogStatus/ReviewOutcome style.
	Reason string `json:"reason,omitempty"`
	// When this stuck condition was first observed. Reset to now on a resolve-in-place reopen.
	FirstDetectedAt time.Time `json:"first_detected_at,omitempty"`
	// Most recent reconcile tick that re-confirmed the condition still holds.
	LastCheckedAt time.Time `json:"last_checked_at,omitempty"`
	// When the operator notification fired. NULL = detected but not yet notified. Cleared on reopen.
	NotifiedAt *time.Time `json:"notified_at,omitempty"`
	// When the condition was observed to clear. NULL = currently open (stuck).
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// Suppresses this row from the active view/re-notification until this time.
	SnoozedUntil *time.Time `json:"snoozed_until,omitempty"`
	// Human-readable 'why' string, e.g. 'last verdict: FAIL' or 'PR #148 green & mergeable 3d'.
	Context string `json:"context,omitempty"`
	// Count of automated remediation attempts actually made for this open row (incremented per attempt, not per detection-sweep tick). Reset to 0 by ResetStuckRemediation/BulkResetStuckRemediation, and implicitly by MarkStuck's reopen-in-place path. remediation_attempts >= maxRemediationAttempts (5) with next_remediation_at NULL is how a 'parked' row is represented — no separate boolean.
	RemediationAttempts int32 `json:"remediation_attempts,omitempty"`
	// When this row becomes eligible for the next automated remediation attempt. NULL while remediation_attempts is 0 means 'eligible immediately'. Set back to NULL once remediation_attempts reaches the cap (parked).
	NextRemediationAt *time.Time `json:"next_remediation_at,omitempty"`
	// The server boot time (session.serverStartTime) of the most recent restart-grace pass consumed by this row, if any. A restart-grace pass lets a remediation action run without consuming remediation_attempts/advancing next_remediation_at when the detected failure coincides with a service restart (in-flight AutonomousDriver goroutines are lost on restart, not a real remediation failure) — at most one free pass per boot, tracked by comparing this field to the current boot time.
	GraceBootTime *time.Time `json:"grace_boot_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BacklogStuckStateQuery when eager-loading is set.
	Edges        BacklogStuckStateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BacklogStuckStateEdges holds the relations/edges for other nodes in the graph.
type BacklogStuckStateEdges struct {
	// Item holds the value of the item edge.
	Item *BacklogItem `json:"item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BacklogStuckStateEdges) ItemOrErr() (*BacklogItem, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: backlogitem.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BacklogStuckState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backlogstuckstate.FieldRemediationAttempts:
			values[i] = new(sql.NullInt64)
		case backlogstuckstate.FieldReason, backlogstuckstate.FieldContext:
			values[i] = new(sql.NullString)
		case backlogstuckstate.FieldFirstDetectedAt, backlogstuckstate.FieldLastCheckedAt, backlogstuckstate.FieldNotifiedAt, backlogstuckstate.FieldResolvedAt, backlogstuckstate.FieldSnoozedUntil, backlogstuckstate.FieldNextRemediationAt, backlogstuckstate.FieldGraceBootTime:
			values[i] = new(sql.NullTime)
		case backlogstuckstate.FieldID, backlogstuckstate.FieldItemID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BacklogStuckState fields.
func (_m *BacklogStuckState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backlogstuckstate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case backlogstuckstate.FieldItemID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value != nil {
				_m.ItemID = *value
			}
		case backlogstuckstate.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case backlogstuckstate.FieldFirstDetectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_detected_at", values[i])
			} else if value.Valid {
				_m.FirstDetectedAt = value.Time
			}
		case backlogstuckstate.FieldLastCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_checked_at", values[i])
			} else if value.Valid {
				_m.LastCheckedAt = value.Time
			}
		case backlogstuckstate.FieldNotifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field notified_at", values[i])
			} else if value.Valid {
				_m.NotifiedAt = new(time.Time)
				*_m.NotifiedAt = value.Time
			}
		case backlogstuckstate.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		case backlogstuckstate.FieldSnoozedUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field snoozed_until", values[i])
			} else if value.Valid {
				_m.SnoozedUntil = new(time.Time)
				*_m.SnoozedUntil = value.Time
			}
		case backlogstuckstate.FieldContext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context", values[i])
			} else if value.Valid {
				_m.Context = value.String
			}
		case backlogstuckstate.FieldRemediationAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field remediation_attempts", values[i])
			} else if value.Valid {
				_m.RemediationAttempts = int32(value.Int64)
			}
		case backlogstuckstate.FieldNextRemediationAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_remediation_at", values[i])
			} else if value.Valid {
				_m.NextRemediationAt = new(time.Time)
				*_m.NextRemediationAt = value.Time
			}
		case backlogstuckstate.FieldGraceBootTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field grace_boot_time", values[i])
			} else if value.Valid {
				_m.GraceBootTime = new(time.Time)
				*_m.GraceBootTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BacklogStuckState.
// This includes values selected through modifiers, order, etc.
func (_m *BacklogStuckState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItem queries the "item" edge of the BacklogStuckState entity.
func (_m *BacklogStuckState) QueryItem() *BacklogItemQuery {
	return NewBacklogStuckStateClient(_m.config).QueryItem(_m)
}

// Update returns a builder for updating this BacklogStuckState.
// Note that you need to call BacklogStuckState.Unwrap() before calling this method if this BacklogStuckState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BacklogStuckState) Update() *BacklogStuckStateUpdateOne {
	return NewBacklogStuckStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BacklogStuckState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BacklogStuckState) Unwrap() *BacklogStuckState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BacklogStuckState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BacklogStuckState) String() string {
	var builder strings.Builder
	builder.WriteString("BacklogStuckState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("item_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ItemID))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("first_detected_at=")
	builder.WriteString(_m.FirstDetectedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_checked_at=")
	builder.WriteString(_m.LastCheckedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.NotifiedAt; v != nil {
		builder.WriteString("notified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SnoozedUntil; v != nil {
		builder.WriteString("snoozed_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("context=")
	builder.WriteString(_m.Context)
	builder.WriteString(", ")
	builder.WriteString("remediation_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemediationAttempts))
	builder.WriteString(", ")
	if v := _m.NextRemediationAt; v != nil {
		builder.WriteString("next_remediation_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.GraceBootTime; v != nil {
		builder.WriteString("grace_boot_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BacklogStuckStates is a parsable slice of BacklogStuckState.
type BacklogStuckStates []*BacklogStuckState
