// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tstapler/stapler-squad/session/ent/backlogitem"
	"github.com/tstapler/stapler-squad/session/ent/backlogprogressnote"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
)

// BacklogProgressNoteUpdate is the builder for updating BacklogProgressNote entities.
type BacklogProgressNoteUpdate struct {
	config
	hooks    []Hook
	mutation *BacklogProgressNoteMutation
}

// Where appends a list predicates to the BacklogProgressNoteUpdate builder.
func (_u *BacklogProgressNoteUpdate) Where(ps ...predicate.BacklogProgressNote) *BacklogProgressNoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *BacklogProgressNoteUpdate) SetItemID(v uuid.UUID) *BacklogProgressNoteUpdate {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *BacklogProgressNoteUpdate) SetNillableItemID(v *uuid.UUID) *BacklogProgressNoteUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetCriterionIndex sets the "criterion_index" field.
func (_u *BacklogProgressNoteUpdate) SetCriterionIndex(v int) *BacklogProgressNoteUpdate {
	_u.mutation.ResetCriterionIndex()
	_u.mutation.SetCriterionIndex(v)
	return _u
}

// SetNillableCriterionIndex sets the "criterion_index" field if the given value is not nil.
func (_u *BacklogProgressNoteUpdate) SetNillableCriterionIndex(v *int) *BacklogProgressNoteUpdate {
	if v != nil {
		_u.SetCriterionIndex(*v)
	}
	return _u
}

// AddCriterionIndex adds value to the "criterion_index" field.
func (_u *BacklogProgressNoteUpdate) AddCriterionIndex(v int) *BacklogProgressNoteUpdate {
	_u.mutation.AddCriterionIndex(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *BacklogProgressNoteUpdate) SetNote(v string) *BacklogProgressNoteUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *BacklogProgressNoteUpdate) SetNillableNote(v *string) *BacklogProgressNoteUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *BacklogProgressNoteUpdate) ClearNote() *BacklogProgressNoteUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BacklogProgressNoteUpdate) SetStatus(v string) *BacklogProgressNoteUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BacklogProgressNoteUpdate) SetNillableStatus(v *string) *BacklogProgressNoteUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetItem sets the "item" edge to the BacklogItem entity.
func (_u *BacklogProgressNoteUpdate) SetItem(v *BacklogItem) *BacklogProgressNoteUpdate {
	return _u.SetItemID(v.ID)
}

// Mutation returns the BacklogProgressNoteMutation object of the builder.
func (_u *BacklogProgressNoteUpdate) Mutation() *BacklogProgressNoteMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the BacklogItem entity.
func (_u *BacklogProgressNoteUpdate) ClearItem() *BacklogProgressNoteUpdate {
	_u.mutation.ClearItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BacklogProgressNoteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BacklogProgressNoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BacklogProgressNoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BacklogProgressNoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BacklogProgressNoteUpdate) check() error {
	if v, ok := _u.mutation.CriterionIndex(); ok {
		if err := backlogprogressnote.CriterionIndexValidator(v); err != nil {
			return &ValidationError{Name: "criterion_index", err: fmt.Errorf(`ent: validator failed for field "BacklogProgressNote.criterion_index": %w`, err)}
		}
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BacklogProgressNote.item"`)
	}
	return nil
}

func (_u *BacklogProgressNoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backlogprogressnote.Table, backlogprogressnote.Columns, sqlgraph.NewFieldSpec(backlogprogressnote.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CriterionIndex(); ok {
		_spec.SetField(backlogprogressnote.FieldCriterionIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCriterionIndex(); ok {
		_spec.AddField(backlogprogressnote.FieldCriterionIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(backlogprogressnote.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(backlogprogressnote.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(backlogprogressnote.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogprogressnote.ItemTable,
			Columns: []string{backlogprogressnote.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogprogressnote.ItemTable,
			Columns: []string{backlogprogressnote.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backlogprogressnote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BacklogProgressNoteUpdateOne is the builder for updating a single BacklogProgressNote entity.
type BacklogProgressNoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BacklogProgressNoteMutation
}

// SetItemID sets the "item_id" field.
func (_u *BacklogProgressNoteUpdateOne) SetItemID(v uuid.UUID) *BacklogProgressNoteUpdateOne {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *BacklogProgressNoteUpdateOne) SetNillableItemID(v *uuid.UUID) *BacklogProgressNoteUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetCriterionIndex sets the "criterion_index" field.
func (_u *BacklogProgressNoteUpdateOne) SetCriterionIndex(v int) *BacklogProgressNoteUpdateOne {
	_u.mutation.ResetCriterionIndex()
	_u.mutation.SetCriterionIndex(v)
	return _u
}

// SetNillableCriterionIndex sets the "criterion_index" field if the given value is not nil.
func (_u *BacklogProgressNoteUpdateOne) SetNillableCriterionIndex(v *int) *BacklogProgressNoteUpdateOne {
	if v != nil {
		_u.SetCriterionIndex(*v)
	}
	return _u
}

// AddCriterionIndex adds value to the "criterion_index" field.
func (_u *BacklogProgressNoteUpdateOne) AddCriterionIndex(v int) *BacklogProgressNoteUpdateOne {
	_u.mutation.AddCriterionIndex(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *BacklogProgressNoteUpdateOne) SetNote(v string) *BacklogProgressNoteUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *BacklogProgressNoteUpdateOne) SetNillableNote(v *string) *BacklogProgressNoteUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *BacklogProgressNoteUpdateOne) ClearNote() *BacklogProgressNoteUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BacklogProgressNoteUpdateOne) SetStatus(v string) *BacklogProgressNoteUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BacklogProgressNoteUpdateOne) SetNillableStatus(v *string) *BacklogProgressNoteUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetItem sets the "item" edge to the BacklogItem entity.
func (_u *BacklogProgressNoteUpdateOne) SetItem(v *BacklogItem) *BacklogProgressNoteUpdateOne {
	return _u.SetItemID(v.ID)
}

// Mutation returns the BacklogProgressNoteMutation object of the builder.
func (_u *BacklogProgressNoteUpdateOne) Mutation() *BacklogProgressNoteMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the BacklogItem entity.
func (_u *BacklogProgressNoteUpdateOne) ClearItem() *BacklogProgressNoteUpdateOne {
	_u.mutation.ClearItem()
	return _u
}

// Where appends a list predicates to the BacklogProgressNoteUpdate builder.
func (_u *BacklogProgressNoteUpdateOne) Where(ps ...predicate.BacklogProgressNote) *BacklogProgressNoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BacklogProgressNoteUpdateOne) Select(field string, fields ...string) *BacklogProgressNoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BacklogProgressNote entity.
func (_u *BacklogProgressNoteUpdateOne) Save(ctx context.Context) (*BacklogProgressNote, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BacklogProgressNoteUpdateOne) SaveX(ctx context.Context) *BacklogProgressNote {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BacklogProgressNoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BacklogProgressNoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BacklogProgressNoteUpdateOne) check() error {
	if v, ok := _u.mutation.CriterionIndex(); ok {
		if err := backlogprogressnote.CriterionIndexValidator(v); err != nil {
			return &ValidationError{Name: "criterion_index", err: fmt.Errorf(`ent: validator failed for field "BacklogProgressNote.criterion_index": %w`, err)}
		}
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BacklogProgressNote.item"`)
	}
	return nil
}

func (_u *BacklogProgressNoteUpdateOne) sqlSave(ctx context.Context) (_node *BacklogProgressNote, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backlogprogressnote.Table, backlogprogressnote.Columns, sqlgraph.NewFieldSpec(backlogprogressnote.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BacklogProgressNote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backlogprogressnote.FieldID)
		for _, f := range fields {
			if !backlogprogressnote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backlogprogressnote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CriterionIndex(); ok {
		_spec.SetField(backlogprogressnote.FieldCriterionIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCriterionIndex(); ok {
		_spec.AddField(backlogprogressnote.FieldCriterionIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(backlogprogressnote.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(backlogprogressnote.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(backlogprogressnote.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogprogressnote.ItemTable,
			Columns: []string{backlogprogressnote.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backlogprogressnote.ItemTable,
			Columns: []string{backlogprogressnote.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BacklogProgressNote{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backlogprogressnote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
