// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tstapler/stapler-squad/session/ent/backlogstuckstate"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
)

// BacklogStuckStateDelete is the builder for deleting a BacklogStuckState entity.
type BacklogStuckStateDelete struct {
	config
	hooks    []Hook
	mutation *BacklogStuckStateMutation
}

// Where appends a list predicates to the BacklogStuckStateDelete builder.
func (_d *BacklogStuckStateDelete) Where(ps ...predicate.BacklogStuckState) *BacklogStuckStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BacklogStuckStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BacklogStuckStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BacklogStuckStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(backlogstuckstate.Table, sqlgraph.NewFieldSpec(backlogstuckstate.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BacklogStuckStateDeleteOne is the builder for deleting a single BacklogStuckState entity.
type BacklogStuckStateDeleteOne struct {
	_d *BacklogStuckStateDelete
}

// Where appends a list predicates to the BacklogStuckStateDelete builder.
func (_d *BacklogStuckStateDeleteOne) Where(ps ...predicate.BacklogStuckState) *BacklogStuckStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BacklogStuckStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{backlogstuckstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BacklogStuckStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
