// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/tstapler/stapler-squad/session/ent/diffstats"
	"github.com/tstapler/stapler-squad/session/ent/session"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiffStatsCreate is the builder for creating a DiffStats entity.
type DiffStatsCreate struct {
	config
	mutation *DiffStatsMutation
	hooks    []Hook
}

// SetAdded sets the "added" field.
func (_c *DiffStatsCreate) SetAdded(v int) *DiffStatsCreate {
	_c.mutation.SetAdded(v)
	return _c
}

// SetNillableAdded sets the "added" field if the given value is not nil.
func (_c *DiffStatsCreate) SetNillableAdded(v *int) *DiffStatsCreate {
	if v != nil {
		_c.SetAdded(*v)
	}
	return _c
}

// SetRemoved sets the "removed" field.
func (_c *DiffStatsCreate) SetRemoved(v int) *DiffStatsCreate {
	_c.mutation.SetRemoved(v)
	return _c
}

// SetNillableRemoved sets the "removed" field if the given value is not nil.
func (_c *DiffStatsCreate) SetNillableRemoved(v *int) *DiffStatsCreate {
	if v != nil {
		_c.SetRemoved(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *DiffStatsCreate) SetContent(v string) *DiffStatsCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *DiffStatsCreate) SetNillableContent(v *string) *DiffStatsCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetSessionID sets the "session" edge to the Session entity by ID.
func (_c *DiffStatsCreate) SetSessionID(id int) *DiffStatsCreate {
	_c.mutation.SetSessionID(id)
	return _c
}

// SetSession sets the "session" edge to the Session entity.
func (_c *DiffStatsCreate) SetSession(v *Session) *DiffStatsCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the DiffStatsMutation object of the builder.
func (_c *DiffStatsCreate) Mutation() *DiffStatsMutation {
	return _c.mutation
}

// Save creates the DiffStats in the database.
func (_c *DiffStatsCreate) Save(ctx context.Context) (*DiffStats, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiffStatsCreate) SaveX(ctx context.Context) *DiffStats {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiffStatsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiffStatsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiffStatsCreate) defaults() {
	if _, ok := _c.mutation.Added(); !ok {
		v := diffstats.DefaultAdded
		_c.mutation.SetAdded(v)
	}
	if _, ok := _c.mutation.Removed(); !ok {
		v := diffstats.DefaultRemoved
		_c.mutation.SetRemoved(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiffStatsCreate) check() error {
	if _, ok := _c.mutation.Added(); !ok {
		return &ValidationError{Name: "added", err: errors.New(`ent: missing required field "DiffStats.added"`)}
	}
	if _, ok := _c.mutation.Removed(); !ok {
		return &ValidationError{Name: "removed", err: errors.New(`ent: missing required field "DiffStats.removed"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "DiffStats.session"`)}
	}
	return nil
}

func (_c *DiffStatsCreate) sqlSave(ctx context.Context) (*DiffStats, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiffStatsCreate) createSpec() (*DiffStats, *sqlgraph.CreateSpec) {
	var (
		_node = &DiffStats{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(diffstats.Table, sqlgraph.NewFieldSpec(diffstats.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Added(); ok {
		_spec.SetField(diffstats.FieldAdded, field.TypeInt, value)
		_node.Added = value
	}
	if value, ok := _c.mutation.Removed(); ok {
		_spec.SetField(diffstats.FieldRemoved, field.TypeInt, value)
		_node.Removed = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(diffstats.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   diffstats.SessionTable,
			Columns: []string{diffstats.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.session_diff_stats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DiffStatsCreateBulk is the builder for creating many DiffStats entities in bulk.
type DiffStatsCreateBulk struct {
	config
	err      error
	builders []*DiffStatsCreate
}

// Save creates the DiffStats entities in the database.
func (_c *DiffStatsCreateBulk) Save(ctx context.Context) ([]*DiffStats, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiffStats, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiffStatsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiffStatsCreateBulk) SaveX(ctx context.Context) []*DiffStats {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiffStatsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiffStatsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
