// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/tstapler/stapler-squad/session/ent/diffstats"
	"github.com/tstapler/stapler-squad/session/ent/session"
)

// DiffStats is the model entity for the DiffStats schema.
type DiffStats struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Added holds the value of the "added" field.
	Added int `json:"added,omitempty"`
	// Removed holds the value of the "removed" field.
	Removed int `json:"removed,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DiffStatsQuery when eager-loading is set.
	Edges              DiffStatsEdges `json:"edges"`
	session_diff_stats *int
	selectValues       sql.SelectValues
}

// DiffStatsEdges holds the relations/edges for other nodes in the graph.
type DiffStatsEdges struct {
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DiffStatsEdges) SessionOrErr() (*Session, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: session.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiffStats) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case diffstats.FieldID, diffstats.FieldAdded, diffstats.FieldRemoved:
			values[i] = new(sql.NullInt64)
		case diffstats.FieldContent:
			values[i] = new(sql.NullString)
		case diffstats.ForeignKeys[0]: // session_diff_stats
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiffStats fields.
func (_m *DiffStats) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case diffstats.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case diffstats.FieldAdded:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field added", values[i])
			} else if value.Valid {
				_m.Added = int(value.Int64)
			}
		case diffstats.FieldRemoved:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field removed", values[i])
			} else if value.Valid {
				_m.Removed = int(value.Int64)
			}
		case diffstats.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case diffstats.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field session_diff_stats", value)
			} else if value.Valid {
				_m.session_diff_stats = new(int)
				*_m.session_diff_stats = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DiffStats.
// This includes values selected through modifiers, order, etc.
func (_m *DiffStats) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the DiffStats entity.
func (_m *DiffStats) QuerySession() *SessionQuery {
	return NewDiffStatsClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this DiffStats.
// Note that you need to call DiffStats.Unwrap() before calling this method if this DiffStats
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DiffStats) Update() *DiffStatsUpdateOne {
	return NewDiffStatsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DiffStats entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DiffStats) Unwrap() *DiffStats {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiffStats is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DiffStats) String() string {
	var builder strings.Builder
	builder.WriteString("DiffStats(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("added=")
	builder.WriteString(fmt.Sprintf("%v", _m.Added))
	builder.WriteString(", ")
	builder.WriteString("removed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Removed))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteByte(')')
	return builder.String()
}

// DiffStatsSlice is a parsable slice of DiffStats.
type DiffStatsSlice []*DiffStats
