// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tstapler/stapler-squad/session/ent/backlogitem"
	"github.com/tstapler/stapler-squad/session/ent/itemsource"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
	"github.com/tstapler/stapler-squad/session/ent/sourcesyncevent"
)

// ItemSourceUpdate is the builder for updating ItemSource entities.
type ItemSourceUpdate struct {
	config
	hooks    []Hook
	mutation *ItemSourceMutation
}

// Where appends a list predicates to the ItemSourceUpdate builder.
func (_u *ItemSourceUpdate) Where(ps ...predicate.ItemSource) *ItemSourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *ItemSourceUpdate) SetPluginID(v string) *ItemSourceUpdate {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *ItemSourceUpdate) SetNillablePluginID(v *string) *ItemSourceUpdate {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ItemSourceUpdate) SetDisplayName(v string) *ItemSourceUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ItemSourceUpdate) SetNillableDisplayName(v *string) *ItemSourceUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ItemSourceUpdate) SetConfig(v string) *ItemSourceUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *ItemSourceUpdate) SetNillableConfig(v *string) *ItemSourceUpdate {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *ItemSourceUpdate) ClearConfig() *ItemSourceUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ItemSourceUpdate) SetEnabled(v bool) *ItemSourceUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ItemSourceUpdate) SetNillableEnabled(v *bool) *ItemSourceUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSyncCursor sets the "sync_cursor" field.
func (_u *ItemSourceUpdate) SetSyncCursor(v string) *ItemSourceUpdate {
	_u.mutation.SetSyncCursor(v)
	return _u
}

// SetNillableSyncCursor sets the "sync_cursor" field if the given value is not nil.
func (_u *ItemSourceUpdate) SetNillableSyncCursor(v *string) *ItemSourceUpdate {
	if v != nil {
		_u.SetSyncCursor(*v)
	}
	return _u
}

// ClearSyncCursor clears the value of the "sync_cursor" field.
func (_u *ItemSourceUpdate) ClearSyncCursor() *ItemSourceUpdate {
	_u.mutation.ClearSyncCursor()
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *ItemSourceUpdate) SetLastSyncedAt(v time.Time) *ItemSourceUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *ItemSourceUpdate) SetNillableLastSyncedAt(v *time.Time) *ItemSourceUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *ItemSourceUpdate) ClearLastSyncedAt() *ItemSourceUpdate {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ItemSourceUpdate) SetUpdatedAt(v time.Time) *ItemSourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddBacklogItemIDs adds the "backlog_items" edge to the BacklogItem entity by IDs.
func (_u *ItemSourceUpdate) AddBacklogItemIDs(ids ...uuid.UUID) *ItemSourceUpdate {
	_u.mutation.AddBacklogItemIDs(ids...)
	return _u
}

// AddBacklogItems adds the "backlog_items" edges to the BacklogItem entity.
func (_u *ItemSourceUpdate) AddBacklogItems(v ...*BacklogItem) *ItemSourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBacklogItemIDs(ids...)
}

// AddSyncEventIDs adds the "sync_events" edge to the SourceSyncEvent entity by IDs.
func (_u *ItemSourceUpdate) AddSyncEventIDs(ids ...uuid.UUID) *ItemSourceUpdate {
	_u.mutation.AddSyncEventIDs(ids...)
	return _u
}

// AddSyncEvents adds the "sync_events" edges to the SourceSyncEvent entity.
func (_u *ItemSourceUpdate) AddSyncEvents(v ...*SourceSyncEvent) *ItemSourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncEventIDs(ids...)
}

// Mutation returns the ItemSourceMutation object of the builder.
func (_u *ItemSourceUpdate) Mutation() *ItemSourceMutation {
	return _u.mutation
}

// ClearBacklogItems clears all "backlog_items" edges to the BacklogItem entity.
func (_u *ItemSourceUpdate) ClearBacklogItems() *ItemSourceUpdate {
	_u.mutation.ClearBacklogItems()
	return _u
}

// RemoveBacklogItemIDs removes the "backlog_items" edge to BacklogItem entities by IDs.
func (_u *ItemSourceUpdate) RemoveBacklogItemIDs(ids ...uuid.UUID) *ItemSourceUpdate {
	_u.mutation.RemoveBacklogItemIDs(ids...)
	return _u
}

// RemoveBacklogItems removes "backlog_items" edges to BacklogItem entities.
func (_u *ItemSourceUpdate) RemoveBacklogItems(v ...*BacklogItem) *ItemSourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBacklogItemIDs(ids...)
}

// ClearSyncEvents clears all "sync_events" edges to the SourceSyncEvent entity.
func (_u *ItemSourceUpdate) ClearSyncEvents() *ItemSourceUpdate {
	_u.mutation.ClearSyncEvents()
	return _u
}

// RemoveSyncEventIDs removes the "sync_events" edge to SourceSyncEvent entities by IDs.
func (_u *ItemSourceUpdate) RemoveSyncEventIDs(ids ...uuid.UUID) *ItemSourceUpdate {
	_u.mutation.RemoveSyncEventIDs(ids...)
	return _u
}

// RemoveSyncEvents removes "sync_events" edges to SourceSyncEvent entities.
func (_u *ItemSourceUpdate) RemoveSyncEvents(v ...*SourceSyncEvent) *ItemSourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ItemSourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemSourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ItemSourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemSourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ItemSourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := itemsource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ItemSourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(itemsource.Table, itemsource.Columns, sqlgraph.NewFieldSpec(itemsource.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PluginID(); ok {
		_spec.SetField(itemsource.FieldPluginID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(itemsource.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(itemsource.FieldConfig, field.TypeString, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(itemsource.FieldConfig, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(itemsource.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SyncCursor(); ok {
		_spec.SetField(itemsource.FieldSyncCursor, field.TypeString, value)
	}
	if _u.mutation.SyncCursorCleared() {
		_spec.ClearField(itemsource.FieldSyncCursor, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(itemsource.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(itemsource.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(itemsource.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BacklogItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.BacklogItemsTable,
			Columns: []string{itemsource.BacklogItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBacklogItemsIDs(); len(nodes) > 0 && !_u.mutation.BacklogItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.BacklogItemsTable,
			Columns: []string{itemsource.BacklogItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BacklogItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.BacklogItemsTable,
			Columns: []string{itemsource.BacklogItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.SyncEventsTable,
			Columns: []string{itemsource.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesyncevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncEventsIDs(); len(nodes) > 0 && !_u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.SyncEventsTable,
			Columns: []string{itemsource.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesyncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.SyncEventsTable,
			Columns: []string{itemsource.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesyncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ItemSourceUpdateOne is the builder for updating a single ItemSource entity.
type ItemSourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemSourceMutation
}

// SetPluginID sets the "plugin_id" field.
func (_u *ItemSourceUpdateOne) SetPluginID(v string) *ItemSourceUpdateOne {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *ItemSourceUpdateOne) SetNillablePluginID(v *string) *ItemSourceUpdateOne {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ItemSourceUpdateOne) SetDisplayName(v string) *ItemSourceUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ItemSourceUpdateOne) SetNillableDisplayName(v *string) *ItemSourceUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ItemSourceUpdateOne) SetConfig(v string) *ItemSourceUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *ItemSourceUpdateOne) SetNillableConfig(v *string) *ItemSourceUpdateOne {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *ItemSourceUpdateOne) ClearConfig() *ItemSourceUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ItemSourceUpdateOne) SetEnabled(v bool) *ItemSourceUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ItemSourceUpdateOne) SetNillableEnabled(v *bool) *ItemSourceUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSyncCursor sets the "sync_cursor" field.
func (_u *ItemSourceUpdateOne) SetSyncCursor(v string) *ItemSourceUpdateOne {
	_u.mutation.SetSyncCursor(v)
	return _u
}

// SetNillableSyncCursor sets the "sync_cursor" field if the given value is not nil.
func (_u *ItemSourceUpdateOne) SetNillableSyncCursor(v *string) *ItemSourceUpdateOne {
	if v != nil {
		_u.SetSyncCursor(*v)
	}
	return _u
}

// ClearSyncCursor clears the value of the "sync_cursor" field.
func (_u *ItemSourceUpdateOne) ClearSyncCursor() *ItemSourceUpdateOne {
	_u.mutation.ClearSyncCursor()
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *ItemSourceUpdateOne) SetLastSyncedAt(v time.Time) *ItemSourceUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *ItemSourceUpdateOne) SetNillableLastSyncedAt(v *time.Time) *ItemSourceUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *ItemSourceUpdateOne) ClearLastSyncedAt() *ItemSourceUpdateOne {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ItemSourceUpdateOne) SetUpdatedAt(v time.Time) *ItemSourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddBacklogItemIDs adds the "backlog_items" edge to the BacklogItem entity by IDs.
func (_u *ItemSourceUpdateOne) AddBacklogItemIDs(ids ...uuid.UUID) *ItemSourceUpdateOne {
	_u.mutation.AddBacklogItemIDs(ids...)
	return _u
}

// AddBacklogItems adds the "backlog_items" edges to the BacklogItem entity.
func (_u *ItemSourceUpdateOne) AddBacklogItems(v ...*BacklogItem) *ItemSourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBacklogItemIDs(ids...)
}

// AddSyncEventIDs adds the "sync_events" edge to the SourceSyncEvent entity by IDs.
func (_u *ItemSourceUpdateOne) AddSyncEventIDs(ids ...uuid.UUID) *ItemSourceUpdateOne {
	_u.mutation.AddSyncEventIDs(ids...)
	return _u
}

// AddSyncEvents adds the "sync_events" edges to the SourceSyncEvent entity.
func (_u *ItemSourceUpdateOne) AddSyncEvents(v ...*SourceSyncEvent) *ItemSourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncEventIDs(ids...)
}

// Mutation returns the ItemSourceMutation object of the builder.
func (_u *ItemSourceUpdateOne) Mutation() *ItemSourceMutation {
	return _u.mutation
}

// ClearBacklogItems clears all "backlog_items" edges to the BacklogItem entity.
func (_u *ItemSourceUpdateOne) ClearBacklogItems() *ItemSourceUpdateOne {
	_u.mutation.ClearBacklogItems()
	return _u
}

// RemoveBacklogItemIDs removes the "backlog_items" edge to BacklogItem entities by IDs.
func (_u *ItemSourceUpdateOne) RemoveBacklogItemIDs(ids ...uuid.UUID) *ItemSourceUpdateOne {
	_u.mutation.RemoveBacklogItemIDs(ids...)
	return _u
}

// RemoveBacklogItems removes "backlog_items" edges to BacklogItem entities.
func (_u *ItemSourceUpdateOne) RemoveBacklogItems(v ...*BacklogItem) *ItemSourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBacklogItemIDs(ids...)
}

// ClearSyncEvents clears all "sync_events" edges to the SourceSyncEvent entity.
func (_u *ItemSourceUpdateOne) ClearSyncEvents() *ItemSourceUpdateOne {
	_u.mutation.ClearSyncEvents()
	return _u
}

// RemoveSyncEventIDs removes the "sync_events" edge to SourceSyncEvent entities by IDs.
func (_u *ItemSourceUpdateOne) RemoveSyncEventIDs(ids ...uuid.UUID) *ItemSourceUpdateOne {
	_u.mutation.RemoveSyncEventIDs(ids...)
	return _u
}

// RemoveSyncEvents removes "sync_events" edges to SourceSyncEvent entities.
func (_u *ItemSourceUpdateOne) RemoveSyncEvents(v ...*SourceSyncEvent) *ItemSourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncEventIDs(ids...)
}

// Where appends a list predicates to the ItemSourceUpdate builder.
func (_u *ItemSourceUpdateOne) Where(ps ...predicate.ItemSource) *ItemSourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ItemSourceUpdateOne) Select(field string, fields ...string) *ItemSourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ItemSource entity.
func (_u *ItemSourceUpdateOne) Save(ctx context.Context) (*ItemSource, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemSourceUpdateOne) SaveX(ctx context.Context) *ItemSource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ItemSourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemSourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ItemSourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := itemsource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ItemSourceUpdateOne) sqlSave(ctx context.Context) (_node *ItemSource, err error) {
	_spec := sqlgraph.NewUpdateSpec(itemsource.Table, itemsource.Columns, sqlgraph.NewFieldSpec(itemsource.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ItemSource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, itemsource.FieldID)
		for _, f := range fields {
			if !itemsource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != itemsource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PluginID(); ok {
		_spec.SetField(itemsource.FieldPluginID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(itemsource.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(itemsource.FieldConfig, field.TypeString, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(itemsource.FieldConfig, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(itemsource.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SyncCursor(); ok {
		_spec.SetField(itemsource.FieldSyncCursor, field.TypeString, value)
	}
	if _u.mutation.SyncCursorCleared() {
		_spec.ClearField(itemsource.FieldSyncCursor, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(itemsource.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(itemsource.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(itemsource.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BacklogItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.BacklogItemsTable,
			Columns: []string{itemsource.BacklogItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBacklogItemsIDs(); len(nodes) > 0 && !_u.mutation.BacklogItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.BacklogItemsTable,
			Columns: []string{itemsource.BacklogItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BacklogItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.BacklogItemsTable,
			Columns: []string{itemsource.BacklogItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backlogitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.SyncEventsTable,
			Columns: []string{itemsource.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesyncevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncEventsIDs(); len(nodes) > 0 && !_u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.SyncEventsTable,
			Columns: []string{itemsource.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesyncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemsource.SyncEventsTable,
			Columns: []string{itemsource.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesyncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ItemSource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
