// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/tstapler/stapler-squad/session/ent/sessionsummary"
)

// SessionSummary is the model entity for the SessionSummary schema.
type SessionSummary struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// SessionTitle holds the value of the "session_title" field.
	SessionTitle string `json:"session_title,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Narrative holds the value of the "narrative" field.
	Narrative string `json:"narrative,omitempty"`
	// NarrativeFallbackUsed holds the value of the "narrative_fallback_used" field.
	NarrativeFallbackUsed bool `json:"narrative_fallback_used,omitempty"`
	// DiffFilesChanged holds the value of the "diff_files_changed" field.
	DiffFilesChanged int `json:"diff_files_changed,omitempty"`
	// DiffAdded holds the value of the "diff_added" field.
	DiffAdded int `json:"diff_added,omitempty"`
	// DiffRemoved holds the value of the "diff_removed" field.
	DiffRemoved int `json:"diff_removed,omitempty"`
	// DecisionsAutoApproved holds the value of the "decisions_auto_approved" field.
	DecisionsAutoApproved int `json:"decisions_auto_approved,omitempty"`
	// DecisionsManuallyApproved holds the value of the "decisions_manually_approved" field.
	DecisionsManuallyApproved int `json:"decisions_manually_approved,omitempty"`
	// DecisionsDenied holds the value of the "decisions_denied" field.
	DecisionsDenied int `json:"decisions_denied,omitempty"`
	// DecisionsReviewQueueResolved holds the value of the "decisions_review_queue_resolved" field.
	DecisionsReviewQueueResolved int `json:"decisions_review_queue_resolved,omitempty"`
	// DecisionsStillOpen holds the value of the "decisions_still_open" field.
	DecisionsStillOpen int `json:"decisions_still_open,omitempty"`
	// SessionStartedAt holds the value of the "session_started_at" field.
	SessionStartedAt *time.Time `json:"session_started_at,omitempty"`
	// SessionStoppedAt holds the value of the "session_stopped_at" field.
	SessionStoppedAt *time.Time `json:"session_stopped_at,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs *int64 `json:"duration_ms,omitempty"`
	// TotalTokens holds the value of the "total_tokens" field.
	TotalTokens *int64 `json:"total_tokens,omitempty"`
	// EstimatedCostUsd holds the value of the "estimated_cost_usd" field.
	EstimatedCostUsd *float64 `json:"estimated_cost_usd,omitempty"`
	// CostDataUnavailable holds the value of the "cost_data_unavailable" field.
	CostDataUnavailable bool `json:"cost_data_unavailable,omitempty"`
	// Markdown holds the value of the "markdown" field.
	Markdown string `json:"markdown,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// ErrorStage holds the value of the "error_stage" field.
	ErrorStage string `json:"error_stage,omitempty"`
	// GenerationStartedAt holds the value of the "generation_started_at" field.
	GenerationStartedAt *time.Time `json:"generation_started_at,omitempty"`
	// GeneratedAt holds the value of the "generated_at" field.
	GeneratedAt *time.Time `json:"generated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SessionSummary) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sessionsummary.FieldNarrativeFallbackUsed, sessionsummary.FieldCostDataUnavailable:
			values[i] = new(sql.NullBool)
		case sessionsummary.FieldEstimatedCostUsd:
			values[i] = new(sql.NullFloat64)
		case sessionsummary.FieldDiffFilesChanged, sessionsummary.FieldDiffAdded, sessionsummary.FieldDiffRemoved, sessionsummary.FieldDecisionsAutoApproved, sessionsummary.FieldDecisionsManuallyApproved, sessionsummary.FieldDecisionsDenied, sessionsummary.FieldDecisionsReviewQueueResolved, sessionsummary.FieldDecisionsStillOpen, sessionsummary.FieldDurationMs, sessionsummary.FieldTotalTokens:
			values[i] = new(sql.NullInt64)
		case sessionsummary.FieldID, sessionsummary.FieldSessionID, sessionsummary.FieldSessionTitle, sessionsummary.FieldStatus, sessionsummary.FieldNarrative, sessionsummary.FieldMarkdown, sessionsummary.FieldErrorMessage, sessionsummary.FieldErrorStage:
			values[i] = new(sql.NullString)
		case sessionsummary.FieldSessionStartedAt, sessionsummary.FieldSessionStoppedAt, sessionsummary.FieldGenerationStartedAt, sessionsummary.FieldGeneratedAt, sessionsummary.FieldCreatedAt, sessionsummary.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SessionSummary fields.
func (_m *SessionSummary) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sessionsummary.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case sessionsummary.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case sessionsummary.FieldSessionTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_title", values[i])
			} else if value.Valid {
				_m.SessionTitle = value.String
			}
		case sessionsummary.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case sessionsummary.FieldNarrative:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field narrative", values[i])
			} else if value.Valid {
				_m.Narrative = value.String
			}
		case sessionsummary.FieldNarrativeFallbackUsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field narrative_fallback_used", values[i])
			} else if value.Valid {
				_m.NarrativeFallbackUsed = value.Bool
			}
		case sessionsummary.FieldDiffFilesChanged:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field diff_files_changed", values[i])
			} else if value.Valid {
				_m.DiffFilesChanged = int(value.Int64)
			}
		case sessionsummary.FieldDiffAdded:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field diff_added", values[i])
			} else if value.Valid {
				_m.DiffAdded = int(value.Int64)
			}
		case sessionsummary.FieldDiffRemoved:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field diff_removed", values[i])
			} else if value.Valid {
				_m.DiffRemoved = int(value.Int64)
			}
		case sessionsummary.FieldDecisionsAutoApproved:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field decisions_auto_approved", values[i])
			} else if value.Valid {
				_m.DecisionsAutoApproved = int(value.Int64)
			}
		case sessionsummary.FieldDecisionsManuallyApproved:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field decisions_manually_approved", values[i])
			} else if value.Valid {
				_m.DecisionsManuallyApproved = int(value.Int64)
			}
		case sessionsummary.FieldDecisionsDenied:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field decisions_denied", values[i])
			} else if value.Valid {
				_m.DecisionsDenied = int(value.Int64)
			}
		case sessionsummary.FieldDecisionsReviewQueueResolved:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field decisions_review_queue_resolved", values[i])
			} else if value.Valid {
				_m.DecisionsReviewQueueResolved = int(value.Int64)
			}
		case sessionsummary.FieldDecisionsStillOpen:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field decisions_still_open", values[i])
			} else if value.Valid {
				_m.DecisionsStillOpen = int(value.Int64)
			}
		case sessionsummary.FieldSessionStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field session_started_at", values[i])
			} else if value.Valid {
				_m.SessionStartedAt = new(time.Time)
				*_m.SessionStartedAt = value.Time
			}
		case sessionsummary.FieldSessionStoppedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field session_stopped_at", values[i])
			} else if value.Valid {
				_m.SessionStoppedAt = new(time.Time)
				*_m.SessionStoppedAt = value.Time
			}
		case sessionsummary.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int64)
				*_m.DurationMs = value.Int64
			}
		case sessionsummary.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = new(int64)
				*_m.TotalTokens = value.Int64
			}
		case sessionsummary.FieldEstimatedCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_cost_usd", values[i])
			} else if value.Valid {
				_m.EstimatedCostUsd = new(float64)
				*_m.EstimatedCostUsd = value.Float64
			}
		case sessionsummary.FieldCostDataUnavailable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field cost_data_unavailable", values[i])
			} else if value.Valid {
				_m.CostDataUnavailable = value.Bool
			}
		case sessionsummary.FieldMarkdown:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field markdown", values[i])
			} else if value.Valid {
				_m.Markdown = value.String
			}
		case sessionsummary.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case sessionsummary.FieldErrorStage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_stage", values[i])
			} else if value.Valid {
				_m.ErrorStage = value.String
			}
		case sessionsummary.FieldGenerationStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field generation_started_at", values[i])
			} else if value.Valid {
				_m.GenerationStartedAt = new(time.Time)
				*_m.GenerationStartedAt = value.Time
			}
		case sessionsummary.FieldGeneratedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field generated_at", values[i])
			} else if value.Valid {
				_m.GeneratedAt = new(time.Time)
				*_m.GeneratedAt = value.Time
			}
		case sessionsummary.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sessionsummary.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SessionSummary.
// This includes values selected through modifiers, order, etc.
func (_m *SessionSummary) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SessionSummary.
// Note that you need to call SessionSummary.Unwrap() before calling this method if this SessionSummary
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SessionSummary) Update() *SessionSummaryUpdateOne {
	return NewSessionSummaryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SessionSummary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SessionSummary) Unwrap() *SessionSummary {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SessionSummary is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SessionSummary) String() string {
	var builder strings.Builder
	builder.WriteString("SessionSummary(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("session_title=")
	builder.WriteString(_m.SessionTitle)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("narrative=")
	builder.WriteString(_m.Narrative)
	builder.WriteString(", ")
	builder.WriteString("narrative_fallback_used=")
	builder.WriteString(fmt.Sprintf("%v", _m.NarrativeFallbackUsed))
	builder.WriteString(", ")
	builder.WriteString("diff_files_changed=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiffFilesChanged))
	builder.WriteString(", ")
	builder.WriteString("diff_added=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiffAdded))
	builder.WriteString(", ")
	builder.WriteString("diff_removed=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiffRemoved))
	builder.WriteString(", ")
	builder.WriteString("decisions_auto_approved=")
	builder.WriteString(fmt.Sprintf("%v", _m.DecisionsAutoApproved))
	builder.WriteString(", ")
	builder.WriteString("decisions_manually_approved=")
	builder.WriteString(fmt.Sprintf("%v", _m.DecisionsManuallyApproved))
	builder.WriteString(", ")
	builder.WriteString("decisions_denied=")
	builder.WriteString(fmt.Sprintf("%v", _m.DecisionsDenied))
	builder.WriteString(", ")
	builder.WriteString("decisions_review_queue_resolved=")
	builder.WriteString(fmt.Sprintf("%v", _m.DecisionsReviewQueueResolved))
	builder.WriteString(", ")
	builder.WriteString("decisions_still_open=")
	builder.WriteString(fmt.Sprintf("%v", _m.DecisionsStillOpen))
	builder.WriteString(", ")
	if v := _m.SessionStartedAt; v != nil {
		builder.WriteString("session_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SessionStoppedAt; v != nil {
		builder.WriteString("session_stopped_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TotalTokens; v != nil {
		builder.WriteString("total_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.EstimatedCostUsd; v != nil {
		builder.WriteString("estimated_cost_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("cost_data_unavailable=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostDataUnavailable))
	builder.WriteString(", ")
	builder.WriteString("markdown=")
	builder.WriteString(_m.Markdown)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("error_stage=")
	builder.WriteString(_m.ErrorStage)
	builder.WriteString(", ")
	if v := _m.GenerationStartedAt; v != nil {
		builder.WriteString("generation_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.GeneratedAt; v != nil {
		builder.WriteString("generated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SessionSummaries is a parsable slice of SessionSummary.
type SessionSummaries []*SessionSummary
