// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
	"github.com/tstapler/stapler-squad/session/ent/sessionsummary"
)

// SessionSummaryQuery is the builder for querying SessionSummary entities.
type SessionSummaryQuery struct {
	config
	ctx        *QueryContext
	order      []sessionsummary.OrderOption
	inters     []Interceptor
	predicates []predicate.SessionSummary
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SessionSummaryQuery builder.
func (_q *SessionSummaryQuery) Where(ps ...predicate.SessionSummary) *SessionSummaryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SessionSummaryQuery) Limit(limit int) *SessionSummaryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SessionSummaryQuery) Offset(offset int) *SessionSummaryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SessionSummaryQuery) Unique(unique bool) *SessionSummaryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SessionSummaryQuery) Order(o ...sessionsummary.OrderOption) *SessionSummaryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first SessionSummary entity from the query.
// Returns a *NotFoundError when no SessionSummary was found.
func (_q *SessionSummaryQuery) First(ctx context.Context) (*SessionSummary, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sessionsummary.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SessionSummaryQuery) FirstX(ctx context.Context) *SessionSummary {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SessionSummary ID from the query.
// Returns a *NotFoundError when no SessionSummary ID was found.
func (_q *SessionSummaryQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sessionsummary.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SessionSummaryQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SessionSummary entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SessionSummary entity is found.
// Returns a *NotFoundError when no SessionSummary entities are found.
func (_q *SessionSummaryQuery) Only(ctx context.Context) (*SessionSummary, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sessionsummary.Label}
	default:
		return nil, &NotSingularError{sessionsummary.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SessionSummaryQuery) OnlyX(ctx context.Context) *SessionSummary {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SessionSummary ID in the query.
// Returns a *NotSingularError when more than one SessionSummary ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SessionSummaryQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sessionsummary.Label}
	default:
		err = &NotSingularError{sessionsummary.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SessionSummaryQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SessionSummaries.
func (_q *SessionSummaryQuery) All(ctx context.Context) ([]*SessionSummary, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SessionSummary, *SessionSummaryQuery]()
	return withInterceptors[[]*SessionSummary](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SessionSummaryQuery) AllX(ctx context.Context) []*SessionSummary {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SessionSummary IDs.
func (_q *SessionSummaryQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(sessionsummary.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SessionSummaryQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SessionSummaryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SessionSummaryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SessionSummaryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SessionSummaryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SessionSummaryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SessionSummaryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SessionSummaryQuery) Clone() *SessionSummaryQuery {
	if _q == nil {
		return nil
	}
	return &SessionSummaryQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]sessionsummary.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.SessionSummary{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SessionID string `json:"session_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SessionSummary.Query().
//		GroupBy(sessionsummary.FieldSessionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SessionSummaryQuery) GroupBy(field string, fields ...string) *SessionSummaryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SessionSummaryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = sessionsummary.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SessionID string `json:"session_id,omitempty"`
//	}
//
//	client.SessionSummary.Query().
//		Select(sessionsummary.FieldSessionID).
//		Scan(ctx, &v)
func (_q *SessionSummaryQuery) Select(fields ...string) *SessionSummarySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SessionSummarySelect{SessionSummaryQuery: _q}
	sbuild.label = sessionsummary.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SessionSummarySelect configured with the given aggregations.
func (_q *SessionSummaryQuery) Aggregate(fns ...AggregateFunc) *SessionSummarySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SessionSummaryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !sessionsummary.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SessionSummaryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SessionSummary, error) {
	var (
		nodes = []*SessionSummary{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SessionSummary).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SessionSummary{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *SessionSummaryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SessionSummaryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sessionsummary.Table, sessionsummary.Columns, sqlgraph.NewFieldSpec(sessionsummary.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sessionsummary.FieldID)
		for i := range fields {
			if fields[i] != sessionsummary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SessionSummaryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(sessionsummary.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = sessionsummary.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SessionSummaryGroupBy is the group-by builder for SessionSummary entities.
type SessionSummaryGroupBy struct {
	selector
	build *SessionSummaryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SessionSummaryGroupBy) Aggregate(fns ...AggregateFunc) *SessionSummaryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SessionSummaryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SessionSummaryQuery, *SessionSummaryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SessionSummaryGroupBy) sqlScan(ctx context.Context, root *SessionSummaryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SessionSummarySelect is the builder for selecting fields of SessionSummary entities.
type SessionSummarySelect struct {
	*SessionSummaryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SessionSummarySelect) Aggregate(fns ...AggregateFunc) *SessionSummarySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SessionSummarySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SessionSummaryQuery, *SessionSummarySelect](ctx, _s.SessionSummaryQuery, _s, _s.inters, v)
}

func (_s *SessionSummarySelect) sqlScan(ctx context.Context, root *SessionSummaryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
