// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tstapler/stapler-squad/session/ent/session"
	"github.com/tstapler/stapler-squad/session/ent/shell"
)

// ShellCreate is the builder for creating a Shell entity.
type ShellCreate struct {
	config
	mutation *ShellMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *ShellCreate) SetName(v string) *ShellCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCommand sets the "command" field.
func (_c *ShellCreate) SetCommand(v string) *ShellCreate {
	_c.mutation.SetCommand(v)
	return _c
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_c *ShellCreate) SetNillableCommand(v *string) *ShellCreate {
	if v != nil {
		_c.SetCommand(*v)
	}
	return _c
}

// SetWorkingDir sets the "working_dir" field.
func (_c *ShellCreate) SetWorkingDir(v string) *ShellCreate {
	_c.mutation.SetWorkingDir(v)
	return _c
}

// SetNillableWorkingDir sets the "working_dir" field if the given value is not nil.
func (_c *ShellCreate) SetNillableWorkingDir(v *string) *ShellCreate {
	if v != nil {
		_c.SetWorkingDir(*v)
	}
	return _c
}

// SetTmuxSessionName sets the "tmux_session_name" field.
func (_c *ShellCreate) SetTmuxSessionName(v string) *ShellCreate {
	_c.mutation.SetTmuxSessionName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ShellCreate) SetStatus(v string) *ShellCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ShellCreate) SetNillableStatus(v *string) *ShellCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExitCode sets the "exit_code" field.
func (_c *ShellCreate) SetExitCode(v int) *ShellCreate {
	_c.mutation.SetExitCode(v)
	return _c
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (_c *ShellCreate) SetNillableExitCode(v *int) *ShellCreate {
	if v != nil {
		_c.SetExitCode(*v)
	}
	return _c
}

// SetOrderIndex sets the "order_index" field.
func (_c *ShellCreate) SetOrderIndex(v int) *ShellCreate {
	_c.mutation.SetOrderIndex(v)
	return _c
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_c *ShellCreate) SetNillableOrderIndex(v *int) *ShellCreate {
	if v != nil {
		_c.SetOrderIndex(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ShellCreate) SetStartedAt(v time.Time) *ShellCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ShellCreate) SetNillableStartedAt(v *time.Time) *ShellCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetStoppedAt sets the "stopped_at" field.
func (_c *ShellCreate) SetStoppedAt(v time.Time) *ShellCreate {
	_c.mutation.SetStoppedAt(v)
	return _c
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_c *ShellCreate) SetNillableStoppedAt(v *time.Time) *ShellCreate {
	if v != nil {
		_c.SetStoppedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ShellCreate) SetID(v string) *ShellCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSessionID sets the "session" edge to the Session entity by ID.
func (_c *ShellCreate) SetSessionID(id int) *ShellCreate {
	_c.mutation.SetSessionID(id)
	return _c
}

// SetSession sets the "session" edge to the Session entity.
func (_c *ShellCreate) SetSession(v *Session) *ShellCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the ShellMutation object of the builder.
func (_c *ShellCreate) Mutation() *ShellMutation {
	return _c.mutation
}

// Save creates the Shell in the database.
func (_c *ShellCreate) Save(ctx context.Context) (*Shell, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShellCreate) SaveX(ctx context.Context) *Shell {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShellCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShellCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShellCreate) defaults() {
	if _, ok := _c.mutation.Command(); !ok {
		v := shell.DefaultCommand
		_c.mutation.SetCommand(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := shell.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.OrderIndex(); !ok {
		v := shell.DefaultOrderIndex
		_c.mutation.SetOrderIndex(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := shell.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShellCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Shell.name"`)}
	}
	if _, ok := _c.mutation.Command(); !ok {
		return &ValidationError{Name: "command", err: errors.New(`ent: missing required field "Shell.command"`)}
	}
	if _, ok := _c.mutation.TmuxSessionName(); !ok {
		return &ValidationError{Name: "tmux_session_name", err: errors.New(`ent: missing required field "Shell.tmux_session_name"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Shell.status"`)}
	}
	if _, ok := _c.mutation.OrderIndex(); !ok {
		return &ValidationError{Name: "order_index", err: errors.New(`ent: missing required field "Shell.order_index"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "Shell.started_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "Shell.session"`)}
	}
	return nil
}

func (_c *ShellCreate) sqlSave(ctx context.Context) (*Shell, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Shell.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShellCreate) createSpec() (*Shell, *sqlgraph.CreateSpec) {
	var (
		_node = &Shell{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shell.Table, sqlgraph.NewFieldSpec(shell.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(shell.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Command(); ok {
		_spec.SetField(shell.FieldCommand, field.TypeString, value)
		_node.Command = value
	}
	if value, ok := _c.mutation.WorkingDir(); ok {
		_spec.SetField(shell.FieldWorkingDir, field.TypeString, value)
		_node.WorkingDir = value
	}
	if value, ok := _c.mutation.TmuxSessionName(); ok {
		_spec.SetField(shell.FieldTmuxSessionName, field.TypeString, value)
		_node.TmuxSessionName = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(shell.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExitCode(); ok {
		_spec.SetField(shell.FieldExitCode, field.TypeInt, value)
		_node.ExitCode = &value
	}
	if value, ok := _c.mutation.OrderIndex(); ok {
		_spec.SetField(shell.FieldOrderIndex, field.TypeInt, value)
		_node.OrderIndex = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(shell.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.StoppedAt(); ok {
		_spec.SetField(shell.FieldStoppedAt, field.TypeTime, value)
		_node.StoppedAt = &value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shell.SessionTable,
			Columns: []string{shell.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.session_shells = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Shell.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShellUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ShellCreate) OnConflict(opts ...sql.ConflictOption) *ShellUpsertOne {
	_c.conflict = opts
	return &ShellUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Shell.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShellCreate) OnConflictColumns(columns ...string) *ShellUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShellUpsertOne{
		create: _c,
	}
}

type (
	// ShellUpsertOne is the builder for "upsert"-ing
	//  one Shell node.
	ShellUpsertOne struct {
		create *ShellCreate
	}

	// ShellUpsert is the "OnConflict" setter.
	ShellUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ShellUpsert) SetName(v string) *ShellUpsert {
	u.Set(shell.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShellUpsert) UpdateName() *ShellUpsert {
	u.SetExcluded(shell.FieldName)
	return u
}

// SetCommand sets the "command" field.
func (u *ShellUpsert) SetCommand(v string) *ShellUpsert {
	u.Set(shell.FieldCommand, v)
	return u
}

// UpdateCommand sets the "command" field to the value that was provided on create.
func (u *ShellUpsert) UpdateCommand() *ShellUpsert {
	u.SetExcluded(shell.FieldCommand)
	return u
}

// SetWorkingDir sets the "working_dir" field.
func (u *ShellUpsert) SetWorkingDir(v string) *ShellUpsert {
	u.Set(shell.FieldWorkingDir, v)
	return u
}

// UpdateWorkingDir sets the "working_dir" field to the value that was provided on create.
func (u *ShellUpsert) UpdateWorkingDir() *ShellUpsert {
	u.SetExcluded(shell.FieldWorkingDir)
	return u
}

// ClearWorkingDir clears the value of the "working_dir" field.
func (u *ShellUpsert) ClearWorkingDir() *ShellUpsert {
	u.SetNull(shell.FieldWorkingDir)
	return u
}

// SetTmuxSessionName sets the "tmux_session_name" field.
func (u *ShellUpsert) SetTmuxSessionName(v string) *ShellUpsert {
	u.Set(shell.FieldTmuxSessionName, v)
	return u
}

// UpdateTmuxSessionName sets the "tmux_session_name" field to the value that was provided on create.
func (u *ShellUpsert) UpdateTmuxSessionName() *ShellUpsert {
	u.SetExcluded(shell.FieldTmuxSessionName)
	return u
}

// SetStatus sets the "status" field.
func (u *ShellUpsert) SetStatus(v string) *ShellUpsert {
	u.Set(shell.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ShellUpsert) UpdateStatus() *ShellUpsert {
	u.SetExcluded(shell.FieldStatus)
	return u
}

// SetExitCode sets the "exit_code" field.
func (u *ShellUpsert) SetExitCode(v int) *ShellUpsert {
	u.Set(shell.FieldExitCode, v)
	return u
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *ShellUpsert) UpdateExitCode() *ShellUpsert {
	u.SetExcluded(shell.FieldExitCode)
	return u
}

// AddExitCode adds v to the "exit_code" field.
func (u *ShellUpsert) AddExitCode(v int) *ShellUpsert {
	u.Add(shell.FieldExitCode, v)
	return u
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *ShellUpsert) ClearExitCode() *ShellUpsert {
	u.SetNull(shell.FieldExitCode)
	return u
}

// SetOrderIndex sets the "order_index" field.
func (u *ShellUpsert) SetOrderIndex(v int) *ShellUpsert {
	u.Set(shell.FieldOrderIndex, v)
	return u
}

// UpdateOrderIndex sets the "order_index" field to the value that was provided on create.
func (u *ShellUpsert) UpdateOrderIndex() *ShellUpsert {
	u.SetExcluded(shell.FieldOrderIndex)
	return u
}

// AddOrderIndex adds v to the "order_index" field.
func (u *ShellUpsert) AddOrderIndex(v int) *ShellUpsert {
	u.Add(shell.FieldOrderIndex, v)
	return u
}

// SetStoppedAt sets the "stopped_at" field.
func (u *ShellUpsert) SetStoppedAt(v time.Time) *ShellUpsert {
	u.Set(shell.FieldStoppedAt, v)
	return u
}

// UpdateStoppedAt sets the "stopped_at" field to the value that was provided on create.
func (u *ShellUpsert) UpdateStoppedAt() *ShellUpsert {
	u.SetExcluded(shell.FieldStoppedAt)
	return u
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (u *ShellUpsert) ClearStoppedAt() *ShellUpsert {
	u.SetNull(shell.FieldStoppedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Shell.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(shell.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ShellUpsertOne) UpdateNewValues() *ShellUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(shell.FieldID)
		}
		if _, exists := u.create.mutation.StartedAt(); exists {
			s.SetIgnore(shell.FieldStartedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Shell.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShellUpsertOne) Ignore() *ShellUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShellUpsertOne) DoNothing() *ShellUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShellCreate.OnConflict
// documentation for more info.
func (u *ShellUpsertOne) Update(set func(*ShellUpsert)) *ShellUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShellUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ShellUpsertOne) SetName(v string) *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShellUpsertOne) UpdateName() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateName()
	})
}

// SetCommand sets the "command" field.
func (u *ShellUpsertOne) SetCommand(v string) *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.SetCommand(v)
	})
}

// UpdateCommand sets the "command" field to the value that was provided on create.
func (u *ShellUpsertOne) UpdateCommand() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateCommand()
	})
}

// SetWorkingDir sets the "working_dir" field.
func (u *ShellUpsertOne) SetWorkingDir(v string) *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.SetWorkingDir(v)
	})
}

// UpdateWorkingDir sets the "working_dir" field to the value that was provided on create.
func (u *ShellUpsertOne) UpdateWorkingDir() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateWorkingDir()
	})
}

// ClearWorkingDir clears the value of the "working_dir" field.
func (u *ShellUpsertOne) ClearWorkingDir() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.ClearWorkingDir()
	})
}

// SetTmuxSessionName sets the "tmux_session_name" field.
func (u *ShellUpsertOne) SetTmuxSessionName(v string) *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.SetTmuxSessionName(v)
	})
}

// UpdateTmuxSessionName sets the "tmux_session_name" field to the value that was provided on create.
func (u *ShellUpsertOne) UpdateTmuxSessionName() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateTmuxSessionName()
	})
}

// SetStatus sets the "status" field.
func (u *ShellUpsertOne) SetStatus(v string) *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ShellUpsertOne) UpdateStatus() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateStatus()
	})
}

// SetExitCode sets the "exit_code" field.
func (u *ShellUpsertOne) SetExitCode(v int) *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.SetExitCode(v)
	})
}

// AddExitCode adds v to the "exit_code" field.
func (u *ShellUpsertOne) AddExitCode(v int) *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.AddExitCode(v)
	})
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *ShellUpsertOne) UpdateExitCode() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateExitCode()
	})
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *ShellUpsertOne) ClearExitCode() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.ClearExitCode()
	})
}

// SetOrderIndex sets the "order_index" field.
func (u *ShellUpsertOne) SetOrderIndex(v int) *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.SetOrderIndex(v)
	})
}

// AddOrderIndex adds v to the "order_index" field.
func (u *ShellUpsertOne) AddOrderIndex(v int) *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.AddOrderIndex(v)
	})
}

// UpdateOrderIndex sets the "order_index" field to the value that was provided on create.
func (u *ShellUpsertOne) UpdateOrderIndex() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateOrderIndex()
	})
}

// SetStoppedAt sets the "stopped_at" field.
func (u *ShellUpsertOne) SetStoppedAt(v time.Time) *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.SetStoppedAt(v)
	})
}

// UpdateStoppedAt sets the "stopped_at" field to the value that was provided on create.
func (u *ShellUpsertOne) UpdateStoppedAt() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateStoppedAt()
	})
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (u *ShellUpsertOne) ClearStoppedAt() *ShellUpsertOne {
	return u.Update(func(s *ShellUpsert) {
		s.ClearStoppedAt()
	})
}

// Exec executes the query.
func (u *ShellUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShellCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShellUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShellUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ShellUpsertOne.ID is not supported by MySQL driver. Use ShellUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShellUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShellCreateBulk is the builder for creating many Shell entities in bulk.
type ShellCreateBulk struct {
	config
	err      error
	builders []*ShellCreate
	conflict []sql.ConflictOption
}

// Save creates the Shell entities in the database.
func (_c *ShellCreateBulk) Save(ctx context.Context) ([]*Shell, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Shell, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShellMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShellCreateBulk) SaveX(ctx context.Context) []*Shell {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShellCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShellCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Shell.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShellUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ShellCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShellUpsertBulk {
	_c.conflict = opts
	return &ShellUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Shell.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShellCreateBulk) OnConflictColumns(columns ...string) *ShellUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShellUpsertBulk{
		create: _c,
	}
}

// ShellUpsertBulk is the builder for "upsert"-ing
// a bulk of Shell nodes.
type ShellUpsertBulk struct {
	create *ShellCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Shell.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(shell.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ShellUpsertBulk) UpdateNewValues() *ShellUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(shell.FieldID)
			}
			if _, exists := b.mutation.StartedAt(); exists {
				s.SetIgnore(shell.FieldStartedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Shell.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShellUpsertBulk) Ignore() *ShellUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShellUpsertBulk) DoNothing() *ShellUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShellCreateBulk.OnConflict
// documentation for more info.
func (u *ShellUpsertBulk) Update(set func(*ShellUpsert)) *ShellUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShellUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ShellUpsertBulk) SetName(v string) *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShellUpsertBulk) UpdateName() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateName()
	})
}

// SetCommand sets the "command" field.
func (u *ShellUpsertBulk) SetCommand(v string) *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.SetCommand(v)
	})
}

// UpdateCommand sets the "command" field to the value that was provided on create.
func (u *ShellUpsertBulk) UpdateCommand() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateCommand()
	})
}

// SetWorkingDir sets the "working_dir" field.
func (u *ShellUpsertBulk) SetWorkingDir(v string) *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.SetWorkingDir(v)
	})
}

// UpdateWorkingDir sets the "working_dir" field to the value that was provided on create.
func (u *ShellUpsertBulk) UpdateWorkingDir() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateWorkingDir()
	})
}

// ClearWorkingDir clears the value of the "working_dir" field.
func (u *ShellUpsertBulk) ClearWorkingDir() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.ClearWorkingDir()
	})
}

// SetTmuxSessionName sets the "tmux_session_name" field.
func (u *ShellUpsertBulk) SetTmuxSessionName(v string) *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.SetTmuxSessionName(v)
	})
}

// UpdateTmuxSessionName sets the "tmux_session_name" field to the value that was provided on create.
func (u *ShellUpsertBulk) UpdateTmuxSessionName() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateTmuxSessionName()
	})
}

// SetStatus sets the "status" field.
func (u *ShellUpsertBulk) SetStatus(v string) *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ShellUpsertBulk) UpdateStatus() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateStatus()
	})
}

// SetExitCode sets the "exit_code" field.
func (u *ShellUpsertBulk) SetExitCode(v int) *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.SetExitCode(v)
	})
}

// AddExitCode adds v to the "exit_code" field.
func (u *ShellUpsertBulk) AddExitCode(v int) *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.AddExitCode(v)
	})
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *ShellUpsertBulk) UpdateExitCode() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateExitCode()
	})
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *ShellUpsertBulk) ClearExitCode() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.ClearExitCode()
	})
}

// SetOrderIndex sets the "order_index" field.
func (u *ShellUpsertBulk) SetOrderIndex(v int) *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.SetOrderIndex(v)
	})
}

// AddOrderIndex adds v to the "order_index" field.
func (u *ShellUpsertBulk) AddOrderIndex(v int) *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.AddOrderIndex(v)
	})
}

// UpdateOrderIndex sets the "order_index" field to the value that was provided on create.
func (u *ShellUpsertBulk) UpdateOrderIndex() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateOrderIndex()
	})
}

// SetStoppedAt sets the "stopped_at" field.
func (u *ShellUpsertBulk) SetStoppedAt(v time.Time) *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.SetStoppedAt(v)
	})
}

// UpdateStoppedAt sets the "stopped_at" field to the value that was provided on create.
func (u *ShellUpsertBulk) UpdateStoppedAt() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.UpdateStoppedAt()
	})
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (u *ShellUpsertBulk) ClearStoppedAt() *ShellUpsertBulk {
	return u.Update(func(s *ShellUpsert) {
		s.ClearStoppedAt()
	})
}

// Exec executes the query.
func (u *ShellUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShellCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShellCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShellUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
