// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
	"github.com/tstapler/stapler-squad/session/ent/workflow"
)

// WorkflowUpdate is the builder for updating Workflow entities.
type WorkflowUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowMutation
}

// Where appends a list predicates to the WorkflowUpdate builder.
func (_u *WorkflowUpdate) Where(ps ...predicate.Workflow) *WorkflowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *WorkflowUpdate) SetSlug(v string) *WorkflowUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableSlug(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WorkflowUpdate) SetName(v string) *WorkflowUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableName(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WorkflowUpdate) SetDescription(v string) *WorkflowUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableDescription(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *WorkflowUpdate) ClearDescription() *WorkflowUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCommand sets the "command" field.
func (_u *WorkflowUpdate) SetCommand(v string) *WorkflowUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableCommand(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// SetTargetDirectory sets the "target_directory" field.
func (_u *WorkflowUpdate) SetTargetDirectory(v string) *WorkflowUpdate {
	_u.mutation.SetTargetDirectory(v)
	return _u
}

// SetNillableTargetDirectory sets the "target_directory" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableTargetDirectory(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetTargetDirectory(*v)
	}
	return _u
}

// ClearTargetDirectory clears the value of the "target_directory" field.
func (_u *WorkflowUpdate) ClearTargetDirectory() *WorkflowUpdate {
	_u.mutation.ClearTargetDirectory()
	return _u
}

// SetInputTemplate sets the "input_template" field.
func (_u *WorkflowUpdate) SetInputTemplate(v string) *WorkflowUpdate {
	_u.mutation.SetInputTemplate(v)
	return _u
}

// SetNillableInputTemplate sets the "input_template" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableInputTemplate(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetInputTemplate(*v)
	}
	return _u
}

// ClearInputTemplate clears the value of the "input_template" field.
func (_u *WorkflowUpdate) ClearInputTemplate() *WorkflowUpdate {
	_u.mutation.ClearInputTemplate()
	return _u
}

// SetSessionType sets the "session_type" field.
func (_u *WorkflowUpdate) SetSessionType(v string) *WorkflowUpdate {
	_u.mutation.SetSessionType(v)
	return _u
}

// SetNillableSessionType sets the "session_type" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableSessionType(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetSessionType(*v)
	}
	return _u
}

// ClearSessionType clears the value of the "session_type" field.
func (_u *WorkflowUpdate) ClearSessionType() *WorkflowUpdate {
	_u.mutation.ClearSessionType()
	return _u
}

// SetModel sets the "model" field.
func (_u *WorkflowUpdate) SetModel(v string) *WorkflowUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableModel(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *WorkflowUpdate) ClearModel() *WorkflowUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetAgentType sets the "agent_type" field.
func (_u *WorkflowUpdate) SetAgentType(v string) *WorkflowUpdate {
	_u.mutation.SetAgentType(v)
	return _u
}

// SetNillableAgentType sets the "agent_type" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableAgentType(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetAgentType(*v)
	}
	return _u
}

// ClearAgentType clears the value of the "agent_type" field.
func (_u *WorkflowUpdate) ClearAgentType() *WorkflowUpdate {
	_u.mutation.ClearAgentType()
	return _u
}

// SetCronExpression sets the "cron_expression" field.
func (_u *WorkflowUpdate) SetCronExpression(v string) *WorkflowUpdate {
	_u.mutation.SetCronExpression(v)
	return _u
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableCronExpression(v *string) *WorkflowUpdate {
	if v != nil {
		_u.SetCronExpression(*v)
	}
	return _u
}

// ClearCronExpression clears the value of the "cron_expression" field.
func (_u *WorkflowUpdate) ClearCronExpression() *WorkflowUpdate {
	_u.mutation.ClearCronExpression()
	return _u
}

// SetCronEnabled sets the "cron_enabled" field.
func (_u *WorkflowUpdate) SetCronEnabled(v bool) *WorkflowUpdate {
	_u.mutation.SetCronEnabled(v)
	return _u
}

// SetNillableCronEnabled sets the "cron_enabled" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableCronEnabled(v *bool) *WorkflowUpdate {
	if v != nil {
		_u.SetCronEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkflowUpdate) SetUpdatedAt(v time.Time) *WorkflowUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKeepSessions sets the "keep_sessions" field.
func (_u *WorkflowUpdate) SetKeepSessions(v int) *WorkflowUpdate {
	_u.mutation.ResetKeepSessions()
	_u.mutation.SetKeepSessions(v)
	return _u
}

// SetNillableKeepSessions sets the "keep_sessions" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableKeepSessions(v *int) *WorkflowUpdate {
	if v != nil {
		_u.SetKeepSessions(*v)
	}
	return _u
}

// AddKeepSessions adds value to the "keep_sessions" field.
func (_u *WorkflowUpdate) AddKeepSessions(v int) *WorkflowUpdate {
	_u.mutation.AddKeepSessions(v)
	return _u
}

// ClearKeepSessions clears the value of the "keep_sessions" field.
func (_u *WorkflowUpdate) ClearKeepSessions() *WorkflowUpdate {
	_u.mutation.ClearKeepSessions()
	return _u
}

// SetArchiveAfterHours sets the "archive_after_hours" field.
func (_u *WorkflowUpdate) SetArchiveAfterHours(v int) *WorkflowUpdate {
	_u.mutation.ResetArchiveAfterHours()
	_u.mutation.SetArchiveAfterHours(v)
	return _u
}

// SetNillableArchiveAfterHours sets the "archive_after_hours" field if the given value is not nil.
func (_u *WorkflowUpdate) SetNillableArchiveAfterHours(v *int) *WorkflowUpdate {
	if v != nil {
		_u.SetArchiveAfterHours(*v)
	}
	return _u
}

// AddArchiveAfterHours adds value to the "archive_after_hours" field.
func (_u *WorkflowUpdate) AddArchiveAfterHours(v int) *WorkflowUpdate {
	_u.mutation.AddArchiveAfterHours(v)
	return _u
}

// ClearArchiveAfterHours clears the value of the "archive_after_hours" field.
func (_u *WorkflowUpdate) ClearArchiveAfterHours() *WorkflowUpdate {
	_u.mutation.ClearArchiveAfterHours()
	return _u
}

// Mutation returns the WorkflowMutation object of the builder.
func (_u *WorkflowUpdate) Mutation() *WorkflowMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkflowUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workflow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := workflow.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Workflow.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := workflow.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workflow.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Command(); ok {
		if err := workflow.CommandValidator(v); err != nil {
			return &ValidationError{Name: "command", err: fmt.Errorf(`ent: validator failed for field "Workflow.command": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(workflow.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workflow.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(workflow.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(workflow.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(workflow.FieldCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetDirectory(); ok {
		_spec.SetField(workflow.FieldTargetDirectory, field.TypeString, value)
	}
	if _u.mutation.TargetDirectoryCleared() {
		_spec.ClearField(workflow.FieldTargetDirectory, field.TypeString)
	}
	if value, ok := _u.mutation.InputTemplate(); ok {
		_spec.SetField(workflow.FieldInputTemplate, field.TypeString, value)
	}
	if _u.mutation.InputTemplateCleared() {
		_spec.ClearField(workflow.FieldInputTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.SessionType(); ok {
		_spec.SetField(workflow.FieldSessionType, field.TypeString, value)
	}
	if _u.mutation.SessionTypeCleared() {
		_spec.ClearField(workflow.FieldSessionType, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(workflow.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(workflow.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.AgentType(); ok {
		_spec.SetField(workflow.FieldAgentType, field.TypeString, value)
	}
	if _u.mutation.AgentTypeCleared() {
		_spec.ClearField(workflow.FieldAgentType, field.TypeString)
	}
	if value, ok := _u.mutation.CronExpression(); ok {
		_spec.SetField(workflow.FieldCronExpression, field.TypeString, value)
	}
	if _u.mutation.CronExpressionCleared() {
		_spec.ClearField(workflow.FieldCronExpression, field.TypeString)
	}
	if value, ok := _u.mutation.CronEnabled(); ok {
		_spec.SetField(workflow.FieldCronEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workflow.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.KeepSessions(); ok {
		_spec.SetField(workflow.FieldKeepSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKeepSessions(); ok {
		_spec.AddField(workflow.FieldKeepSessions, field.TypeInt, value)
	}
	if _u.mutation.KeepSessionsCleared() {
		_spec.ClearField(workflow.FieldKeepSessions, field.TypeInt)
	}
	if value, ok := _u.mutation.ArchiveAfterHours(); ok {
		_spec.SetField(workflow.FieldArchiveAfterHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedArchiveAfterHours(); ok {
		_spec.AddField(workflow.FieldArchiveAfterHours, field.TypeInt, value)
	}
	if _u.mutation.ArchiveAfterHoursCleared() {
		_spec.ClearField(workflow.FieldArchiveAfterHours, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowUpdateOne is the builder for updating a single Workflow entity.
type WorkflowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowMutation
}

// SetSlug sets the "slug" field.
func (_u *WorkflowUpdateOne) SetSlug(v string) *WorkflowUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableSlug(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WorkflowUpdateOne) SetName(v string) *WorkflowUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableName(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WorkflowUpdateOne) SetDescription(v string) *WorkflowUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableDescription(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *WorkflowUpdateOne) ClearDescription() *WorkflowUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCommand sets the "command" field.
func (_u *WorkflowUpdateOne) SetCommand(v string) *WorkflowUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableCommand(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// SetTargetDirectory sets the "target_directory" field.
func (_u *WorkflowUpdateOne) SetTargetDirectory(v string) *WorkflowUpdateOne {
	_u.mutation.SetTargetDirectory(v)
	return _u
}

// SetNillableTargetDirectory sets the "target_directory" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableTargetDirectory(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetTargetDirectory(*v)
	}
	return _u
}

// ClearTargetDirectory clears the value of the "target_directory" field.
func (_u *WorkflowUpdateOne) ClearTargetDirectory() *WorkflowUpdateOne {
	_u.mutation.ClearTargetDirectory()
	return _u
}

// SetInputTemplate sets the "input_template" field.
func (_u *WorkflowUpdateOne) SetInputTemplate(v string) *WorkflowUpdateOne {
	_u.mutation.SetInputTemplate(v)
	return _u
}

// SetNillableInputTemplate sets the "input_template" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableInputTemplate(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetInputTemplate(*v)
	}
	return _u
}

// ClearInputTemplate clears the value of the "input_template" field.
func (_u *WorkflowUpdateOne) ClearInputTemplate() *WorkflowUpdateOne {
	_u.mutation.ClearInputTemplate()
	return _u
}

// SetSessionType sets the "session_type" field.
func (_u *WorkflowUpdateOne) SetSessionType(v string) *WorkflowUpdateOne {
	_u.mutation.SetSessionType(v)
	return _u
}

// SetNillableSessionType sets the "session_type" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableSessionType(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetSessionType(*v)
	}
	return _u
}

// ClearSessionType clears the value of the "session_type" field.
func (_u *WorkflowUpdateOne) ClearSessionType() *WorkflowUpdateOne {
	_u.mutation.ClearSessionType()
	return _u
}

// SetModel sets the "model" field.
func (_u *WorkflowUpdateOne) SetModel(v string) *WorkflowUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableModel(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *WorkflowUpdateOne) ClearModel() *WorkflowUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetAgentType sets the "agent_type" field.
func (_u *WorkflowUpdateOne) SetAgentType(v string) *WorkflowUpdateOne {
	_u.mutation.SetAgentType(v)
	return _u
}

// SetNillableAgentType sets the "agent_type" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableAgentType(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetAgentType(*v)
	}
	return _u
}

// ClearAgentType clears the value of the "agent_type" field.
func (_u *WorkflowUpdateOne) ClearAgentType() *WorkflowUpdateOne {
	_u.mutation.ClearAgentType()
	return _u
}

// SetCronExpression sets the "cron_expression" field.
func (_u *WorkflowUpdateOne) SetCronExpression(v string) *WorkflowUpdateOne {
	_u.mutation.SetCronExpression(v)
	return _u
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableCronExpression(v *string) *WorkflowUpdateOne {
	if v != nil {
		_u.SetCronExpression(*v)
	}
	return _u
}

// ClearCronExpression clears the value of the "cron_expression" field.
func (_u *WorkflowUpdateOne) ClearCronExpression() *WorkflowUpdateOne {
	_u.mutation.ClearCronExpression()
	return _u
}

// SetCronEnabled sets the "cron_enabled" field.
func (_u *WorkflowUpdateOne) SetCronEnabled(v bool) *WorkflowUpdateOne {
	_u.mutation.SetCronEnabled(v)
	return _u
}

// SetNillableCronEnabled sets the "cron_enabled" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableCronEnabled(v *bool) *WorkflowUpdateOne {
	if v != nil {
		_u.SetCronEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkflowUpdateOne) SetUpdatedAt(v time.Time) *WorkflowUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKeepSessions sets the "keep_sessions" field.
func (_u *WorkflowUpdateOne) SetKeepSessions(v int) *WorkflowUpdateOne {
	_u.mutation.ResetKeepSessions()
	_u.mutation.SetKeepSessions(v)
	return _u
}

// SetNillableKeepSessions sets the "keep_sessions" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableKeepSessions(v *int) *WorkflowUpdateOne {
	if v != nil {
		_u.SetKeepSessions(*v)
	}
	return _u
}

// AddKeepSessions adds value to the "keep_sessions" field.
func (_u *WorkflowUpdateOne) AddKeepSessions(v int) *WorkflowUpdateOne {
	_u.mutation.AddKeepSessions(v)
	return _u
}

// ClearKeepSessions clears the value of the "keep_sessions" field.
func (_u *WorkflowUpdateOne) ClearKeepSessions() *WorkflowUpdateOne {
	_u.mutation.ClearKeepSessions()
	return _u
}

// SetArchiveAfterHours sets the "archive_after_hours" field.
func (_u *WorkflowUpdateOne) SetArchiveAfterHours(v int) *WorkflowUpdateOne {
	_u.mutation.ResetArchiveAfterHours()
	_u.mutation.SetArchiveAfterHours(v)
	return _u
}

// SetNillableArchiveAfterHours sets the "archive_after_hours" field if the given value is not nil.
func (_u *WorkflowUpdateOne) SetNillableArchiveAfterHours(v *int) *WorkflowUpdateOne {
	if v != nil {
		_u.SetArchiveAfterHours(*v)
	}
	return _u
}

// AddArchiveAfterHours adds value to the "archive_after_hours" field.
func (_u *WorkflowUpdateOne) AddArchiveAfterHours(v int) *WorkflowUpdateOne {
	_u.mutation.AddArchiveAfterHours(v)
	return _u
}

// ClearArchiveAfterHours clears the value of the "archive_after_hours" field.
func (_u *WorkflowUpdateOne) ClearArchiveAfterHours() *WorkflowUpdateOne {
	_u.mutation.ClearArchiveAfterHours()
	return _u
}

// Mutation returns the WorkflowMutation object of the builder.
func (_u *WorkflowUpdateOne) Mutation() *WorkflowMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkflowUpdate builder.
func (_u *WorkflowUpdateOne) Where(ps ...predicate.Workflow) *WorkflowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowUpdateOne) Select(field string, fields ...string) *WorkflowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Workflow entity.
func (_u *WorkflowUpdateOne) Save(ctx context.Context) (*Workflow, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowUpdateOne) SaveX(ctx context.Context) *Workflow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkflowUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workflow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := workflow.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Workflow.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := workflow.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workflow.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Command(); ok {
		if err := workflow.CommandValidator(v); err != nil {
			return &ValidationError{Name: "command", err: fmt.Errorf(`ent: validator failed for field "Workflow.command": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowUpdateOne) sqlSave(ctx context.Context) (_node *Workflow, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workflow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflow.FieldID)
		for _, f := range fields {
			if !workflow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(workflow.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workflow.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(workflow.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(workflow.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(workflow.FieldCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetDirectory(); ok {
		_spec.SetField(workflow.FieldTargetDirectory, field.TypeString, value)
	}
	if _u.mutation.TargetDirectoryCleared() {
		_spec.ClearField(workflow.FieldTargetDirectory, field.TypeString)
	}
	if value, ok := _u.mutation.InputTemplate(); ok {
		_spec.SetField(workflow.FieldInputTemplate, field.TypeString, value)
	}
	if _u.mutation.InputTemplateCleared() {
		_spec.ClearField(workflow.FieldInputTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.SessionType(); ok {
		_spec.SetField(workflow.FieldSessionType, field.TypeString, value)
	}
	if _u.mutation.SessionTypeCleared() {
		_spec.ClearField(workflow.FieldSessionType, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(workflow.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(workflow.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.AgentType(); ok {
		_spec.SetField(workflow.FieldAgentType, field.TypeString, value)
	}
	if _u.mutation.AgentTypeCleared() {
		_spec.ClearField(workflow.FieldAgentType, field.TypeString)
	}
	if value, ok := _u.mutation.CronExpression(); ok {
		_spec.SetField(workflow.FieldCronExpression, field.TypeString, value)
	}
	if _u.mutation.CronExpressionCleared() {
		_spec.ClearField(workflow.FieldCronExpression, field.TypeString)
	}
	if value, ok := _u.mutation.CronEnabled(); ok {
		_spec.SetField(workflow.FieldCronEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workflow.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.KeepSessions(); ok {
		_spec.SetField(workflow.FieldKeepSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKeepSessions(); ok {
		_spec.AddField(workflow.FieldKeepSessions, field.TypeInt, value)
	}
	if _u.mutation.KeepSessionsCleared() {
		_spec.ClearField(workflow.FieldKeepSessions, field.TypeInt)
	}
	if value, ok := _u.mutation.ArchiveAfterHours(); ok {
		_spec.SetField(workflow.FieldArchiveAfterHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedArchiveAfterHours(); ok {
		_spec.AddField(workflow.FieldArchiveAfterHours, field.TypeInt, value)
	}
	if _u.mutation.ArchiveAfterHoursCleared() {
		_spec.ClearField(workflow.FieldArchiveAfterHours, field.TypeInt)
	}
	_node = &Workflow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
