// Code generated by ent, DO NOT EDIT.

package ent

import (
	"claude-squad/session/ent/session"
	"claude-squad/session/ent/worktree"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Worktree is the model entity for the Worktree schema.
type Worktree struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RepoPath holds the value of the "repo_path" field.
	RepoPath string `json:"repo_path,omitempty"`
	// WorktreePath holds the value of the "worktree_path" field.
	WorktreePath string `json:"worktree_path,omitempty"`
	// SessionName holds the value of the "session_name" field.
	SessionName string `json:"session_name,omitempty"`
	// BranchName holds the value of the "branch_name" field.
	BranchName string `json:"branch_name,omitempty"`
	// BaseCommitSha holds the value of the "base_commit_sha" field.
	BaseCommitSha string `json:"base_commit_sha,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorktreeQuery when eager-loading is set.
	Edges            WorktreeEdges `json:"edges"`
	session_worktree *int
	selectValues     sql.SelectValues
}

// WorktreeEdges holds the relations/edges for other nodes in the graph.
type WorktreeEdges struct {
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorktreeEdges) SessionOrErr() (*Session, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: session.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Worktree) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case worktree.FieldID:
			values[i] = new(sql.NullInt64)
		case worktree.FieldRepoPath, worktree.FieldWorktreePath, worktree.FieldSessionName, worktree.FieldBranchName, worktree.FieldBaseCommitSha:
			values[i] = new(sql.NullString)
		case worktree.ForeignKeys[0]: // session_worktree
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Worktree fields.
func (_m *Worktree) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case worktree.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case worktree.FieldRepoPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_path", values[i])
			} else if value.Valid {
				_m.RepoPath = value.String
			}
		case worktree.FieldWorktreePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field worktree_path", values[i])
			} else if value.Valid {
				_m.WorktreePath = value.String
			}
		case worktree.FieldSessionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_name", values[i])
			} else if value.Valid {
				_m.SessionName = value.String
			}
		case worktree.FieldBranchName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field branch_name", values[i])
			} else if value.Valid {
				_m.BranchName = value.String
			}
		case worktree.FieldBaseCommitSha:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_commit_sha", values[i])
			} else if value.Valid {
				_m.BaseCommitSha = value.String
			}
		case worktree.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field session_worktree", value)
			} else if value.Valid {
				_m.session_worktree = new(int)
				*_m.session_worktree = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Worktree.
// This includes values selected through modifiers, order, etc.
func (_m *Worktree) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the Worktree entity.
func (_m *Worktree) QuerySession() *SessionQuery {
	return NewWorktreeClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this Worktree.
// Note that you need to call Worktree.Unwrap() before calling this method if this Worktree
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Worktree) Update() *WorktreeUpdateOne {
	return NewWorktreeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Worktree entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Worktree) Unwrap() *Worktree {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Worktree is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Worktree) String() string {
	var builder strings.Builder
	builder.WriteString("Worktree(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("repo_path=")
	builder.WriteString(_m.RepoPath)
	builder.WriteString(", ")
	builder.WriteString("worktree_path=")
	builder.WriteString(_m.WorktreePath)
	builder.WriteString(", ")
	builder.WriteString("session_name=")
	builder.WriteString(_m.SessionName)
	builder.WriteString(", ")
	builder.WriteString("branch_name=")
	builder.WriteString(_m.BranchName)
	builder.WriteString(", ")
	builder.WriteString("base_commit_sha=")
	builder.WriteString(_m.BaseCommitSha)
	builder.WriteByte(')')
	return builder.String()
}

// Worktrees is a parsable slice of Worktree.
type Worktrees []*Worktree
