// Code generated by ent, DO NOT EDIT.

package approvalrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldID, id))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldRuleID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldName, v))
}

// ToolName applies equality check predicate on the "tool_name" field. It's identical to ToolNameEQ.
func ToolName(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldToolName, v))
}

// ToolPattern applies equality check predicate on the "tool_pattern" field. It's identical to ToolPatternEQ.
func ToolPattern(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldToolPattern, v))
}

// ToolCategory applies equality check predicate on the "tool_category" field. It's identical to ToolCategoryEQ.
func ToolCategory(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldToolCategory, v))
}

// CommandPattern applies equality check predicate on the "command_pattern" field. It's identical to CommandPatternEQ.
func CommandPattern(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldCommandPattern, v))
}

// FilePattern applies equality check predicate on the "file_pattern" field. It's identical to FilePatternEQ.
func FilePattern(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldFilePattern, v))
}

// Decision applies equality check predicate on the "decision" field. It's identical to DecisionEQ.
func Decision(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldDecision, v))
}

// RiskLevel applies equality check predicate on the "risk_level" field. It's identical to RiskLevelEQ.
func RiskLevel(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldRiskLevel, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldReason, v))
}

// Alternative applies equality check predicate on the "alternative" field. It's identical to AlternativeEQ.
func Alternative(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldAlternative, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldPriority, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldEnabled, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldSource, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// SafePythonImportsOnly applies equality check predicate on the "safe_python_imports_only" field. It's identical to SafePythonImportsOnlyEQ.
func SafePythonImportsOnly(v bool) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldSafePythonImportsOnly, v))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldRuleID, vs...))
}

// RuleIDGT applies the GT predicate on the "rule_id" field.
func RuleIDGT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldRuleID, v))
}

// RuleIDGTE applies the GTE predicate on the "rule_id" field.
func RuleIDGTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldRuleID, v))
}

// RuleIDLT applies the LT predicate on the "rule_id" field.
func RuleIDLT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldRuleID, v))
}

// RuleIDLTE applies the LTE predicate on the "rule_id" field.
func RuleIDLTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldRuleID, v))
}

// RuleIDContains applies the Contains predicate on the "rule_id" field.
func RuleIDContains(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContains(FieldRuleID, v))
}

// RuleIDHasPrefix applies the HasPrefix predicate on the "rule_id" field.
func RuleIDHasPrefix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasPrefix(FieldRuleID, v))
}

// RuleIDHasSuffix applies the HasSuffix predicate on the "rule_id" field.
func RuleIDHasSuffix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasSuffix(FieldRuleID, v))
}

// RuleIDEqualFold applies the EqualFold predicate on the "rule_id" field.
func RuleIDEqualFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEqualFold(FieldRuleID, v))
}

// RuleIDContainsFold applies the ContainsFold predicate on the "rule_id" field.
func RuleIDContainsFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContainsFold(FieldRuleID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContainsFold(FieldName, v))
}

// ToolNameEQ applies the EQ predicate on the "tool_name" field.
func ToolNameEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldToolName, v))
}

// ToolNameNEQ applies the NEQ predicate on the "tool_name" field.
func ToolNameNEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldToolName, v))
}

// ToolNameIn applies the In predicate on the "tool_name" field.
func ToolNameIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldToolName, vs...))
}

// ToolNameNotIn applies the NotIn predicate on the "tool_name" field.
func ToolNameNotIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldToolName, vs...))
}

// ToolNameGT applies the GT predicate on the "tool_name" field.
func ToolNameGT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldToolName, v))
}

// ToolNameGTE applies the GTE predicate on the "tool_name" field.
func ToolNameGTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldToolName, v))
}

// ToolNameLT applies the LT predicate on the "tool_name" field.
func ToolNameLT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldToolName, v))
}

// ToolNameLTE applies the LTE predicate on the "tool_name" field.
func ToolNameLTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldToolName, v))
}

// ToolNameContains applies the Contains predicate on the "tool_name" field.
func ToolNameContains(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContains(FieldToolName, v))
}

// ToolNameHasPrefix applies the HasPrefix predicate on the "tool_name" field.
func ToolNameHasPrefix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasPrefix(FieldToolName, v))
}

// ToolNameHasSuffix applies the HasSuffix predicate on the "tool_name" field.
func ToolNameHasSuffix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasSuffix(FieldToolName, v))
}

// ToolNameIsNil applies the IsNil predicate on the "tool_name" field.
func ToolNameIsNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIsNull(FieldToolName))
}

// ToolNameNotNil applies the NotNil predicate on the "tool_name" field.
func ToolNameNotNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotNull(FieldToolName))
}

// ToolNameEqualFold applies the EqualFold predicate on the "tool_name" field.
func ToolNameEqualFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEqualFold(FieldToolName, v))
}

// ToolNameContainsFold applies the ContainsFold predicate on the "tool_name" field.
func ToolNameContainsFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContainsFold(FieldToolName, v))
}

// ToolPatternEQ applies the EQ predicate on the "tool_pattern" field.
func ToolPatternEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldToolPattern, v))
}

// ToolPatternNEQ applies the NEQ predicate on the "tool_pattern" field.
func ToolPatternNEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldToolPattern, v))
}

// ToolPatternIn applies the In predicate on the "tool_pattern" field.
func ToolPatternIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldToolPattern, vs...))
}

// ToolPatternNotIn applies the NotIn predicate on the "tool_pattern" field.
func ToolPatternNotIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldToolPattern, vs...))
}

// ToolPatternGT applies the GT predicate on the "tool_pattern" field.
func ToolPatternGT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldToolPattern, v))
}

// ToolPatternGTE applies the GTE predicate on the "tool_pattern" field.
func ToolPatternGTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldToolPattern, v))
}

// ToolPatternLT applies the LT predicate on the "tool_pattern" field.
func ToolPatternLT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldToolPattern, v))
}

// ToolPatternLTE applies the LTE predicate on the "tool_pattern" field.
func ToolPatternLTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldToolPattern, v))
}

// ToolPatternContains applies the Contains predicate on the "tool_pattern" field.
func ToolPatternContains(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContains(FieldToolPattern, v))
}

// ToolPatternHasPrefix applies the HasPrefix predicate on the "tool_pattern" field.
func ToolPatternHasPrefix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasPrefix(FieldToolPattern, v))
}

// ToolPatternHasSuffix applies the HasSuffix predicate on the "tool_pattern" field.
func ToolPatternHasSuffix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasSuffix(FieldToolPattern, v))
}

// ToolPatternIsNil applies the IsNil predicate on the "tool_pattern" field.
func ToolPatternIsNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIsNull(FieldToolPattern))
}

// ToolPatternNotNil applies the NotNil predicate on the "tool_pattern" field.
func ToolPatternNotNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotNull(FieldToolPattern))
}

// ToolPatternEqualFold applies the EqualFold predicate on the "tool_pattern" field.
func ToolPatternEqualFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEqualFold(FieldToolPattern, v))
}

// ToolPatternContainsFold applies the ContainsFold predicate on the "tool_pattern" field.
func ToolPatternContainsFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContainsFold(FieldToolPattern, v))
}

// ToolCategoryEQ applies the EQ predicate on the "tool_category" field.
func ToolCategoryEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldToolCategory, v))
}

// ToolCategoryNEQ applies the NEQ predicate on the "tool_category" field.
func ToolCategoryNEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldToolCategory, v))
}

// ToolCategoryIn applies the In predicate on the "tool_category" field.
func ToolCategoryIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldToolCategory, vs...))
}

// ToolCategoryNotIn applies the NotIn predicate on the "tool_category" field.
func ToolCategoryNotIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldToolCategory, vs...))
}

// ToolCategoryGT applies the GT predicate on the "tool_category" field.
func ToolCategoryGT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldToolCategory, v))
}

// ToolCategoryGTE applies the GTE predicate on the "tool_category" field.
func ToolCategoryGTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldToolCategory, v))
}

// ToolCategoryLT applies the LT predicate on the "tool_category" field.
func ToolCategoryLT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldToolCategory, v))
}

// ToolCategoryLTE applies the LTE predicate on the "tool_category" field.
func ToolCategoryLTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldToolCategory, v))
}

// ToolCategoryContains applies the Contains predicate on the "tool_category" field.
func ToolCategoryContains(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContains(FieldToolCategory, v))
}

// ToolCategoryHasPrefix applies the HasPrefix predicate on the "tool_category" field.
func ToolCategoryHasPrefix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasPrefix(FieldToolCategory, v))
}

// ToolCategoryHasSuffix applies the HasSuffix predicate on the "tool_category" field.
func ToolCategoryHasSuffix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasSuffix(FieldToolCategory, v))
}

// ToolCategoryIsNil applies the IsNil predicate on the "tool_category" field.
func ToolCategoryIsNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIsNull(FieldToolCategory))
}

// ToolCategoryNotNil applies the NotNil predicate on the "tool_category" field.
func ToolCategoryNotNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotNull(FieldToolCategory))
}

// ToolCategoryEqualFold applies the EqualFold predicate on the "tool_category" field.
func ToolCategoryEqualFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEqualFold(FieldToolCategory, v))
}

// ToolCategoryContainsFold applies the ContainsFold predicate on the "tool_category" field.
func ToolCategoryContainsFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContainsFold(FieldToolCategory, v))
}

// CommandPatternEQ applies the EQ predicate on the "command_pattern" field.
func CommandPatternEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldCommandPattern, v))
}

// CommandPatternNEQ applies the NEQ predicate on the "command_pattern" field.
func CommandPatternNEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldCommandPattern, v))
}

// CommandPatternIn applies the In predicate on the "command_pattern" field.
func CommandPatternIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldCommandPattern, vs...))
}

// CommandPatternNotIn applies the NotIn predicate on the "command_pattern" field.
func CommandPatternNotIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldCommandPattern, vs...))
}

// CommandPatternGT applies the GT predicate on the "command_pattern" field.
func CommandPatternGT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldCommandPattern, v))
}

// CommandPatternGTE applies the GTE predicate on the "command_pattern" field.
func CommandPatternGTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldCommandPattern, v))
}

// CommandPatternLT applies the LT predicate on the "command_pattern" field.
func CommandPatternLT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldCommandPattern, v))
}

// CommandPatternLTE applies the LTE predicate on the "command_pattern" field.
func CommandPatternLTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldCommandPattern, v))
}

// CommandPatternContains applies the Contains predicate on the "command_pattern" field.
func CommandPatternContains(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContains(FieldCommandPattern, v))
}

// CommandPatternHasPrefix applies the HasPrefix predicate on the "command_pattern" field.
func CommandPatternHasPrefix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasPrefix(FieldCommandPattern, v))
}

// CommandPatternHasSuffix applies the HasSuffix predicate on the "command_pattern" field.
func CommandPatternHasSuffix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasSuffix(FieldCommandPattern, v))
}

// CommandPatternIsNil applies the IsNil predicate on the "command_pattern" field.
func CommandPatternIsNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIsNull(FieldCommandPattern))
}

// CommandPatternNotNil applies the NotNil predicate on the "command_pattern" field.
func CommandPatternNotNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotNull(FieldCommandPattern))
}

// CommandPatternEqualFold applies the EqualFold predicate on the "command_pattern" field.
func CommandPatternEqualFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEqualFold(FieldCommandPattern, v))
}

// CommandPatternContainsFold applies the ContainsFold predicate on the "command_pattern" field.
func CommandPatternContainsFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContainsFold(FieldCommandPattern, v))
}

// FilePatternEQ applies the EQ predicate on the "file_pattern" field.
func FilePatternEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldFilePattern, v))
}

// FilePatternNEQ applies the NEQ predicate on the "file_pattern" field.
func FilePatternNEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldFilePattern, v))
}

// FilePatternIn applies the In predicate on the "file_pattern" field.
func FilePatternIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldFilePattern, vs...))
}

// FilePatternNotIn applies the NotIn predicate on the "file_pattern" field.
func FilePatternNotIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldFilePattern, vs...))
}

// FilePatternGT applies the GT predicate on the "file_pattern" field.
func FilePatternGT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldFilePattern, v))
}

// FilePatternGTE applies the GTE predicate on the "file_pattern" field.
func FilePatternGTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldFilePattern, v))
}

// FilePatternLT applies the LT predicate on the "file_pattern" field.
func FilePatternLT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldFilePattern, v))
}

// FilePatternLTE applies the LTE predicate on the "file_pattern" field.
func FilePatternLTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldFilePattern, v))
}

// FilePatternContains applies the Contains predicate on the "file_pattern" field.
func FilePatternContains(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContains(FieldFilePattern, v))
}

// FilePatternHasPrefix applies the HasPrefix predicate on the "file_pattern" field.
func FilePatternHasPrefix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasPrefix(FieldFilePattern, v))
}

// FilePatternHasSuffix applies the HasSuffix predicate on the "file_pattern" field.
func FilePatternHasSuffix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasSuffix(FieldFilePattern, v))
}

// FilePatternIsNil applies the IsNil predicate on the "file_pattern" field.
func FilePatternIsNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIsNull(FieldFilePattern))
}

// FilePatternNotNil applies the NotNil predicate on the "file_pattern" field.
func FilePatternNotNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotNull(FieldFilePattern))
}

// FilePatternEqualFold applies the EqualFold predicate on the "file_pattern" field.
func FilePatternEqualFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEqualFold(FieldFilePattern, v))
}

// FilePatternContainsFold applies the ContainsFold predicate on the "file_pattern" field.
func FilePatternContainsFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContainsFold(FieldFilePattern, v))
}

// DecisionEQ applies the EQ predicate on the "decision" field.
func DecisionEQ(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldDecision, v))
}

// DecisionNEQ applies the NEQ predicate on the "decision" field.
func DecisionNEQ(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldDecision, v))
}

// DecisionIn applies the In predicate on the "decision" field.
func DecisionIn(vs ...int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldDecision, vs...))
}

// DecisionNotIn applies the NotIn predicate on the "decision" field.
func DecisionNotIn(vs ...int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldDecision, vs...))
}

// DecisionGT applies the GT predicate on the "decision" field.
func DecisionGT(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldDecision, v))
}

// DecisionGTE applies the GTE predicate on the "decision" field.
func DecisionGTE(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldDecision, v))
}

// DecisionLT applies the LT predicate on the "decision" field.
func DecisionLT(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldDecision, v))
}

// DecisionLTE applies the LTE predicate on the "decision" field.
func DecisionLTE(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldDecision, v))
}

// RiskLevelEQ applies the EQ predicate on the "risk_level" field.
func RiskLevelEQ(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldRiskLevel, v))
}

// RiskLevelNEQ applies the NEQ predicate on the "risk_level" field.
func RiskLevelNEQ(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldRiskLevel, v))
}

// RiskLevelIn applies the In predicate on the "risk_level" field.
func RiskLevelIn(vs ...int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldRiskLevel, vs...))
}

// RiskLevelNotIn applies the NotIn predicate on the "risk_level" field.
func RiskLevelNotIn(vs ...int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldRiskLevel, vs...))
}

// RiskLevelGT applies the GT predicate on the "risk_level" field.
func RiskLevelGT(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldRiskLevel, v))
}

// RiskLevelGTE applies the GTE predicate on the "risk_level" field.
func RiskLevelGTE(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldRiskLevel, v))
}

// RiskLevelLT applies the LT predicate on the "risk_level" field.
func RiskLevelLT(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldRiskLevel, v))
}

// RiskLevelLTE applies the LTE predicate on the "risk_level" field.
func RiskLevelLTE(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldRiskLevel, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContainsFold(FieldReason, v))
}

// AlternativeEQ applies the EQ predicate on the "alternative" field.
func AlternativeEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldAlternative, v))
}

// AlternativeNEQ applies the NEQ predicate on the "alternative" field.
func AlternativeNEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldAlternative, v))
}

// AlternativeIn applies the In predicate on the "alternative" field.
func AlternativeIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldAlternative, vs...))
}

// AlternativeNotIn applies the NotIn predicate on the "alternative" field.
func AlternativeNotIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldAlternative, vs...))
}

// AlternativeGT applies the GT predicate on the "alternative" field.
func AlternativeGT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldAlternative, v))
}

// AlternativeGTE applies the GTE predicate on the "alternative" field.
func AlternativeGTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldAlternative, v))
}

// AlternativeLT applies the LT predicate on the "alternative" field.
func AlternativeLT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldAlternative, v))
}

// AlternativeLTE applies the LTE predicate on the "alternative" field.
func AlternativeLTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldAlternative, v))
}

// AlternativeContains applies the Contains predicate on the "alternative" field.
func AlternativeContains(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContains(FieldAlternative, v))
}

// AlternativeHasPrefix applies the HasPrefix predicate on the "alternative" field.
func AlternativeHasPrefix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasPrefix(FieldAlternative, v))
}

// AlternativeHasSuffix applies the HasSuffix predicate on the "alternative" field.
func AlternativeHasSuffix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasSuffix(FieldAlternative, v))
}

// AlternativeIsNil applies the IsNil predicate on the "alternative" field.
func AlternativeIsNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIsNull(FieldAlternative))
}

// AlternativeNotNil applies the NotNil predicate on the "alternative" field.
func AlternativeNotNil() predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotNull(FieldAlternative))
}

// AlternativeEqualFold applies the EqualFold predicate on the "alternative" field.
func AlternativeEqualFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEqualFold(FieldAlternative, v))
}

// AlternativeContainsFold applies the ContainsFold predicate on the "alternative" field.
func AlternativeContainsFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContainsFold(FieldAlternative, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldPriority, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldEnabled, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldContainsFold(FieldSource, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// SafePythonImportsOnlyEQ applies the EQ predicate on the "safe_python_imports_only" field.
func SafePythonImportsOnlyEQ(v bool) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldEQ(FieldSafePythonImportsOnly, v))
}

// SafePythonImportsOnlyNEQ applies the NEQ predicate on the "safe_python_imports_only" field.
func SafePythonImportsOnlyNEQ(v bool) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.FieldNEQ(FieldSafePythonImportsOnly, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ApprovalRule) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ApprovalRule) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ApprovalRule) predicate.ApprovalRule {
	return predicate.ApprovalRule(sql.NotPredicates(p))
}
