import { useEffect, useCallback } from "react";

export type KeyHandler = () => void;
export type KeyboardHandlers = Record<string, KeyHandler>;

interface UseKeyboardOptions {
  /**
   * Whether keyboard shortcuts are enabled
   */
  enabled?: boolean;

  /**
   * Elements to ignore keyboard events from (e.g., inputs, textareas)
   */
  ignoreElements?: string[];

  /**
   * Require modifier keys (Ctrl, Alt, Meta) for shortcuts
   */
  requireModifier?: boolean;
}

/**
 * Hook for managing keyboard shortcuts and navigation
 */
export function useKeyboard(
  handlers: KeyboardHandlers,
  options: UseKeyboardOptions = {}
) {
  const {
    enabled = true,
    ignoreElements = ["INPUT", "TEXTAREA", "SELECT"],
    requireModifier = false,
  } = options;

  const handleKeyDown = useCallback(
    (event: KeyboardEvent) => {
      if (!enabled) return;

      // Ignore if we're in an input element -- tagName covers INPUT/TEXTAREA/SELECT, but a
      // contenteditable div (e.g. a rich-text omnibar) has no matching tagName, so it needs
      // its own check too. Matches the precedent in shortcutRegistry.ts's isInputElement and
      // OmnibarContext.tsx's equivalent guard.
      //
      // Also ignore a focused native button/link/role="button" element -- these have their
      // own default keyboard activation (Enter/Space) the browser dispatches on the focused
      // element itself, which a single-letter global shortcut has no business intercepting.
      // Without this, registering e.g. an unscoped `Enter` handler here (page.tsx does, for
      // "open the focused session row") calls preventDefault() on every Enter keydown on the
      // page -- even when its own handler body no-ops -- silently breaking Enter-activation
      // for every other focused button on the page (found via a real, reproducibly-failing
      // scroll-forward-blocked-toast-keyboard.spec.ts case: Enter never dismissed the toast's
      // "Got it" button, Space did, because Space isn't a registered shortcut key here).
      // event.target can be the bare Document node itself (real apps never
      // do this, but a test dispatching keydown directly on `document` does)
      // -- Document has no getAttribute, so that call is optional-chained
      // rather than assumed to exist on every EventTarget.
      const target = event.target as HTMLElement;
      const tag = target.tagName;
      if (
        ignoreElements.includes(tag) ||
        target.isContentEditable ||
        tag === "BUTTON" ||
        tag === "A" ||
        target.getAttribute?.("role") === "button"
      ) {
        return;
      }

      // Skip events generated by IME composition (e.g. CJK input methods)
      if (event.isComposing || event.keyCode === 229) return;

      // Build key identifier with modifiers
      const key = event.key;
      const hasModifier =
        event.ctrlKey || event.altKey || event.metaKey || event.shiftKey;

      // If requireModifier is true, skip unless a modifier is pressed
      if (requireModifier && !hasModifier) {
        return;
      }

      // Check if we have a handler for this key
      if (handlers[key]) {
        event.preventDefault();
        handlers[key]();
      }
    },
    [enabled, handlers, ignoreElements, requireModifier]
  );

  useEffect(() => {
    if (!enabled) return;

    window.addEventListener("keydown", handleKeyDown);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [enabled, handleKeyDown]);
}

