import type { Feature } from '../types';

export const analyticsFeatures = {
  'get-escape-analytics-summary': {
    id: 'get-escape-analytics-summary',
    title: 'Get Escape Analytics Summary',
    description: 'Returns a summarized view of escape analytics events across sessions.',
    rpcIds: ['GetEscapeAnalyticsSummary'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'get-program-analytics': {
    id: 'get-program-analytics',
    title: 'Get Program Analytics',
    description: 'Retrieves aggregated analytics data for a specific program or agent type.',
    rpcIds: ['GetProgramAnalytics'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'query-escape-analytics': {
    id: 'query-escape-analytics',
    title: 'Query Escape Analytics',
    description: 'Queries raw escape analytics events with filtering and pagination support.',
    rpcIds: ['QueryEscapeAnalytics'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'get-insights-summary': {
    id: 'get-insights-summary',
    title: 'Get Insights Summary',
    description: 'Returns a paginated summary of token usage and cost insights across sessions.',
    rpcIds: ['GetInsightsSummary'],
    componentPaths: [],
    testIds: [
      'TestGetInsightsSummary_EmptyStore',
      'TestGetInsightsSummary_Aggregation',
      'TestGetInsightsSummary_TimeFilter',
      'TestGetInsightsSummary_ModelFilter',
      'TestGetInsightsSummary_OrphanFilter',
      'TestGetInsightsSummary_DailyRollup',
      'TestGetInsightsSummary_ModelBreakdown',
      'TestGetInsightsSummary_SortByCostDesc',
      'TestGetInsightsSummary_Pagination',
      'TestGetInsightsSummary_CacheHitRate',
    ],
    status: 'stable',
    since: '1.0.0',
  },
} as const satisfies Record<string, Feature>;
