import type { Feature } from '../types';

export const approvalFeatures = {
  'approval-delete-rule': {
    id: 'approval-delete-rule',
    title: 'Delete Approval Rule',
    description: 'Deletes an existing approval rule by ID.',
    rpcIds: ['approval:delete-rule'],
    componentPaths: [],
    testIds: [
      'TestDeleteApprovalRule_Success',
      'TestDeleteApprovalRule_EmptyID',
      'TestDeleteApprovalRule_NotFound',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'approval-get-analytics': {
    id: 'approval-get-analytics',
    title: 'Get Approval Analytics',
    description: 'Returns analytics and approval rate summaries over a configurable time window.',
    rpcIds: ['approval:get-analytics'],
    componentPaths: [],
    testIds: [
      'TestGetApprovalAnalytics_ReturnsEmptySummaryWhenNoData',
      'TestGetApprovalAnalytics_CustomWindowDays',
      'TestClassify_DailyBucketAutoApproveRate',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'approval-list-pending': {
    id: 'approval-list-pending',
    title: 'List Pending Approvals',
    description: 'Lists all pending approval requests, optionally filtered by session ID.',
    rpcIds: ['approval:list-pending'],
    componentPaths: [],
    testIds: [
      'TestListPendingApprovals_EmptyInitially',
      'TestListPendingApprovals_ReturnsAllPending',
      'TestListPendingApprovals_FilterBySessionID',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'approval-list-rules': {
    id: 'approval-list-rules',
    title: 'List Approval Rules',
    description: 'Lists all approval rules, with optional filtering by source.',
    rpcIds: ['approval:list-rules'],
    componentPaths: [],
    testIds: [
      'TestListApprovalRules_ReturnsSeedRules',
      'TestListApprovalRules_SourceFilter',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'approval-resolve': {
    id: 'approval-resolve',
    title: 'Resolve Approval',
    description: 'Resolves a pending approval request by allowing or denying the requested action.',
    rpcIds: ['approval:resolve'],
    componentPaths: [],
    testIds: [
      'TestApprovalFlow_Allow',
      'TestApprovalFlow_Deny',
      'TestApprovalFlow_Timeout',
      'TestApprovalFlow_MethodNotAllowed',
      'TestApprovalFlow_ParseError',
      'TestApprovalFlow_SessionIDFromHeader',
      'TestApprovalFlow_AskUserQuestion_DeferToNativeDialog',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'approval-upsert-rule': {
    id: 'approval-upsert-rule',
    title: 'Upsert Approval Rule',
    description: 'Creates or updates an approval rule defining auto-allow or auto-deny patterns.',
    rpcIds: ['approval:upsert-rule'],
    componentPaths: [],
    testIds: [
      'TestUpsertApprovalRule_Success',
      'TestUpsertApprovalRule_UpdateExisting',
      'TestUpsertApprovalRule_NilRule',
      'TestUpsertApprovalRule_EmptyID',
    ],
    status: 'stable',
    since: '1.0.0',
  },
} as const satisfies Record<string, Feature>;
