import type { Feature } from '../types';

export const backlogFeatures = {
  'backlog-approve-plan': {
    id: 'backlog-approve-plan',
    title: 'Approve Plan',
    description: 'Approves the plan artifact for a backlog item, marking it ready for execution.',
    rpcIds: ['backlog:approve-plan'],
    componentPaths: [],
    testIds: [
      'TestApprovePlan_MissingPlanArtifactsPath_ReturnsFailedPrecondition',
      'TestApprovePlan_HappyPath_SetsPlanApprovedAndTimestamp',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'backlog-archive-item': {
    id: 'backlog-archive-item',
    title: 'Archive Backlog Item',
    description: 'Archives a backlog item, removing it from the active queue.',
    rpcIds: ['backlog:archive-item'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-attach-session': {
    id: 'backlog-attach-session',
    title: 'Attach Session To Item',
    description: 'Attaches an existing AI agent session to a backlog item.',
    rpcIds: ['backlog:attach-session'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-create-item': {
    id: 'backlog-create-item',
    title: 'Create Backlog Item',
    description: 'Creates a new backlog item with a title and optional metadata.',
    rpcIds: ['backlog:create-item'],
    componentPaths: [],
    testIds: [
      'TestCreateBacklogItem_Success',
      'TestCreateBacklogItem_EmptyTitle',
      'TestCreateBacklogItem_NilStorage',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'backlog-create-source': {
    id: 'backlog-create-source',
    title: 'Create Item Source',
    description: 'Creates a new item source that feeds backlog items from an external integration.',
    rpcIds: ['backlog:create-source'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-delete-source': {
    id: 'backlog-delete-source',
    title: 'Delete Item Source',
    description: 'Deletes an item source and stops ingestion of backlog items from it.',
    rpcIds: ['backlog:delete-source'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-get-item': {
    id: 'backlog-get-item',
    title: 'Get Backlog Item',
    description: 'Retrieves a single backlog item by ID with its full details.',
    rpcIds: ['backlog:get-item'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-get-sync-history': {
    id: 'backlog-get-sync-history',
    title: 'Get Sync History',
    description: 'Retrieves the synchronization history for a backlog item source.',
    rpcIds: ['backlog:get-sync-history'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-list-items': {
    id: 'backlog-list-items',
    title: 'List Backlog Items',
    description: 'Lists backlog items with optional filtering by status and other criteria.',
    rpcIds: ['backlog:list-items'],
    componentPaths: [],
    testIds: [
      'TestListBacklogItems_DefaultFilterHidesTerminalStatuses',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'backlog-list-sources': {
    id: 'backlog-list-sources',
    title: 'List Item Sources',
    description: 'Lists all configured item sources that feed backlog items.',
    rpcIds: ['backlog:list-sources'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-override-verdict': {
    id: 'backlog-override-verdict',
    title: 'Override Verdict',
    description: 'Overrides the triage verdict for a backlog item with a manual decision.',
    rpcIds: ['backlog:override-verdict'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-spawn-session-autonomous': {
    id: 'backlog-spawn-session-autonomous',
    title: 'Spawn Session From Item (Autonomous)',
    description: 'Spawns an autonomous AI agent session from a backlog item without human-in-the-loop confirmation.',
    rpcIds: ['backlog:spawn-session-autonomous'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-spawn-session': {
    id: 'backlog-spawn-session',
    title: 'Spawn Session From Item',
    description: 'Spawns an AI agent session from a backlog item to begin working on it.',
    rpcIds: ['backlog:spawn-session'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-suggest-next': {
    id: 'backlog-suggest-next',
    title: 'Suggest Next Item',
    description: 'Suggests the next backlog item to work on based on priority and context.',
    rpcIds: ['backlog:suggest-next'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-transition-status': {
    id: 'backlog-transition-status',
    title: 'Transition Backlog Item Status',
    description: 'Transitions a backlog item through its lifecycle status states.',
    rpcIds: ['backlog:transition-status'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-trigger-re-review': {
    id: 'backlog-trigger-re-review',
    title: 'Trigger Re-Review',
    description: 'Triggers a re-review of a backlog item to re-evaluate its triage verdict.',
    rpcIds: ['backlog:trigger-re-review'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-trigger-sync': {
    id: 'backlog-trigger-sync',
    title: 'Trigger Sync',
    description: 'Triggers an immediate synchronization of backlog items from configured sources.',
    rpcIds: ['backlog:trigger-sync'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-trigger-triage': {
    id: 'backlog-trigger-triage',
    title: 'Trigger Triage',
    description: 'Triggers AI-powered triage of pending backlog items to assign priorities and verdicts.',
    rpcIds: ['backlog:trigger-triage'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-update-item': {
    id: 'backlog-update-item',
    title: 'Update Backlog Item',
    description: 'Updates the fields of an existing backlog item such as title or description.',
    rpcIds: ['backlog:update-item'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-update-source': {
    id: 'backlog-update-source',
    title: 'Update Item Source',
    description: 'Updates the configuration of an existing backlog item source.',
    rpcIds: ['backlog:update-source'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
} as const satisfies Record<string, Feature>;
