import type { Feature } from '../types';

export const backlogFeatures = {
  'backlog-approve-plan': {
    id: 'backlog-approve-plan',
    title: 'Approve Plan',
    description: 'Approves the plan artifact for a backlog item, marking it ready for execution.',
    rpcIds: ['backlog:approve-plan'],
    componentPaths: [],
    testIds: [
      'TestApprovePlan_MissingPlanArtifactsPath_ReturnsFailedPrecondition',
      'TestApprovePlan_HappyPath_SetsPlanApprovedAndTimestamp',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'backlog-archive-item': {
    id: 'backlog-archive-item',
    title: 'Archive Backlog Item',
    description: 'Archives a backlog item, removing it from the active queue.',
    rpcIds: ['backlog:archive-item'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-attach-session': {
    id: 'backlog-attach-session',
    title: 'Attach Session To Item',
    description: 'Attaches an existing AI agent session to a backlog item.',
    rpcIds: ['backlog:attach-session'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-create-item': {
    id: 'backlog-create-item',
    title: 'Create Backlog Item',
    description: 'Creates a new backlog item with a title and optional metadata. Accepts a GitHub URL/shorthand for repo_path, resolving and cloning it (mirrors session creation) instead of storing it verbatim.',
    rpcIds: ['backlog:create-item'],
    componentPaths: [
      'web-app/src/components/backlog/BacklogItemForm.tsx',
      'web-app/src/components/ui/RepoPathInput.tsx',
    ],
    testIds: [
      'TestCreateBacklogItem_Success',
      'TestCreateBacklogItem_EmptyTitle',
      'TestCreateBacklogItem_NilStorage',
      'TestCreateBacklogItem_ResolvesGitHubURL',
      'TestCreateBacklogItem_GitHubResolveError_ReturnsInvalidArgument',
      'TestCreateBacklogItem_PlainPath_DoesNotCallResolver',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'backlog-create-source': {
    id: 'backlog-create-source',
    title: 'Create Item Source',
    description: 'Creates a new item source that feeds backlog items from an external integration.',
    rpcIds: ['backlog:create-source'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-first-visit-tour': {
    id: 'backlog-first-visit-tour',
    title: 'Backlog First-Visit Tour',
    description: 'First-visit walkthrough for the backlog page explaining the item lifecycle, the Repository Path field (local clone vs. GitHub URL), and the skip-planning/skip-review-gate flags. Re-openable via the "?" button in the page header.',
    rpcIds: [],
    componentPaths: [
      'web-app/src/components/backlog/BacklogTourModal.tsx',
      'web-app/src/components/backlog/useBacklogTour.ts',
    ],
    testIds: [
      'BacklogTourModal — visibility',
      'BacklogTourModal — navigation',
      'BacklogTourModal — dismissal',
      'e2e:backlog-tour-first-visit',
      'e2e:backlog-tour-reopen-button',
    ],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-delete-source': {
    id: 'backlog-delete-source',
    title: 'Delete Item Source',
    description: 'Deletes an item source and stops ingestion of backlog items from it.',
    rpcIds: ['backlog:delete-source'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-get-item': {
    id: 'backlog-get-item',
    title: 'Get Backlog Item',
    description: 'Retrieves a single backlog item by ID with its full details.',
    rpcIds: ['backlog:get-item'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-get-sync-history': {
    id: 'backlog-get-sync-history',
    title: 'Get Sync History',
    description: 'Retrieves the synchronization history for a backlog item source.',
    rpcIds: ['backlog:get-sync-history'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-list-items': {
    id: 'backlog-list-items',
    title: 'List Backlog Items',
    description: 'Lists backlog items with optional filtering by status and other criteria.',
    rpcIds: ['backlog:list-items'],
    componentPaths: [],
    testIds: [
      'TestListBacklogItems_DefaultFilterHidesTerminalStatuses',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'backlog-list-sources': {
    id: 'backlog-list-sources',
    title: 'List Item Sources',
    description: 'Lists all configured item sources that feed backlog items.',
    rpcIds: ['backlog:list-sources'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-override-verdict': {
    id: 'backlog-override-verdict',
    title: 'Override Verdict',
    description: 'Overrides the triage verdict for a backlog item with a manual decision.',
    rpcIds: ['backlog:override-verdict'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-spawn-session-autonomous': {
    id: 'backlog-spawn-session-autonomous',
    title: 'Spawn Session From Item (Autonomous)',
    description: 'Spawns an autonomous AI agent session from a backlog item without human-in-the-loop confirmation.',
    rpcIds: ['backlog:spawn-session-autonomous'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-spawn-session': {
    id: 'backlog-spawn-session',
    title: 'Spawn Session From Item',
    description: 'Spawns an AI agent session from a backlog item to begin working on it.',
    rpcIds: ['backlog:spawn-session'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-suggest-next': {
    id: 'backlog-suggest-next',
    title: 'Suggest Next Item',
    description: 'Suggests the next backlog item to work on based on priority and context.',
    rpcIds: ['backlog:suggest-next'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-transition-status': {
    id: 'backlog-transition-status',
    title: 'Transition Backlog Item Status',
    description: 'Transitions a backlog item through its lifecycle status states.',
    rpcIds: ['backlog:transition-status'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-trigger-re-review': {
    id: 'backlog-trigger-re-review',
    title: 'Trigger Re-Review',
    description: 'Triggers a re-review of a backlog item to re-evaluate its triage verdict.',
    rpcIds: ['backlog:trigger-re-review'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-trigger-sync': {
    id: 'backlog-trigger-sync',
    title: 'Trigger Sync',
    description: 'Triggers an immediate synchronization of backlog items from configured sources.',
    rpcIds: ['backlog:trigger-sync'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-trigger-triage': {
    id: 'backlog-trigger-triage',
    title: 'Trigger Triage',
    description: 'Triggers AI-powered triage of pending backlog items to assign priorities and verdicts.',
    rpcIds: ['backlog:trigger-triage'],
    componentPaths: [
      'web-app/src/components/backlog/BacklogItemDetail.tsx',
      'web-app/src/components/backlog/BacklogItemCard.tsx',
    ],
    testIds: ['e2e:backlog-triage-gate-disabled'],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-update-item': {
    id: 'backlog-update-item',
    title: 'Update Backlog Item',
    description: 'Updates the fields of an existing backlog item such as title or description. Also the fix-up path for an item created with an unresolvable repo_path — resolves GitHub URLs the same way CreateBacklogItem does.',
    rpcIds: ['backlog:update-item'],
    componentPaths: ['web-app/src/components/backlog/BacklogItemForm.tsx'],
    testIds: [
      'TestUpdateBacklogItem_ResolvesGitHubURL',
      'TestUpdateBacklogItem_GitHubResolveError_ReturnsInvalidArgument',
    ],
    status: 'experimental',
    since: '1.0.0',
  },
  'backlog-update-source': {
    id: 'backlog-update-source',
    title: 'Update Item Source',
    description: 'Updates the configuration of an existing backlog item source.',
    rpcIds: ['backlog:update-source'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'triage-related-work': {
    id: 'triage-related-work',
    title: 'Find Related Past Work',
    description: 'Triage panel search box that surfaces session-deduped prior sessions related to a backlog item, pre-populated with the item title.',
    rpcIds: ['history:search'],
    componentPaths: ['web-app/src/components/backlog/TriageRelatedWorkSection.tsx'],
    testIds: [
      'pre-populates query with backlog item title on mount',
      'shows reassuring copy when zero matches found',
      'e2e:triage-related-work - Find related past work surfaces prior sessions',
    ],
    status: 'stable',
    since: '1.0.0',
  },
} as const satisfies Record<string, Feature>;
