import type { Feature } from '../types';

export const sessionFeatures = {
  'session-create': {
    id: 'session-create',
    title: 'Create Session',
    description: 'Creates a new AI agent session in a directory, worktree, or one-off mode.',
    rpcIds: ['session:create'],
    componentPaths: [
      'components/sessions/Omnibar.tsx',
      'components/sessions/OmnibarCreationPanel.tsx',
    ],
    testIds: [
      'Session Lifecycle > e2e:session-create - Session create UI is accessible',
      'Session Create Directory > creates a session in a directory',
      'One-Off Session > creates a one-off session',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-list': {
    id: 'session-list',
    title: 'Session List',
    description: 'Lists and streams updates for all sessions.',
    rpcIds: ['session:list', 'session:watch'],
    componentPaths: ['components/sessions/SessionList.tsx'],
    testIds: ['Smoke Tests > home page loads successfully'],
    status: 'stable',
    since: '1.0.0',
  },
  'session-delete': {
    id: 'session-delete',
    title: 'Delete Session',
    description: 'Deletes a session and its associated worktree.',
    rpcIds: ['session:delete'],
    componentPaths: ['components/sessions/SessionList.tsx'],
    testIds: [
      'Session Lifecycle > e2e:session-delete - Session management page loads',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-acknowledge': {
    id: 'session-acknowledge',
    title: 'Acknowledge Session',
    description: 'Acknowledges a session to mark it as seen and clear its notification state.',
    rpcIds: ['session:acknowledge'],
    componentPaths: [],
    testIds: [
      'TestAcknowledgeSession_EmptyID',
      'TestAcknowledgeSession_UnknownSession',
      'TestAcknowledgeSession_UpdatesLiveInstance',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-batch-create': {
    id: 'session-batch-create',
    title: 'Batch Create Sessions',
    description: 'Creates multiple AI agent sessions concurrently with configurable parallelism limits.',
    rpcIds: ['session:batch-create'],
    componentPaths: [],
    testIds: [
      'TestBatchCreateSessions_SemaphoreLimitsConcurrency',
      'TestBatchCreateSessions_MaxConcurrencyEnforced',
      'TestBatchCreateSessions_EmptyRequest',
      'TestBatchCreateSessions_DuplicateTitlesRejected',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-clear-conversation-state': {
    id: 'session-clear-conversation-state',
    title: 'Clear Conversation State',
    description: 'Clears the stored conversation state for a session, resetting its history.',
    rpcIds: ['session:clear-conversation-state'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'session-delete-prompt-history': {
    id: 'session-delete-prompt-history',
    title: 'Delete Prompt History',
    description: 'Deletes a specific entry from the session prompt history.',
    rpcIds: ['session:delete-prompt-history'],
    componentPaths: [],
    testIds: [
      'TestDeletePromptHistory_EmptyID',
      'TestDeletePromptHistory_RemovesEntry',
      'TestDeletePromptHistory_DeleteOneKeepsOthers',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-fork': {
    id: 'session-fork',
    title: 'Fork Session',
    description: 'Forks an existing session from a checkpoint into a new independent session.',
    rpcIds: ['session:fork'],
    componentPaths: [],
    testIds: [
      'TestForkSession_Success',
      'TestForkSession_MissingSessionID',
      'TestForkSession_MissingNewTitle',
      'TestForkSession_SessionNotFound',
      'TestForkSession_DuplicateTitle',
      'TestForkSession_MissingCheckpointID',
      'TestForkSession_CheckpointNotFound',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-get': {
    id: 'session-get',
    title: 'Get Session',
    description: 'Retrieves a single session by its ID or title.',
    rpcIds: ['session:get'],
    componentPaths: [],
    testIds: [
      'TestGetSession_MissingID',
      'TestGetSession_UnknownID',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-get-diff': {
    id: 'session-get-diff',
    title: 'Get Session Diff',
    description: 'Returns the git diff for the files modified in a session.',
    rpcIds: ['session:get-diff'],
    componentPaths: [],
    testIds: [
      'TestGetSessionDiff_FindsByUUID',
      'TestGetSessionDiff_FindsByTitle',
      'TestGetSessionDiff_UnknownIDReturnsNotFound',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-get-terminal-snapshot': {
    id: 'session-get-terminal-snapshot',
    title: 'Get Terminal Snapshot',
    description: 'Retrieves a point-in-time snapshot of the session terminal output.',
    rpcIds: ['session:get-terminal-snapshot'],
    componentPaths: [],
    testIds: [
      'TestGetTerminalSnapshot_EmptyID',
      'TestGetTerminalSnapshot_SessionNotFound',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-get-vcs-status': {
    id: 'session-get-vcs-status',
    title: 'Get VCS Status',
    description: 'Returns the version control system status for the files in a session workspace.',
    rpcIds: ['session:get-vcs-status'],
    componentPaths: [],
    testIds: [
      'TestWorkspaceService_GetVCSStatus_FindsByUUID',
      'TestWorkspaceService_GetVCSStatus_FindsByTitle',
      'TestWorkspaceService_GetVCSStatus_UnknownIDReturnsNotFound',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-list-branches': {
    id: 'session-list-branches',
    title: 'List Branches',
    description: 'Lists the git branches available in a given repository path.',
    rpcIds: ['session:list-branches'],
    componentPaths: [],
    testIds: [
      'TestListBranches_EmptyPath',
      'TestListBranches_PathOutsideHome',
      'TestListBranches_NonExistentPath',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-list-prompt-history': {
    id: 'session-list-prompt-history',
    title: 'List Prompt History',
    description: 'Returns the prompt history entries recorded for a session.',
    rpcIds: ['session:list-prompt-history'],
    componentPaths: [],
    testIds: [
      'TestListPromptHistory_EmptyInitially',
      'TestListPromptHistory_ReturnsEntriesAfterRecord',
      'TestListPromptHistory_EntryFieldsPopulated',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-rename': {
    id: 'session-rename',
    title: 'Rename Session',
    description: 'Renames an existing session to a new unique title.',
    rpcIds: ['session:rename'],
    componentPaths: [],
    testIds: [
      'TestRenameSession_MissingSessionID',
      'TestRenameSession_MissingNewTitle',
      'TestRenameSession_DuplicateTitle',
      'TestRenameSession_SessionNotFound',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-restart': {
    id: 'session-restart',
    title: 'Restart Session',
    description: 'Restarts a session, relaunching its AI agent process.',
    rpcIds: ['session:restart'],
    componentPaths: [],
    testIds: [
      'TestRestartSession_EmptyID',
      'TestRestartSession_SessionNotFound',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-run-one-shot': {
    id: 'session-run-one-shot',
    title: 'Run One Shot',
    description: 'Runs a one-shot AI agent task in a session without persistent state.',
    rpcIds: ['session:run-one-shot'],
    componentPaths: [],
    testIds: [
      'TestExtractPRURL_Found',
      'TestExtractPRURL_NotFound',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'session-stream-terminal': {
    id: 'session-stream-terminal',
    title: 'Stream Terminal',
    description: 'Streams real-time terminal output from a session over a server-sent event connection.',
    rpcIds: ['session:stream-terminal'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'session-update': {
    id: 'session-update',
    title: 'Update Session',
    description: 'Updates session metadata such as tags, title, and status.',
    rpcIds: ['session:update'],
    componentPaths: [],
    testIds: [
      'TestUpdateSession_MissingID',
      'TestUpdateSession_NotFound',
      'TestUpdateSession_TagsUpdate',
      'TestUpdateSession_TagsUpdate_Replaces',
      'TestUpdateSession_TitleConflict',
      'TestUpdateSession_HandlerOrdering_MetadataBeforeStatus',
    ],
    status: 'stable',
    since: '1.0.0',
  },
} as const satisfies Record<string, Feature>;
