import type { Feature } from '../types';

export const unfinishedFeatures = {
  'unfinished-commit-push': {
    id: 'unfinished-commit-push',
    title: 'Quick Commit Push',
    description: 'Commits and pushes pending changes in a worktree with a single RPC call.',
    rpcIds: ['unfinished:commit-push'],
    componentPaths: [],
    testIds: [
      'TestQuickCommitPush_EmptyCommitMessage',
      'TestQuickCommitPush_UnknownWorktree',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'unfinished-dismiss': {
    id: 'unfinished-dismiss',
    title: 'Dismiss Worktree',
    description: 'Dismisses a worktree from the unfinished work list so it no longer appears.',
    rpcIds: ['unfinished:dismiss'],
    componentPaths: [],
    testIds: [
      'TestStateStore_DismissWorktree',
      'TestStateStore_IsDismissed',
      'unfinished-work > Dismiss button calls DismissWorktree RPC',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'unfinished-get-ai-summary': {
    id: 'unfinished-get-ai-summary',
    title: 'Get Worktree AI Summary',
    description: 'Generates an AI-produced summary of uncommitted changes in a worktree.',
    rpcIds: ['unfinished:get-ai-summary'],
    componentPaths: [],
    testIds: [
      'TestGetWorktreeAISummary_UnknownWorktree',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'unfinished-get-config': {
    id: 'unfinished-get-config',
    title: 'Get Unfinished Work Config',
    description: 'Retrieves the current configuration for the unfinished work scanner.',
    rpcIds: ['unfinished:get-config'],
    componentPaths: [],
    testIds: [
      'TestGetUnfinishedWorkConfig_ReturnsConfig',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'unfinished-get-worktree-diff': {
    id: 'unfinished-get-worktree-diff',
    title: 'Get Worktree Diff',
    description: 'Returns the full git diff for a worktree with uncommitted changes.',
    rpcIds: ['unfinished:get-worktree-diff'],
    componentPaths: [],
    testIds: [],
    status: 'experimental',
    since: '1.0.0',
  },
  'unfinished-scan': {
    id: 'unfinished-scan',
    title: 'Scan Unfinished Work',
    description: 'Triggers an immediate scan of all worktrees to refresh unfinished work state.',
    rpcIds: ['unfinished:scan'],
    componentPaths: [],
    testIds: [
      'unfinished-work > Refresh button triggers a scan RPC',
      'unfinished-work > scan completed event updates last-scanned timestamp',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'unfinished-snooze': {
    id: 'unfinished-snooze',
    title: 'Snooze Worktree',
    description: 'Temporarily snoozes a worktree so it is hidden from unfinished work for a set duration.',
    rpcIds: ['unfinished:snooze'],
    componentPaths: [],
    testIds: [
      'TestStateStore_SnoozeWorktree',
      'TestStateStore_IsSnoozeActive',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'unfinished-undismiss': {
    id: 'unfinished-undismiss',
    title: 'Undismiss Worktree',
    description: 'Restores a previously dismissed worktree back into the unfinished work list.',
    rpcIds: ['unfinished:undismiss'],
    componentPaths: [],
    testIds: [
      'TestUndismissWorktree_NoOpOnUnknown',
    ],
    status: 'stable',
    since: '1.0.0',
  },
  'unfinished-update-config': {
    id: 'unfinished-update-config',
    title: 'Update Unfinished Work Config',
    description: 'Updates the configuration for the unfinished work scanner, such as scan intervals and exclusions.',
    rpcIds: ['unfinished:update-config'],
    componentPaths: [],
    testIds: [
      'TestUpdateUnfinishedWorkConfig_NilConfigReturnsError',
      'TestUpdateUnfinishedWorkConfig_ValidConfig',
    ],
    status: 'stable',
    since: '1.0.0',
  },
} as const satisfies Record<string, Feature>;
