// Code generated by ent, DO NOT EDIT.

package classificationanalytics

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldID, id))
}

// AnalyticsID applies equality check predicate on the "analytics_id" field. It's identical to AnalyticsIDEQ.
func AnalyticsID(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldAnalyticsID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldSessionID, v))
}

// ToolName applies equality check predicate on the "tool_name" field. It's identical to ToolNameEQ.
func ToolName(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldToolName, v))
}

// CommandPreview applies equality check predicate on the "command_preview" field. It's identical to CommandPreviewEQ.
func CommandPreview(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCommandPreview, v))
}

// Cwd applies equality check predicate on the "cwd" field. It's identical to CwdEQ.
func Cwd(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCwd, v))
}

// Decision applies equality check predicate on the "decision" field. It's identical to DecisionEQ.
func Decision(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldDecision, v))
}

// RiskLevel applies equality check predicate on the "risk_level" field. It's identical to RiskLevelEQ.
func RiskLevel(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldRiskLevel, v))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldRuleID, v))
}

// RuleName applies equality check predicate on the "rule_name" field. It's identical to RuleNameEQ.
func RuleName(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldRuleName, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldReason, v))
}

// Alternative applies equality check predicate on the "alternative" field. It's identical to AlternativeEQ.
func Alternative(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldAlternative, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldDurationMs, v))
}

// ApprovalID applies equality check predicate on the "approval_id" field. It's identical to ApprovalIDEQ.
func ApprovalID(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldApprovalID, v))
}

// CommandProgram applies equality check predicate on the "command_program" field. It's identical to CommandProgramEQ.
func CommandProgram(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCommandProgram, v))
}

// CommandCategory applies equality check predicate on the "command_category" field. It's identical to CommandCategoryEQ.
func CommandCategory(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCommandCategory, v))
}

// CommandSubcategory applies equality check predicate on the "command_subcategory" field. It's identical to CommandSubcategoryEQ.
func CommandSubcategory(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCommandSubcategory, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCreatedAt, v))
}

// AnalyticsIDEQ applies the EQ predicate on the "analytics_id" field.
func AnalyticsIDEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldAnalyticsID, v))
}

// AnalyticsIDNEQ applies the NEQ predicate on the "analytics_id" field.
func AnalyticsIDNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldAnalyticsID, v))
}

// AnalyticsIDIn applies the In predicate on the "analytics_id" field.
func AnalyticsIDIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldAnalyticsID, vs...))
}

// AnalyticsIDNotIn applies the NotIn predicate on the "analytics_id" field.
func AnalyticsIDNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldAnalyticsID, vs...))
}

// AnalyticsIDGT applies the GT predicate on the "analytics_id" field.
func AnalyticsIDGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldAnalyticsID, v))
}

// AnalyticsIDGTE applies the GTE predicate on the "analytics_id" field.
func AnalyticsIDGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldAnalyticsID, v))
}

// AnalyticsIDLT applies the LT predicate on the "analytics_id" field.
func AnalyticsIDLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldAnalyticsID, v))
}

// AnalyticsIDLTE applies the LTE predicate on the "analytics_id" field.
func AnalyticsIDLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldAnalyticsID, v))
}

// AnalyticsIDContains applies the Contains predicate on the "analytics_id" field.
func AnalyticsIDContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldAnalyticsID, v))
}

// AnalyticsIDHasPrefix applies the HasPrefix predicate on the "analytics_id" field.
func AnalyticsIDHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldAnalyticsID, v))
}

// AnalyticsIDHasSuffix applies the HasSuffix predicate on the "analytics_id" field.
func AnalyticsIDHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldAnalyticsID, v))
}

// AnalyticsIDEqualFold applies the EqualFold predicate on the "analytics_id" field.
func AnalyticsIDEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldAnalyticsID, v))
}

// AnalyticsIDContainsFold applies the ContainsFold predicate on the "analytics_id" field.
func AnalyticsIDContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldAnalyticsID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDIsNil applies the IsNil predicate on the "session_id" field.
func SessionIDIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldSessionID))
}

// SessionIDNotNil applies the NotNil predicate on the "session_id" field.
func SessionIDNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldSessionID))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldSessionID, v))
}

// ToolNameEQ applies the EQ predicate on the "tool_name" field.
func ToolNameEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldToolName, v))
}

// ToolNameNEQ applies the NEQ predicate on the "tool_name" field.
func ToolNameNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldToolName, v))
}

// ToolNameIn applies the In predicate on the "tool_name" field.
func ToolNameIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldToolName, vs...))
}

// ToolNameNotIn applies the NotIn predicate on the "tool_name" field.
func ToolNameNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldToolName, vs...))
}

// ToolNameGT applies the GT predicate on the "tool_name" field.
func ToolNameGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldToolName, v))
}

// ToolNameGTE applies the GTE predicate on the "tool_name" field.
func ToolNameGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldToolName, v))
}

// ToolNameLT applies the LT predicate on the "tool_name" field.
func ToolNameLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldToolName, v))
}

// ToolNameLTE applies the LTE predicate on the "tool_name" field.
func ToolNameLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldToolName, v))
}

// ToolNameContains applies the Contains predicate on the "tool_name" field.
func ToolNameContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldToolName, v))
}

// ToolNameHasPrefix applies the HasPrefix predicate on the "tool_name" field.
func ToolNameHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldToolName, v))
}

// ToolNameHasSuffix applies the HasSuffix predicate on the "tool_name" field.
func ToolNameHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldToolName, v))
}

// ToolNameEqualFold applies the EqualFold predicate on the "tool_name" field.
func ToolNameEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldToolName, v))
}

// ToolNameContainsFold applies the ContainsFold predicate on the "tool_name" field.
func ToolNameContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldToolName, v))
}

// CommandPreviewEQ applies the EQ predicate on the "command_preview" field.
func CommandPreviewEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCommandPreview, v))
}

// CommandPreviewNEQ applies the NEQ predicate on the "command_preview" field.
func CommandPreviewNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldCommandPreview, v))
}

// CommandPreviewIn applies the In predicate on the "command_preview" field.
func CommandPreviewIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldCommandPreview, vs...))
}

// CommandPreviewNotIn applies the NotIn predicate on the "command_preview" field.
func CommandPreviewNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldCommandPreview, vs...))
}

// CommandPreviewGT applies the GT predicate on the "command_preview" field.
func CommandPreviewGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldCommandPreview, v))
}

// CommandPreviewGTE applies the GTE predicate on the "command_preview" field.
func CommandPreviewGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldCommandPreview, v))
}

// CommandPreviewLT applies the LT predicate on the "command_preview" field.
func CommandPreviewLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldCommandPreview, v))
}

// CommandPreviewLTE applies the LTE predicate on the "command_preview" field.
func CommandPreviewLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldCommandPreview, v))
}

// CommandPreviewContains applies the Contains predicate on the "command_preview" field.
func CommandPreviewContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldCommandPreview, v))
}

// CommandPreviewHasPrefix applies the HasPrefix predicate on the "command_preview" field.
func CommandPreviewHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldCommandPreview, v))
}

// CommandPreviewHasSuffix applies the HasSuffix predicate on the "command_preview" field.
func CommandPreviewHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldCommandPreview, v))
}

// CommandPreviewIsNil applies the IsNil predicate on the "command_preview" field.
func CommandPreviewIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldCommandPreview))
}

// CommandPreviewNotNil applies the NotNil predicate on the "command_preview" field.
func CommandPreviewNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldCommandPreview))
}

// CommandPreviewEqualFold applies the EqualFold predicate on the "command_preview" field.
func CommandPreviewEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldCommandPreview, v))
}

// CommandPreviewContainsFold applies the ContainsFold predicate on the "command_preview" field.
func CommandPreviewContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldCommandPreview, v))
}

// CwdEQ applies the EQ predicate on the "cwd" field.
func CwdEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCwd, v))
}

// CwdNEQ applies the NEQ predicate on the "cwd" field.
func CwdNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldCwd, v))
}

// CwdIn applies the In predicate on the "cwd" field.
func CwdIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldCwd, vs...))
}

// CwdNotIn applies the NotIn predicate on the "cwd" field.
func CwdNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldCwd, vs...))
}

// CwdGT applies the GT predicate on the "cwd" field.
func CwdGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldCwd, v))
}

// CwdGTE applies the GTE predicate on the "cwd" field.
func CwdGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldCwd, v))
}

// CwdLT applies the LT predicate on the "cwd" field.
func CwdLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldCwd, v))
}

// CwdLTE applies the LTE predicate on the "cwd" field.
func CwdLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldCwd, v))
}

// CwdContains applies the Contains predicate on the "cwd" field.
func CwdContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldCwd, v))
}

// CwdHasPrefix applies the HasPrefix predicate on the "cwd" field.
func CwdHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldCwd, v))
}

// CwdHasSuffix applies the HasSuffix predicate on the "cwd" field.
func CwdHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldCwd, v))
}

// CwdIsNil applies the IsNil predicate on the "cwd" field.
func CwdIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldCwd))
}

// CwdNotNil applies the NotNil predicate on the "cwd" field.
func CwdNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldCwd))
}

// CwdEqualFold applies the EqualFold predicate on the "cwd" field.
func CwdEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldCwd, v))
}

// CwdContainsFold applies the ContainsFold predicate on the "cwd" field.
func CwdContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldCwd, v))
}

// DecisionEQ applies the EQ predicate on the "decision" field.
func DecisionEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldDecision, v))
}

// DecisionNEQ applies the NEQ predicate on the "decision" field.
func DecisionNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldDecision, v))
}

// DecisionIn applies the In predicate on the "decision" field.
func DecisionIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldDecision, vs...))
}

// DecisionNotIn applies the NotIn predicate on the "decision" field.
func DecisionNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldDecision, vs...))
}

// DecisionGT applies the GT predicate on the "decision" field.
func DecisionGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldDecision, v))
}

// DecisionGTE applies the GTE predicate on the "decision" field.
func DecisionGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldDecision, v))
}

// DecisionLT applies the LT predicate on the "decision" field.
func DecisionLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldDecision, v))
}

// DecisionLTE applies the LTE predicate on the "decision" field.
func DecisionLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldDecision, v))
}

// DecisionContains applies the Contains predicate on the "decision" field.
func DecisionContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldDecision, v))
}

// DecisionHasPrefix applies the HasPrefix predicate on the "decision" field.
func DecisionHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldDecision, v))
}

// DecisionHasSuffix applies the HasSuffix predicate on the "decision" field.
func DecisionHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldDecision, v))
}

// DecisionEqualFold applies the EqualFold predicate on the "decision" field.
func DecisionEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldDecision, v))
}

// DecisionContainsFold applies the ContainsFold predicate on the "decision" field.
func DecisionContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldDecision, v))
}

// RiskLevelEQ applies the EQ predicate on the "risk_level" field.
func RiskLevelEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldRiskLevel, v))
}

// RiskLevelNEQ applies the NEQ predicate on the "risk_level" field.
func RiskLevelNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldRiskLevel, v))
}

// RiskLevelIn applies the In predicate on the "risk_level" field.
func RiskLevelIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldRiskLevel, vs...))
}

// RiskLevelNotIn applies the NotIn predicate on the "risk_level" field.
func RiskLevelNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldRiskLevel, vs...))
}

// RiskLevelGT applies the GT predicate on the "risk_level" field.
func RiskLevelGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldRiskLevel, v))
}

// RiskLevelGTE applies the GTE predicate on the "risk_level" field.
func RiskLevelGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldRiskLevel, v))
}

// RiskLevelLT applies the LT predicate on the "risk_level" field.
func RiskLevelLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldRiskLevel, v))
}

// RiskLevelLTE applies the LTE predicate on the "risk_level" field.
func RiskLevelLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldRiskLevel, v))
}

// RiskLevelContains applies the Contains predicate on the "risk_level" field.
func RiskLevelContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldRiskLevel, v))
}

// RiskLevelHasPrefix applies the HasPrefix predicate on the "risk_level" field.
func RiskLevelHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldRiskLevel, v))
}

// RiskLevelHasSuffix applies the HasSuffix predicate on the "risk_level" field.
func RiskLevelHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldRiskLevel, v))
}

// RiskLevelEqualFold applies the EqualFold predicate on the "risk_level" field.
func RiskLevelEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldRiskLevel, v))
}

// RiskLevelContainsFold applies the ContainsFold predicate on the "risk_level" field.
func RiskLevelContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldRiskLevel, v))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldRuleID, vs...))
}

// RuleIDGT applies the GT predicate on the "rule_id" field.
func RuleIDGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldRuleID, v))
}

// RuleIDGTE applies the GTE predicate on the "rule_id" field.
func RuleIDGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldRuleID, v))
}

// RuleIDLT applies the LT predicate on the "rule_id" field.
func RuleIDLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldRuleID, v))
}

// RuleIDLTE applies the LTE predicate on the "rule_id" field.
func RuleIDLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldRuleID, v))
}

// RuleIDContains applies the Contains predicate on the "rule_id" field.
func RuleIDContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldRuleID, v))
}

// RuleIDHasPrefix applies the HasPrefix predicate on the "rule_id" field.
func RuleIDHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldRuleID, v))
}

// RuleIDHasSuffix applies the HasSuffix predicate on the "rule_id" field.
func RuleIDHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldRuleID, v))
}

// RuleIDIsNil applies the IsNil predicate on the "rule_id" field.
func RuleIDIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldRuleID))
}

// RuleIDNotNil applies the NotNil predicate on the "rule_id" field.
func RuleIDNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldRuleID))
}

// RuleIDEqualFold applies the EqualFold predicate on the "rule_id" field.
func RuleIDEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldRuleID, v))
}

// RuleIDContainsFold applies the ContainsFold predicate on the "rule_id" field.
func RuleIDContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldRuleID, v))
}

// RuleNameEQ applies the EQ predicate on the "rule_name" field.
func RuleNameEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldRuleName, v))
}

// RuleNameNEQ applies the NEQ predicate on the "rule_name" field.
func RuleNameNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldRuleName, v))
}

// RuleNameIn applies the In predicate on the "rule_name" field.
func RuleNameIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldRuleName, vs...))
}

// RuleNameNotIn applies the NotIn predicate on the "rule_name" field.
func RuleNameNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldRuleName, vs...))
}

// RuleNameGT applies the GT predicate on the "rule_name" field.
func RuleNameGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldRuleName, v))
}

// RuleNameGTE applies the GTE predicate on the "rule_name" field.
func RuleNameGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldRuleName, v))
}

// RuleNameLT applies the LT predicate on the "rule_name" field.
func RuleNameLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldRuleName, v))
}

// RuleNameLTE applies the LTE predicate on the "rule_name" field.
func RuleNameLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldRuleName, v))
}

// RuleNameContains applies the Contains predicate on the "rule_name" field.
func RuleNameContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldRuleName, v))
}

// RuleNameHasPrefix applies the HasPrefix predicate on the "rule_name" field.
func RuleNameHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldRuleName, v))
}

// RuleNameHasSuffix applies the HasSuffix predicate on the "rule_name" field.
func RuleNameHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldRuleName, v))
}

// RuleNameIsNil applies the IsNil predicate on the "rule_name" field.
func RuleNameIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldRuleName))
}

// RuleNameNotNil applies the NotNil predicate on the "rule_name" field.
func RuleNameNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldRuleName))
}

// RuleNameEqualFold applies the EqualFold predicate on the "rule_name" field.
func RuleNameEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldRuleName, v))
}

// RuleNameContainsFold applies the ContainsFold predicate on the "rule_name" field.
func RuleNameContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldRuleName, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldReason, v))
}

// AlternativeEQ applies the EQ predicate on the "alternative" field.
func AlternativeEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldAlternative, v))
}

// AlternativeNEQ applies the NEQ predicate on the "alternative" field.
func AlternativeNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldAlternative, v))
}

// AlternativeIn applies the In predicate on the "alternative" field.
func AlternativeIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldAlternative, vs...))
}

// AlternativeNotIn applies the NotIn predicate on the "alternative" field.
func AlternativeNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldAlternative, vs...))
}

// AlternativeGT applies the GT predicate on the "alternative" field.
func AlternativeGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldAlternative, v))
}

// AlternativeGTE applies the GTE predicate on the "alternative" field.
func AlternativeGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldAlternative, v))
}

// AlternativeLT applies the LT predicate on the "alternative" field.
func AlternativeLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldAlternative, v))
}

// AlternativeLTE applies the LTE predicate on the "alternative" field.
func AlternativeLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldAlternative, v))
}

// AlternativeContains applies the Contains predicate on the "alternative" field.
func AlternativeContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldAlternative, v))
}

// AlternativeHasPrefix applies the HasPrefix predicate on the "alternative" field.
func AlternativeHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldAlternative, v))
}

// AlternativeHasSuffix applies the HasSuffix predicate on the "alternative" field.
func AlternativeHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldAlternative, v))
}

// AlternativeIsNil applies the IsNil predicate on the "alternative" field.
func AlternativeIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldAlternative))
}

// AlternativeNotNil applies the NotNil predicate on the "alternative" field.
func AlternativeNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldAlternative))
}

// AlternativeEqualFold applies the EqualFold predicate on the "alternative" field.
func AlternativeEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldAlternative, v))
}

// AlternativeContainsFold applies the ContainsFold predicate on the "alternative" field.
func AlternativeContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldAlternative, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldDurationMs, v))
}

// ApprovalIDEQ applies the EQ predicate on the "approval_id" field.
func ApprovalIDEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldApprovalID, v))
}

// ApprovalIDNEQ applies the NEQ predicate on the "approval_id" field.
func ApprovalIDNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldApprovalID, v))
}

// ApprovalIDIn applies the In predicate on the "approval_id" field.
func ApprovalIDIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldApprovalID, vs...))
}

// ApprovalIDNotIn applies the NotIn predicate on the "approval_id" field.
func ApprovalIDNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldApprovalID, vs...))
}

// ApprovalIDGT applies the GT predicate on the "approval_id" field.
func ApprovalIDGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldApprovalID, v))
}

// ApprovalIDGTE applies the GTE predicate on the "approval_id" field.
func ApprovalIDGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldApprovalID, v))
}

// ApprovalIDLT applies the LT predicate on the "approval_id" field.
func ApprovalIDLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldApprovalID, v))
}

// ApprovalIDLTE applies the LTE predicate on the "approval_id" field.
func ApprovalIDLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldApprovalID, v))
}

// ApprovalIDContains applies the Contains predicate on the "approval_id" field.
func ApprovalIDContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldApprovalID, v))
}

// ApprovalIDHasPrefix applies the HasPrefix predicate on the "approval_id" field.
func ApprovalIDHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldApprovalID, v))
}

// ApprovalIDHasSuffix applies the HasSuffix predicate on the "approval_id" field.
func ApprovalIDHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldApprovalID, v))
}

// ApprovalIDIsNil applies the IsNil predicate on the "approval_id" field.
func ApprovalIDIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldApprovalID))
}

// ApprovalIDNotNil applies the NotNil predicate on the "approval_id" field.
func ApprovalIDNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldApprovalID))
}

// ApprovalIDEqualFold applies the EqualFold predicate on the "approval_id" field.
func ApprovalIDEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldApprovalID, v))
}

// ApprovalIDContainsFold applies the ContainsFold predicate on the "approval_id" field.
func ApprovalIDContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldApprovalID, v))
}

// CommandProgramEQ applies the EQ predicate on the "command_program" field.
func CommandProgramEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCommandProgram, v))
}

// CommandProgramNEQ applies the NEQ predicate on the "command_program" field.
func CommandProgramNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldCommandProgram, v))
}

// CommandProgramIn applies the In predicate on the "command_program" field.
func CommandProgramIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldCommandProgram, vs...))
}

// CommandProgramNotIn applies the NotIn predicate on the "command_program" field.
func CommandProgramNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldCommandProgram, vs...))
}

// CommandProgramGT applies the GT predicate on the "command_program" field.
func CommandProgramGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldCommandProgram, v))
}

// CommandProgramGTE applies the GTE predicate on the "command_program" field.
func CommandProgramGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldCommandProgram, v))
}

// CommandProgramLT applies the LT predicate on the "command_program" field.
func CommandProgramLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldCommandProgram, v))
}

// CommandProgramLTE applies the LTE predicate on the "command_program" field.
func CommandProgramLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldCommandProgram, v))
}

// CommandProgramContains applies the Contains predicate on the "command_program" field.
func CommandProgramContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldCommandProgram, v))
}

// CommandProgramHasPrefix applies the HasPrefix predicate on the "command_program" field.
func CommandProgramHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldCommandProgram, v))
}

// CommandProgramHasSuffix applies the HasSuffix predicate on the "command_program" field.
func CommandProgramHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldCommandProgram, v))
}

// CommandProgramIsNil applies the IsNil predicate on the "command_program" field.
func CommandProgramIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldCommandProgram))
}

// CommandProgramNotNil applies the NotNil predicate on the "command_program" field.
func CommandProgramNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldCommandProgram))
}

// CommandProgramEqualFold applies the EqualFold predicate on the "command_program" field.
func CommandProgramEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldCommandProgram, v))
}

// CommandProgramContainsFold applies the ContainsFold predicate on the "command_program" field.
func CommandProgramContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldCommandProgram, v))
}

// CommandCategoryEQ applies the EQ predicate on the "command_category" field.
func CommandCategoryEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCommandCategory, v))
}

// CommandCategoryNEQ applies the NEQ predicate on the "command_category" field.
func CommandCategoryNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldCommandCategory, v))
}

// CommandCategoryIn applies the In predicate on the "command_category" field.
func CommandCategoryIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldCommandCategory, vs...))
}

// CommandCategoryNotIn applies the NotIn predicate on the "command_category" field.
func CommandCategoryNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldCommandCategory, vs...))
}

// CommandCategoryGT applies the GT predicate on the "command_category" field.
func CommandCategoryGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldCommandCategory, v))
}

// CommandCategoryGTE applies the GTE predicate on the "command_category" field.
func CommandCategoryGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldCommandCategory, v))
}

// CommandCategoryLT applies the LT predicate on the "command_category" field.
func CommandCategoryLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldCommandCategory, v))
}

// CommandCategoryLTE applies the LTE predicate on the "command_category" field.
func CommandCategoryLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldCommandCategory, v))
}

// CommandCategoryContains applies the Contains predicate on the "command_category" field.
func CommandCategoryContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldCommandCategory, v))
}

// CommandCategoryHasPrefix applies the HasPrefix predicate on the "command_category" field.
func CommandCategoryHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldCommandCategory, v))
}

// CommandCategoryHasSuffix applies the HasSuffix predicate on the "command_category" field.
func CommandCategoryHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldCommandCategory, v))
}

// CommandCategoryIsNil applies the IsNil predicate on the "command_category" field.
func CommandCategoryIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldCommandCategory))
}

// CommandCategoryNotNil applies the NotNil predicate on the "command_category" field.
func CommandCategoryNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldCommandCategory))
}

// CommandCategoryEqualFold applies the EqualFold predicate on the "command_category" field.
func CommandCategoryEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldCommandCategory, v))
}

// CommandCategoryContainsFold applies the ContainsFold predicate on the "command_category" field.
func CommandCategoryContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldCommandCategory, v))
}

// CommandSubcategoryEQ applies the EQ predicate on the "command_subcategory" field.
func CommandSubcategoryEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCommandSubcategory, v))
}

// CommandSubcategoryNEQ applies the NEQ predicate on the "command_subcategory" field.
func CommandSubcategoryNEQ(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldCommandSubcategory, v))
}

// CommandSubcategoryIn applies the In predicate on the "command_subcategory" field.
func CommandSubcategoryIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldCommandSubcategory, vs...))
}

// CommandSubcategoryNotIn applies the NotIn predicate on the "command_subcategory" field.
func CommandSubcategoryNotIn(vs ...string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldCommandSubcategory, vs...))
}

// CommandSubcategoryGT applies the GT predicate on the "command_subcategory" field.
func CommandSubcategoryGT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldCommandSubcategory, v))
}

// CommandSubcategoryGTE applies the GTE predicate on the "command_subcategory" field.
func CommandSubcategoryGTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldCommandSubcategory, v))
}

// CommandSubcategoryLT applies the LT predicate on the "command_subcategory" field.
func CommandSubcategoryLT(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldCommandSubcategory, v))
}

// CommandSubcategoryLTE applies the LTE predicate on the "command_subcategory" field.
func CommandSubcategoryLTE(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldCommandSubcategory, v))
}

// CommandSubcategoryContains applies the Contains predicate on the "command_subcategory" field.
func CommandSubcategoryContains(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContains(FieldCommandSubcategory, v))
}

// CommandSubcategoryHasPrefix applies the HasPrefix predicate on the "command_subcategory" field.
func CommandSubcategoryHasPrefix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasPrefix(FieldCommandSubcategory, v))
}

// CommandSubcategoryHasSuffix applies the HasSuffix predicate on the "command_subcategory" field.
func CommandSubcategoryHasSuffix(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldHasSuffix(FieldCommandSubcategory, v))
}

// CommandSubcategoryIsNil applies the IsNil predicate on the "command_subcategory" field.
func CommandSubcategoryIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldCommandSubcategory))
}

// CommandSubcategoryNotNil applies the NotNil predicate on the "command_subcategory" field.
func CommandSubcategoryNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldCommandSubcategory))
}

// CommandSubcategoryEqualFold applies the EqualFold predicate on the "command_subcategory" field.
func CommandSubcategoryEqualFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEqualFold(FieldCommandSubcategory, v))
}

// CommandSubcategoryContainsFold applies the ContainsFold predicate on the "command_subcategory" field.
func CommandSubcategoryContainsFold(v string) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldContainsFold(FieldCommandSubcategory, v))
}

// PythonImportsIsNil applies the IsNil predicate on the "python_imports" field.
func PythonImportsIsNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIsNull(FieldPythonImports))
}

// PythonImportsNotNil applies the NotNil predicate on the "python_imports" field.
func PythonImportsNotNil() predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotNull(FieldPythonImports))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClassificationAnalytics) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClassificationAnalytics) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClassificationAnalytics) predicate.ClassificationAnalytics {
	return predicate.ClassificationAnalytics(sql.NotPredicates(p))
}
