// Code generated by ent, DO NOT EDIT.

package backlogitemdependency

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the backlogitemdependency type in the database.
	Label = "backlog_item_dependency"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlockerID holds the string denoting the blocker_id field in the database.
	FieldBlockerID = "blocker_id"
	// FieldBlockedID holds the string denoting the blocked_id field in the database.
	FieldBlockedID = "blocked_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeBlocker holds the string denoting the blocker edge name in mutations.
	EdgeBlocker = "blocker"
	// EdgeBlocked holds the string denoting the blocked edge name in mutations.
	EdgeBlocked = "blocked"
	// Table holds the table name of the backlogitemdependency in the database.
	Table = "backlog_item_dependencies"
	// BlockerTable is the table that holds the blocker relation/edge.
	BlockerTable = "backlog_item_dependencies"
	// BlockerInverseTable is the table name for the BacklogItem entity.
	// It exists in this package in order to avoid circular dependency with the "backlogitem" package.
	BlockerInverseTable = "backlog_items"
	// BlockerColumn is the table column denoting the blocker relation/edge.
	BlockerColumn = "blocker_id"
	// BlockedTable is the table that holds the blocked relation/edge.
	BlockedTable = "backlog_item_dependencies"
	// BlockedInverseTable is the table name for the BacklogItem entity.
	// It exists in this package in order to avoid circular dependency with the "backlogitem" package.
	BlockedInverseTable = "backlog_items"
	// BlockedColumn is the table column denoting the blocked relation/edge.
	BlockedColumn = "blocked_id"
)

// Columns holds all SQL columns for backlogitemdependency fields.
var Columns = []string{
	FieldID,
	FieldBlockerID,
	FieldBlockedID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the BacklogItemDependency queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBlockerID orders the results by the blocker_id field.
func ByBlockerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockerID, opts...).ToFunc()
}

// ByBlockedID orders the results by the blocked_id field.
func ByBlockedID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockedID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByBlockerField orders the results by blocker field.
func ByBlockerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBlockerStep(), sql.OrderByField(field, opts...))
	}
}

// ByBlockedField orders the results by blocked field.
func ByBlockedField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBlockedStep(), sql.OrderByField(field, opts...))
	}
}
func newBlockerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BlockerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BlockerTable, BlockerColumn),
	)
}
func newBlockedStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BlockedInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BlockedTable, BlockedColumn),
	)
}
