// Code generated by ent, DO NOT EDIT.

package analyticsevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContainsFold(FieldID, id))
}

// EventName applies equality check predicate on the "event_name" field. It's identical to EventNameEQ.
func EventName(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldEventName, v))
}

// EventCategory applies equality check predicate on the "event_category" field. It's identical to EventCategoryEQ.
func EventCategory(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldEventCategory, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldSessionID, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldDurationMs, v))
}

// Page applies equality check predicate on the "page" field. It's identical to PageEQ.
func Page(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldPage, v))
}

// Component applies equality check predicate on the "component" field. It's identical to ComponentEQ.
func Component(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldComponent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// EventNameEQ applies the EQ predicate on the "event_name" field.
func EventNameEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldEventName, v))
}

// EventNameNEQ applies the NEQ predicate on the "event_name" field.
func EventNameNEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldEventName, v))
}

// EventNameIn applies the In predicate on the "event_name" field.
func EventNameIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldEventName, vs...))
}

// EventNameNotIn applies the NotIn predicate on the "event_name" field.
func EventNameNotIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldEventName, vs...))
}

// EventNameGT applies the GT predicate on the "event_name" field.
func EventNameGT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldEventName, v))
}

// EventNameGTE applies the GTE predicate on the "event_name" field.
func EventNameGTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldEventName, v))
}

// EventNameLT applies the LT predicate on the "event_name" field.
func EventNameLT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldEventName, v))
}

// EventNameLTE applies the LTE predicate on the "event_name" field.
func EventNameLTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldEventName, v))
}

// EventNameContains applies the Contains predicate on the "event_name" field.
func EventNameContains(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContains(FieldEventName, v))
}

// EventNameHasPrefix applies the HasPrefix predicate on the "event_name" field.
func EventNameHasPrefix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasPrefix(FieldEventName, v))
}

// EventNameHasSuffix applies the HasSuffix predicate on the "event_name" field.
func EventNameHasSuffix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasSuffix(FieldEventName, v))
}

// EventNameEqualFold applies the EqualFold predicate on the "event_name" field.
func EventNameEqualFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEqualFold(FieldEventName, v))
}

// EventNameContainsFold applies the ContainsFold predicate on the "event_name" field.
func EventNameContainsFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContainsFold(FieldEventName, v))
}

// EventCategoryEQ applies the EQ predicate on the "event_category" field.
func EventCategoryEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldEventCategory, v))
}

// EventCategoryNEQ applies the NEQ predicate on the "event_category" field.
func EventCategoryNEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldEventCategory, v))
}

// EventCategoryIn applies the In predicate on the "event_category" field.
func EventCategoryIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldEventCategory, vs...))
}

// EventCategoryNotIn applies the NotIn predicate on the "event_category" field.
func EventCategoryNotIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldEventCategory, vs...))
}

// EventCategoryGT applies the GT predicate on the "event_category" field.
func EventCategoryGT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldEventCategory, v))
}

// EventCategoryGTE applies the GTE predicate on the "event_category" field.
func EventCategoryGTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldEventCategory, v))
}

// EventCategoryLT applies the LT predicate on the "event_category" field.
func EventCategoryLT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldEventCategory, v))
}

// EventCategoryLTE applies the LTE predicate on the "event_category" field.
func EventCategoryLTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldEventCategory, v))
}

// EventCategoryContains applies the Contains predicate on the "event_category" field.
func EventCategoryContains(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContains(FieldEventCategory, v))
}

// EventCategoryHasPrefix applies the HasPrefix predicate on the "event_category" field.
func EventCategoryHasPrefix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasPrefix(FieldEventCategory, v))
}

// EventCategoryHasSuffix applies the HasSuffix predicate on the "event_category" field.
func EventCategoryHasSuffix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasSuffix(FieldEventCategory, v))
}

// EventCategoryEqualFold applies the EqualFold predicate on the "event_category" field.
func EventCategoryEqualFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEqualFold(FieldEventCategory, v))
}

// EventCategoryContainsFold applies the ContainsFold predicate on the "event_category" field.
func EventCategoryContainsFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContainsFold(FieldEventCategory, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDIsNil applies the IsNil predicate on the "session_id" field.
func SessionIDIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldSessionID))
}

// SessionIDNotNil applies the NotNil predicate on the "session_id" field.
func SessionIDNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldSessionID))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContainsFold(FieldSessionID, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldDurationMs))
}

// PageEQ applies the EQ predicate on the "page" field.
func PageEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldPage, v))
}

// PageNEQ applies the NEQ predicate on the "page" field.
func PageNEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldPage, v))
}

// PageIn applies the In predicate on the "page" field.
func PageIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldPage, vs...))
}

// PageNotIn applies the NotIn predicate on the "page" field.
func PageNotIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldPage, vs...))
}

// PageGT applies the GT predicate on the "page" field.
func PageGT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldPage, v))
}

// PageGTE applies the GTE predicate on the "page" field.
func PageGTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldPage, v))
}

// PageLT applies the LT predicate on the "page" field.
func PageLT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldPage, v))
}

// PageLTE applies the LTE predicate on the "page" field.
func PageLTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldPage, v))
}

// PageContains applies the Contains predicate on the "page" field.
func PageContains(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContains(FieldPage, v))
}

// PageHasPrefix applies the HasPrefix predicate on the "page" field.
func PageHasPrefix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasPrefix(FieldPage, v))
}

// PageHasSuffix applies the HasSuffix predicate on the "page" field.
func PageHasSuffix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasSuffix(FieldPage, v))
}

// PageIsNil applies the IsNil predicate on the "page" field.
func PageIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldPage))
}

// PageNotNil applies the NotNil predicate on the "page" field.
func PageNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldPage))
}

// PageEqualFold applies the EqualFold predicate on the "page" field.
func PageEqualFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEqualFold(FieldPage, v))
}

// PageContainsFold applies the ContainsFold predicate on the "page" field.
func PageContainsFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContainsFold(FieldPage, v))
}

// ComponentEQ applies the EQ predicate on the "component" field.
func ComponentEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldComponent, v))
}

// ComponentNEQ applies the NEQ predicate on the "component" field.
func ComponentNEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldComponent, v))
}

// ComponentIn applies the In predicate on the "component" field.
func ComponentIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldComponent, vs...))
}

// ComponentNotIn applies the NotIn predicate on the "component" field.
func ComponentNotIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldComponent, vs...))
}

// ComponentGT applies the GT predicate on the "component" field.
func ComponentGT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldComponent, v))
}

// ComponentGTE applies the GTE predicate on the "component" field.
func ComponentGTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldComponent, v))
}

// ComponentLT applies the LT predicate on the "component" field.
func ComponentLT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldComponent, v))
}

// ComponentLTE applies the LTE predicate on the "component" field.
func ComponentLTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldComponent, v))
}

// ComponentContains applies the Contains predicate on the "component" field.
func ComponentContains(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContains(FieldComponent, v))
}

// ComponentHasPrefix applies the HasPrefix predicate on the "component" field.
func ComponentHasPrefix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasPrefix(FieldComponent, v))
}

// ComponentHasSuffix applies the HasSuffix predicate on the "component" field.
func ComponentHasSuffix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasSuffix(FieldComponent, v))
}

// ComponentIsNil applies the IsNil predicate on the "component" field.
func ComponentIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldComponent))
}

// ComponentNotNil applies the NotNil predicate on the "component" field.
func ComponentNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldComponent))
}

// ComponentEqualFold applies the EqualFold predicate on the "component" field.
func ComponentEqualFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEqualFold(FieldComponent, v))
}

// ComponentContainsFold applies the ContainsFold predicate on the "component" field.
func ComponentContainsFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContainsFold(FieldComponent, v))
}

// LabelsIsNil applies the IsNil predicate on the "labels" field.
func LabelsIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldLabels))
}

// LabelsNotNil applies the NotNil predicate on the "labels" field.
func LabelsNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldLabels))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnalyticsEvent) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnalyticsEvent) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnalyticsEvent) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.NotPredicates(p))
}
