// Code generated by ent, DO NOT EDIT.

package backlogactivitynote

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the backlogactivitynote type in the database.
	Label = "backlog_activity_note"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldItemID holds the string denoting the item_id field in the database.
	FieldItemID = "item_id"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldAuthorSessionUUID holds the string denoting the author_session_uuid field in the database.
	FieldAuthorSessionUUID = "author_session_uuid"
	// FieldAuthorSessionTitle holds the string denoting the author_session_title field in the database.
	FieldAuthorSessionTitle = "author_session_title"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeItem holds the string denoting the item edge name in mutations.
	EdgeItem = "item"
	// Table holds the table name of the backlogactivitynote in the database.
	Table = "backlog_activity_notes"
	// ItemTable is the table that holds the item relation/edge.
	ItemTable = "backlog_activity_notes"
	// ItemInverseTable is the table name for the BacklogItem entity.
	// It exists in this package in order to avoid circular dependency with the "backlogitem" package.
	ItemInverseTable = "backlog_items"
	// ItemColumn is the table column denoting the item relation/edge.
	ItemColumn = "item_id"
)

// Columns holds all SQL columns for backlogactivitynote fields.
var Columns = []string{
	FieldID,
	FieldItemID,
	FieldMessage,
	FieldAuthorSessionUUID,
	FieldAuthorSessionTitle,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the BacklogActivityNote queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByItemID orders the results by the item_id field.
func ByItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemID, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByAuthorSessionUUID orders the results by the author_session_uuid field.
func ByAuthorSessionUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorSessionUUID, opts...).ToFunc()
}

// ByAuthorSessionTitle orders the results by the author_session_title field.
func ByAuthorSessionTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorSessionTitle, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByItemField orders the results by item field.
func ByItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemStep(), sql.OrderByField(field, opts...))
	}
}
func newItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
	)
}
