// Code generated by ent, DO NOT EDIT.

package pipelinemode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tstapler/stapler-squad/session/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldID, id))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldSlug, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldDescription, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldEnabled, v))
}

// StatusCommandTemplate applies equality check predicate on the "status_command_template" field. It's identical to StatusCommandTemplateEQ.
func StatusCommandTemplate(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldStatusCommandTemplate, v))
}

// DoneCommandTemplate applies equality check predicate on the "done_command_template" field. It's identical to DoneCommandTemplateEQ.
func DoneCommandTemplate(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldDoneCommandTemplate, v))
}

// FailCommandTemplate applies equality check predicate on the "fail_command_template" field. It's identical to FailCommandTemplateEQ.
func FailCommandTemplate(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldFailCommandTemplate, v))
}

// ReviewCommandTemplate applies equality check predicate on the "review_command_template" field. It's identical to ReviewCommandTemplateEQ.
func ReviewCommandTemplate(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldReviewCommandTemplate, v))
}

// ShipCommandTemplate applies equality check predicate on the "ship_command_template" field. It's identical to ShipCommandTemplateEQ.
func ShipCommandTemplate(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldShipCommandTemplate, v))
}

// HelpCommandTemplate applies equality check predicate on the "help_command_template" field. It's identical to HelpCommandTemplateEQ.
func HelpCommandTemplate(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldHelpCommandTemplate, v))
}

// TriagePromptTemplate applies equality check predicate on the "triage_prompt_template" field. It's identical to TriagePromptTemplateEQ.
func TriagePromptTemplate(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldTriagePromptTemplate, v))
}

// ReviewPromptTemplate applies equality check predicate on the "review_prompt_template" field. It's identical to ReviewPromptTemplateEQ.
func ReviewPromptTemplate(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldReviewPromptTemplate, v))
}

// InitialPromptTemplate applies equality check predicate on the "initial_prompt_template" field. It's identical to InitialPromptTemplateEQ.
func InitialPromptTemplate(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldInitialPromptTemplate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldUpdatedAt, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldSlug, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldDescription, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldEnabled, v))
}

// StatusCommandTemplateEQ applies the EQ predicate on the "status_command_template" field.
func StatusCommandTemplateEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldStatusCommandTemplate, v))
}

// StatusCommandTemplateNEQ applies the NEQ predicate on the "status_command_template" field.
func StatusCommandTemplateNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldStatusCommandTemplate, v))
}

// StatusCommandTemplateIn applies the In predicate on the "status_command_template" field.
func StatusCommandTemplateIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldStatusCommandTemplate, vs...))
}

// StatusCommandTemplateNotIn applies the NotIn predicate on the "status_command_template" field.
func StatusCommandTemplateNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldStatusCommandTemplate, vs...))
}

// StatusCommandTemplateGT applies the GT predicate on the "status_command_template" field.
func StatusCommandTemplateGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldStatusCommandTemplate, v))
}

// StatusCommandTemplateGTE applies the GTE predicate on the "status_command_template" field.
func StatusCommandTemplateGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldStatusCommandTemplate, v))
}

// StatusCommandTemplateLT applies the LT predicate on the "status_command_template" field.
func StatusCommandTemplateLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldStatusCommandTemplate, v))
}

// StatusCommandTemplateLTE applies the LTE predicate on the "status_command_template" field.
func StatusCommandTemplateLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldStatusCommandTemplate, v))
}

// StatusCommandTemplateContains applies the Contains predicate on the "status_command_template" field.
func StatusCommandTemplateContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldStatusCommandTemplate, v))
}

// StatusCommandTemplateHasPrefix applies the HasPrefix predicate on the "status_command_template" field.
func StatusCommandTemplateHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldStatusCommandTemplate, v))
}

// StatusCommandTemplateHasSuffix applies the HasSuffix predicate on the "status_command_template" field.
func StatusCommandTemplateHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldStatusCommandTemplate, v))
}

// StatusCommandTemplateEqualFold applies the EqualFold predicate on the "status_command_template" field.
func StatusCommandTemplateEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldStatusCommandTemplate, v))
}

// StatusCommandTemplateContainsFold applies the ContainsFold predicate on the "status_command_template" field.
func StatusCommandTemplateContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldStatusCommandTemplate, v))
}

// DoneCommandTemplateEQ applies the EQ predicate on the "done_command_template" field.
func DoneCommandTemplateEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldDoneCommandTemplate, v))
}

// DoneCommandTemplateNEQ applies the NEQ predicate on the "done_command_template" field.
func DoneCommandTemplateNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldDoneCommandTemplate, v))
}

// DoneCommandTemplateIn applies the In predicate on the "done_command_template" field.
func DoneCommandTemplateIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldDoneCommandTemplate, vs...))
}

// DoneCommandTemplateNotIn applies the NotIn predicate on the "done_command_template" field.
func DoneCommandTemplateNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldDoneCommandTemplate, vs...))
}

// DoneCommandTemplateGT applies the GT predicate on the "done_command_template" field.
func DoneCommandTemplateGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldDoneCommandTemplate, v))
}

// DoneCommandTemplateGTE applies the GTE predicate on the "done_command_template" field.
func DoneCommandTemplateGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldDoneCommandTemplate, v))
}

// DoneCommandTemplateLT applies the LT predicate on the "done_command_template" field.
func DoneCommandTemplateLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldDoneCommandTemplate, v))
}

// DoneCommandTemplateLTE applies the LTE predicate on the "done_command_template" field.
func DoneCommandTemplateLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldDoneCommandTemplate, v))
}

// DoneCommandTemplateContains applies the Contains predicate on the "done_command_template" field.
func DoneCommandTemplateContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldDoneCommandTemplate, v))
}

// DoneCommandTemplateHasPrefix applies the HasPrefix predicate on the "done_command_template" field.
func DoneCommandTemplateHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldDoneCommandTemplate, v))
}

// DoneCommandTemplateHasSuffix applies the HasSuffix predicate on the "done_command_template" field.
func DoneCommandTemplateHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldDoneCommandTemplate, v))
}

// DoneCommandTemplateEqualFold applies the EqualFold predicate on the "done_command_template" field.
func DoneCommandTemplateEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldDoneCommandTemplate, v))
}

// DoneCommandTemplateContainsFold applies the ContainsFold predicate on the "done_command_template" field.
func DoneCommandTemplateContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldDoneCommandTemplate, v))
}

// FailCommandTemplateEQ applies the EQ predicate on the "fail_command_template" field.
func FailCommandTemplateEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldFailCommandTemplate, v))
}

// FailCommandTemplateNEQ applies the NEQ predicate on the "fail_command_template" field.
func FailCommandTemplateNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldFailCommandTemplate, v))
}

// FailCommandTemplateIn applies the In predicate on the "fail_command_template" field.
func FailCommandTemplateIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldFailCommandTemplate, vs...))
}

// FailCommandTemplateNotIn applies the NotIn predicate on the "fail_command_template" field.
func FailCommandTemplateNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldFailCommandTemplate, vs...))
}

// FailCommandTemplateGT applies the GT predicate on the "fail_command_template" field.
func FailCommandTemplateGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldFailCommandTemplate, v))
}

// FailCommandTemplateGTE applies the GTE predicate on the "fail_command_template" field.
func FailCommandTemplateGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldFailCommandTemplate, v))
}

// FailCommandTemplateLT applies the LT predicate on the "fail_command_template" field.
func FailCommandTemplateLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldFailCommandTemplate, v))
}

// FailCommandTemplateLTE applies the LTE predicate on the "fail_command_template" field.
func FailCommandTemplateLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldFailCommandTemplate, v))
}

// FailCommandTemplateContains applies the Contains predicate on the "fail_command_template" field.
func FailCommandTemplateContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldFailCommandTemplate, v))
}

// FailCommandTemplateHasPrefix applies the HasPrefix predicate on the "fail_command_template" field.
func FailCommandTemplateHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldFailCommandTemplate, v))
}

// FailCommandTemplateHasSuffix applies the HasSuffix predicate on the "fail_command_template" field.
func FailCommandTemplateHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldFailCommandTemplate, v))
}

// FailCommandTemplateEqualFold applies the EqualFold predicate on the "fail_command_template" field.
func FailCommandTemplateEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldFailCommandTemplate, v))
}

// FailCommandTemplateContainsFold applies the ContainsFold predicate on the "fail_command_template" field.
func FailCommandTemplateContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldFailCommandTemplate, v))
}

// ReviewCommandTemplateEQ applies the EQ predicate on the "review_command_template" field.
func ReviewCommandTemplateEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldReviewCommandTemplate, v))
}

// ReviewCommandTemplateNEQ applies the NEQ predicate on the "review_command_template" field.
func ReviewCommandTemplateNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldReviewCommandTemplate, v))
}

// ReviewCommandTemplateIn applies the In predicate on the "review_command_template" field.
func ReviewCommandTemplateIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldReviewCommandTemplate, vs...))
}

// ReviewCommandTemplateNotIn applies the NotIn predicate on the "review_command_template" field.
func ReviewCommandTemplateNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldReviewCommandTemplate, vs...))
}

// ReviewCommandTemplateGT applies the GT predicate on the "review_command_template" field.
func ReviewCommandTemplateGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldReviewCommandTemplate, v))
}

// ReviewCommandTemplateGTE applies the GTE predicate on the "review_command_template" field.
func ReviewCommandTemplateGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldReviewCommandTemplate, v))
}

// ReviewCommandTemplateLT applies the LT predicate on the "review_command_template" field.
func ReviewCommandTemplateLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldReviewCommandTemplate, v))
}

// ReviewCommandTemplateLTE applies the LTE predicate on the "review_command_template" field.
func ReviewCommandTemplateLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldReviewCommandTemplate, v))
}

// ReviewCommandTemplateContains applies the Contains predicate on the "review_command_template" field.
func ReviewCommandTemplateContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldReviewCommandTemplate, v))
}

// ReviewCommandTemplateHasPrefix applies the HasPrefix predicate on the "review_command_template" field.
func ReviewCommandTemplateHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldReviewCommandTemplate, v))
}

// ReviewCommandTemplateHasSuffix applies the HasSuffix predicate on the "review_command_template" field.
func ReviewCommandTemplateHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldReviewCommandTemplate, v))
}

// ReviewCommandTemplateEqualFold applies the EqualFold predicate on the "review_command_template" field.
func ReviewCommandTemplateEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldReviewCommandTemplate, v))
}

// ReviewCommandTemplateContainsFold applies the ContainsFold predicate on the "review_command_template" field.
func ReviewCommandTemplateContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldReviewCommandTemplate, v))
}

// ShipCommandTemplateEQ applies the EQ predicate on the "ship_command_template" field.
func ShipCommandTemplateEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldShipCommandTemplate, v))
}

// ShipCommandTemplateNEQ applies the NEQ predicate on the "ship_command_template" field.
func ShipCommandTemplateNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldShipCommandTemplate, v))
}

// ShipCommandTemplateIn applies the In predicate on the "ship_command_template" field.
func ShipCommandTemplateIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldShipCommandTemplate, vs...))
}

// ShipCommandTemplateNotIn applies the NotIn predicate on the "ship_command_template" field.
func ShipCommandTemplateNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldShipCommandTemplate, vs...))
}

// ShipCommandTemplateGT applies the GT predicate on the "ship_command_template" field.
func ShipCommandTemplateGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldShipCommandTemplate, v))
}

// ShipCommandTemplateGTE applies the GTE predicate on the "ship_command_template" field.
func ShipCommandTemplateGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldShipCommandTemplate, v))
}

// ShipCommandTemplateLT applies the LT predicate on the "ship_command_template" field.
func ShipCommandTemplateLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldShipCommandTemplate, v))
}

// ShipCommandTemplateLTE applies the LTE predicate on the "ship_command_template" field.
func ShipCommandTemplateLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldShipCommandTemplate, v))
}

// ShipCommandTemplateContains applies the Contains predicate on the "ship_command_template" field.
func ShipCommandTemplateContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldShipCommandTemplate, v))
}

// ShipCommandTemplateHasPrefix applies the HasPrefix predicate on the "ship_command_template" field.
func ShipCommandTemplateHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldShipCommandTemplate, v))
}

// ShipCommandTemplateHasSuffix applies the HasSuffix predicate on the "ship_command_template" field.
func ShipCommandTemplateHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldShipCommandTemplate, v))
}

// ShipCommandTemplateEqualFold applies the EqualFold predicate on the "ship_command_template" field.
func ShipCommandTemplateEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldShipCommandTemplate, v))
}

// ShipCommandTemplateContainsFold applies the ContainsFold predicate on the "ship_command_template" field.
func ShipCommandTemplateContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldShipCommandTemplate, v))
}

// HelpCommandTemplateEQ applies the EQ predicate on the "help_command_template" field.
func HelpCommandTemplateEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldHelpCommandTemplate, v))
}

// HelpCommandTemplateNEQ applies the NEQ predicate on the "help_command_template" field.
func HelpCommandTemplateNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldHelpCommandTemplate, v))
}

// HelpCommandTemplateIn applies the In predicate on the "help_command_template" field.
func HelpCommandTemplateIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldHelpCommandTemplate, vs...))
}

// HelpCommandTemplateNotIn applies the NotIn predicate on the "help_command_template" field.
func HelpCommandTemplateNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldHelpCommandTemplate, vs...))
}

// HelpCommandTemplateGT applies the GT predicate on the "help_command_template" field.
func HelpCommandTemplateGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldHelpCommandTemplate, v))
}

// HelpCommandTemplateGTE applies the GTE predicate on the "help_command_template" field.
func HelpCommandTemplateGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldHelpCommandTemplate, v))
}

// HelpCommandTemplateLT applies the LT predicate on the "help_command_template" field.
func HelpCommandTemplateLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldHelpCommandTemplate, v))
}

// HelpCommandTemplateLTE applies the LTE predicate on the "help_command_template" field.
func HelpCommandTemplateLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldHelpCommandTemplate, v))
}

// HelpCommandTemplateContains applies the Contains predicate on the "help_command_template" field.
func HelpCommandTemplateContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldHelpCommandTemplate, v))
}

// HelpCommandTemplateHasPrefix applies the HasPrefix predicate on the "help_command_template" field.
func HelpCommandTemplateHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldHelpCommandTemplate, v))
}

// HelpCommandTemplateHasSuffix applies the HasSuffix predicate on the "help_command_template" field.
func HelpCommandTemplateHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldHelpCommandTemplate, v))
}

// HelpCommandTemplateEqualFold applies the EqualFold predicate on the "help_command_template" field.
func HelpCommandTemplateEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldHelpCommandTemplate, v))
}

// HelpCommandTemplateContainsFold applies the ContainsFold predicate on the "help_command_template" field.
func HelpCommandTemplateContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldHelpCommandTemplate, v))
}

// TriagePromptTemplateEQ applies the EQ predicate on the "triage_prompt_template" field.
func TriagePromptTemplateEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldTriagePromptTemplate, v))
}

// TriagePromptTemplateNEQ applies the NEQ predicate on the "triage_prompt_template" field.
func TriagePromptTemplateNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldTriagePromptTemplate, v))
}

// TriagePromptTemplateIn applies the In predicate on the "triage_prompt_template" field.
func TriagePromptTemplateIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldTriagePromptTemplate, vs...))
}

// TriagePromptTemplateNotIn applies the NotIn predicate on the "triage_prompt_template" field.
func TriagePromptTemplateNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldTriagePromptTemplate, vs...))
}

// TriagePromptTemplateGT applies the GT predicate on the "triage_prompt_template" field.
func TriagePromptTemplateGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldTriagePromptTemplate, v))
}

// TriagePromptTemplateGTE applies the GTE predicate on the "triage_prompt_template" field.
func TriagePromptTemplateGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldTriagePromptTemplate, v))
}

// TriagePromptTemplateLT applies the LT predicate on the "triage_prompt_template" field.
func TriagePromptTemplateLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldTriagePromptTemplate, v))
}

// TriagePromptTemplateLTE applies the LTE predicate on the "triage_prompt_template" field.
func TriagePromptTemplateLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldTriagePromptTemplate, v))
}

// TriagePromptTemplateContains applies the Contains predicate on the "triage_prompt_template" field.
func TriagePromptTemplateContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldTriagePromptTemplate, v))
}

// TriagePromptTemplateHasPrefix applies the HasPrefix predicate on the "triage_prompt_template" field.
func TriagePromptTemplateHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldTriagePromptTemplate, v))
}

// TriagePromptTemplateHasSuffix applies the HasSuffix predicate on the "triage_prompt_template" field.
func TriagePromptTemplateHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldTriagePromptTemplate, v))
}

// TriagePromptTemplateEqualFold applies the EqualFold predicate on the "triage_prompt_template" field.
func TriagePromptTemplateEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldTriagePromptTemplate, v))
}

// TriagePromptTemplateContainsFold applies the ContainsFold predicate on the "triage_prompt_template" field.
func TriagePromptTemplateContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldTriagePromptTemplate, v))
}

// ReviewPromptTemplateEQ applies the EQ predicate on the "review_prompt_template" field.
func ReviewPromptTemplateEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldReviewPromptTemplate, v))
}

// ReviewPromptTemplateNEQ applies the NEQ predicate on the "review_prompt_template" field.
func ReviewPromptTemplateNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldReviewPromptTemplate, v))
}

// ReviewPromptTemplateIn applies the In predicate on the "review_prompt_template" field.
func ReviewPromptTemplateIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldReviewPromptTemplate, vs...))
}

// ReviewPromptTemplateNotIn applies the NotIn predicate on the "review_prompt_template" field.
func ReviewPromptTemplateNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldReviewPromptTemplate, vs...))
}

// ReviewPromptTemplateGT applies the GT predicate on the "review_prompt_template" field.
func ReviewPromptTemplateGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldReviewPromptTemplate, v))
}

// ReviewPromptTemplateGTE applies the GTE predicate on the "review_prompt_template" field.
func ReviewPromptTemplateGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldReviewPromptTemplate, v))
}

// ReviewPromptTemplateLT applies the LT predicate on the "review_prompt_template" field.
func ReviewPromptTemplateLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldReviewPromptTemplate, v))
}

// ReviewPromptTemplateLTE applies the LTE predicate on the "review_prompt_template" field.
func ReviewPromptTemplateLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldReviewPromptTemplate, v))
}

// ReviewPromptTemplateContains applies the Contains predicate on the "review_prompt_template" field.
func ReviewPromptTemplateContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldReviewPromptTemplate, v))
}

// ReviewPromptTemplateHasPrefix applies the HasPrefix predicate on the "review_prompt_template" field.
func ReviewPromptTemplateHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldReviewPromptTemplate, v))
}

// ReviewPromptTemplateHasSuffix applies the HasSuffix predicate on the "review_prompt_template" field.
func ReviewPromptTemplateHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldReviewPromptTemplate, v))
}

// ReviewPromptTemplateEqualFold applies the EqualFold predicate on the "review_prompt_template" field.
func ReviewPromptTemplateEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldReviewPromptTemplate, v))
}

// ReviewPromptTemplateContainsFold applies the ContainsFold predicate on the "review_prompt_template" field.
func ReviewPromptTemplateContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldReviewPromptTemplate, v))
}

// InitialPromptTemplateEQ applies the EQ predicate on the "initial_prompt_template" field.
func InitialPromptTemplateEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldInitialPromptTemplate, v))
}

// InitialPromptTemplateNEQ applies the NEQ predicate on the "initial_prompt_template" field.
func InitialPromptTemplateNEQ(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldInitialPromptTemplate, v))
}

// InitialPromptTemplateIn applies the In predicate on the "initial_prompt_template" field.
func InitialPromptTemplateIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldInitialPromptTemplate, vs...))
}

// InitialPromptTemplateNotIn applies the NotIn predicate on the "initial_prompt_template" field.
func InitialPromptTemplateNotIn(vs ...string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldInitialPromptTemplate, vs...))
}

// InitialPromptTemplateGT applies the GT predicate on the "initial_prompt_template" field.
func InitialPromptTemplateGT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldInitialPromptTemplate, v))
}

// InitialPromptTemplateGTE applies the GTE predicate on the "initial_prompt_template" field.
func InitialPromptTemplateGTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldInitialPromptTemplate, v))
}

// InitialPromptTemplateLT applies the LT predicate on the "initial_prompt_template" field.
func InitialPromptTemplateLT(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldInitialPromptTemplate, v))
}

// InitialPromptTemplateLTE applies the LTE predicate on the "initial_prompt_template" field.
func InitialPromptTemplateLTE(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldInitialPromptTemplate, v))
}

// InitialPromptTemplateContains applies the Contains predicate on the "initial_prompt_template" field.
func InitialPromptTemplateContains(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContains(FieldInitialPromptTemplate, v))
}

// InitialPromptTemplateHasPrefix applies the HasPrefix predicate on the "initial_prompt_template" field.
func InitialPromptTemplateHasPrefix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasPrefix(FieldInitialPromptTemplate, v))
}

// InitialPromptTemplateHasSuffix applies the HasSuffix predicate on the "initial_prompt_template" field.
func InitialPromptTemplateHasSuffix(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldHasSuffix(FieldInitialPromptTemplate, v))
}

// InitialPromptTemplateEqualFold applies the EqualFold predicate on the "initial_prompt_template" field.
func InitialPromptTemplateEqualFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEqualFold(FieldInitialPromptTemplate, v))
}

// InitialPromptTemplateContainsFold applies the ContainsFold predicate on the "initial_prompt_template" field.
func InitialPromptTemplateContainsFold(v string) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldContainsFold(FieldInitialPromptTemplate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PipelineMode {
	return predicate.PipelineMode(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PipelineMode) predicate.PipelineMode {
	return predicate.PipelineMode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PipelineMode) predicate.PipelineMode {
	return predicate.PipelineMode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PipelineMode) predicate.PipelineMode {
	return predicate.PipelineMode(sql.NotPredicates(p))
}
