package session

// pipeline_engine_characterization_test.go — Epic 1.7, Story 1.7.1: golden-file
// characterization tests proving the default (PipelineModeDefault) path is
// byte-identical before and after the PipelineEngine refactor.
//
// Two tests share the same golden fixtures under session/testdata/pipeline_engine/:
//   - TestBuildDefaultSlashCommandSet_should_MatchPreRefactorGoldenOutput_When_GivenRepresentativeFixtures
//     pins buildDefaultSlashCommandSet/BuildHeadlessTriagePrompt/BuildHeadlessReviewPrompt/
//     BuildTokenBudgetedPrompt's own output against the golden files (Story 1.3.4's
//     zero-regression guard on the pre-existing hardcoded functions themselves).
//   - TestCachingPipelineEngine_should_ProduceByteIdenticalOutputToGoldenFixtures_When_ModeIsDefault
//     proves CachingPipelineEngine's SlashCommandSet/TriagePromptFor/ReviewPromptFor/
//     InitialPromptFor produce the SAME output for a default-mode item — i.e. the
//     refactor introduced zero drift on the path every existing item takes today.
//
// Golden files are regenerated by running the test suite with
// UPDATE_PIPELINE_GOLDEN=1, e.g.:
//
//	UPDATE_PIPELINE_GOLDEN=1 go test ./session/ -run TestBuildDefaultSlashCommandSet_should_MatchPreRefactorGoldenOutput -v
//
// Regenerating is only ever appropriate for a deliberate, reviewed behavior
// change to the default pipeline — a golden-file diff in review is exactly the
// signal this story exists to produce.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// characterizationFixture bundles one representative BacklogItemData plus the
// fixed input params BuildHeadlessReviewPrompt/BuildTokenBudgetedPrompt need,
// so both characterization tests exercise identical inputs.
type characterizationFixture struct {
	name string
	item *BacklogItemData
}

// characterizationFixtures returns the 3 representative fixtures Story 1.7.1
// requires: 0 AC criteria, 1 criterion, 2+ criteria. All fields that would
// otherwise touch the filesystem (PlanArtifactsPath) are deliberately left
// empty so golden output has no environment dependency.
func characterizationFixtures() []characterizationFixture {
	return []characterizationFixture{
		{
			name: "zero_criteria",
			item: &BacklogItemData{
				ID:                 "char-fixture-0",
				Title:              "Zero Criteria Item",
				Description:        "An item with no acceptance criteria yet.",
				AcceptanceCriteria: "",
				RepoPath:           "/repo/zero",
			},
		},
		{
			name: "one_criterion",
			item: &BacklogItemData{
				ID:                 "char-fixture-1",
				Title:              "One Criterion Item",
				Description:        "An item with exactly one acceptance criterion.",
				AcceptanceCriteria: `[{"index":0,"text":"Do the one thing","status":"pending"}]`,
				RepoPath:           "/repo/one",
			},
		},
		{
			name: "two_plus_criteria",
			item: &BacklogItemData{
				ID:          "char-fixture-2",
				Title:       "Two Plus Criteria Item",
				Description: "An item with multiple acceptance criteria.",
				AcceptanceCriteria: `[{"index":0,"text":"First criterion","status":"pending"},` +
					`{"index":1,"text":"Second criterion","status":"done"},` +
					`{"index":2,"text":"Third criterion","status":"pending"}]`,
				RepoPath: "/repo/two-plus",
			},
		},
	}
}

// characterizationArtifactAbsPath is the fixed (non-filesystem-touching)
// artifact path passed to BuildHeadlessTriagePrompt/TriagePromptFor — it only
// appears as literal text inside the rendered prompt.
const characterizationArtifactAbsPath = "/artifacts/char-fixture"

// characterizationReviewParams returns the fixed diff/verificationNotes/extras
// inputs BuildHeadlessReviewPrompt/ReviewPromptFor need. acSnapshot is derived
// from the fixture item's own AcceptanceCriteria so the review prompt's
// "## Acceptance Criteria" section matches the fixture's shape (0/1/2+).
func characterizationReviewParams(t *testing.T, item *BacklogItemData) (acSnapshot []AcCriterion, diff string, diffTruncated bool, verificationNotes string, extras ReviewContextExtras) {
	t.Helper()
	criteria, err := ParseAcCriteria(item.AcceptanceCriteria)
	if err != nil {
		t.Fatalf("ParseAcCriteria(%s): %v", item.ID, err)
	}
	diff = "diff --git a/main.go b/main.go\n" +
		"index 1111111..2222222 100644\n" +
		"--- a/main.go\n" +
		"+++ b/main.go\n" +
		"@@ -1,3 +1,4 @@\n" +
		" package main\n" +
		"+// added a comment\n"
	verificationNotes = "Verified locally via go test ./... — all tests pass."
	return criteria, diff, false, verificationNotes, ReviewContextExtras{}
}

// serializeSlashCommandSet renders a filename->content map deterministically
// (sorted by filename) so it can be stored as a single golden file per
// fixture.
func serializeSlashCommandSet(files map[string]string) string {
	keys := make([]string, 0, len(files))
	for k := range files {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	for _, k := range keys {
		fmt.Fprintf(&sb, "=== %s ===\n%s\n", k, files[k])
	}
	return sb.String()
}

// goldenPath returns the path to the golden fixture file named name under
// session/testdata/pipeline_engine/.
func goldenPath(name string) string {
	return filepath.Join("testdata", "pipeline_engine", name+".golden")
}

// assertMatchesGolden compares got against the golden file named name. When
// the UPDATE_PIPELINE_GOLDEN=1 environment variable is set, it writes got as
// the new golden content instead of comparing (regeneration mode) — see the
// package doc comment above for the regeneration command.
func assertMatchesGolden(t *testing.T, name, got string) {
	t.Helper()
	path := goldenPath(name)

	if os.Getenv("UPDATE_PIPELINE_GOLDEN") == "1" {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("assertMatchesGolden: MkdirAll(%s): %v", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatalf("assertMatchesGolden: WriteFile(%s): %v", path, err)
		}
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("assertMatchesGolden: ReadFile(%s): %v (run with UPDATE_PIPELINE_GOLDEN=1 to generate golden fixtures)", path, err)
	}
	if got != string(want) {
		t.Errorf("golden mismatch for %s:\n--- got ---\n%s\n--- want (golden) ---\n%s", name, got, string(want))
	}
}

// ─── Story 1.7.1: golden-file characterization tests ───────────────────────

// TestBuildDefaultSlashCommandSet_should_MatchPreRefactorGoldenOutput_When_GivenRepresentativeFixtures
// pins the pre-existing hardcoded functions' own output against the golden
// fixtures — the zero-regression guard on Story 1.3.4's extraction of
// buildDefaultSlashCommandSet itself, independent of PipelineEngine.
func TestBuildDefaultSlashCommandSet_should_MatchPreRefactorGoldenOutput_When_GivenRepresentativeFixtures(t *testing.T) {
	t.Parallel()
	for _, fx := range characterizationFixtures() {
		t.Run(fx.name, func(t *testing.T) {
			t.Parallel()
			files, err := buildDefaultSlashCommandSet(fx.item)
			if err != nil {
				t.Fatalf("buildDefaultSlashCommandSet: %v", err)
			}
			assertMatchesGolden(t, fx.name+"_slash_commands", serializeSlashCommandSet(files))

			triagePrompt := BuildHeadlessTriagePrompt(fx.item, characterizationArtifactAbsPath)
			assertMatchesGolden(t, fx.name+"_triage_prompt", triagePrompt)

			acSnapshot, diff, diffTruncated, verificationNotes, extras := characterizationReviewParams(t, fx.item)
			reviewPrompt := BuildHeadlessReviewPrompt(fx.item, acSnapshot, diff, diffTruncated, verificationNotes, extras)
			assertMatchesGolden(t, fx.name+"_review_prompt", reviewPrompt)

			initialPrompt := BuildTokenBudgetedPrompt(fx.item, nil)
			assertMatchesGolden(t, fx.name+"_initial_prompt", initialPrompt)
		})
	}
}

// TestCachingPipelineEngine_should_ProduceByteIdenticalOutputToGoldenFixtures_When_ModeIsDefault
// proves CachingPipelineEngine's 4 content-generating methods produce
// byte-identical output to the same golden fixtures for a default-mode
// (PipelineMode == "") item — the direct regression test for "the refactor
// didn't change default-path behavior." Uses a zero-value engine (nil
// cache/repo) so any accidental cache/DB touch on the default-mode
// short-circuit would panic and fail the test, exactly like
// TestCachingPipelineEngine_SlashCommandSet_should_ShortCircuitCacheAndDB_When_ModeIsDefault
// already does for SlashCommandSet alone.
func TestCachingPipelineEngine_should_ProduceByteIdenticalOutputToGoldenFixtures_When_ModeIsDefault(t *testing.T) {
	t.Parallel()
	engine := &CachingPipelineEngine{}

	for _, fx := range characterizationFixtures() {
		t.Run(fx.name, func(t *testing.T) {
			t.Parallel()
			files, err := engine.SlashCommandSet(fx.item)
			if err != nil {
				t.Fatalf("SlashCommandSet: %v", err)
			}
			assertMatchesGolden(t, fx.name+"_slash_commands", serializeSlashCommandSet(files))

			triagePrompt := engine.TriagePromptFor(fx.item, characterizationArtifactAbsPath)
			assertMatchesGolden(t, fx.name+"_triage_prompt", triagePrompt)

			acSnapshot, diff, diffTruncated, verificationNotes, extras := characterizationReviewParams(t, fx.item)
			reviewPrompt := engine.ReviewPromptFor(fx.item, acSnapshot, diff, diffTruncated, verificationNotes, extras)
			assertMatchesGolden(t, fx.name+"_review_prompt", reviewPrompt)

			initialPrompt := engine.InitialPromptFor(fx.item, nil)
			assertMatchesGolden(t, fx.name+"_initial_prompt", initialPrompt)
		})
	}
}
