// Code generated by ent, DO NOT EDIT.

package shell

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the shell type in the database.
	Label = "shell"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCommand holds the string denoting the command field in the database.
	FieldCommand = "command"
	// FieldWorkingDir holds the string denoting the working_dir field in the database.
	FieldWorkingDir = "working_dir"
	// FieldTmuxSessionName holds the string denoting the tmux_session_name field in the database.
	FieldTmuxSessionName = "tmux_session_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExitCode holds the string denoting the exit_code field in the database.
	FieldExitCode = "exit_code"
	// FieldOrderIndex holds the string denoting the order_index field in the database.
	FieldOrderIndex = "order_index"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldStoppedAt holds the string denoting the stopped_at field in the database.
	FieldStoppedAt = "stopped_at"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// Table holds the table name of the shell in the database.
	Table = "shells"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "shells"
	// SessionInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionInverseTable = "sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_shells"
)

// Columns holds all SQL columns for shell fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCommand,
	FieldWorkingDir,
	FieldTmuxSessionName,
	FieldStatus,
	FieldExitCode,
	FieldOrderIndex,
	FieldStartedAt,
	FieldStoppedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "shells"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"session_shells",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCommand holds the default value on creation for the "command" field.
	DefaultCommand string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultOrderIndex holds the default value on creation for the "order_index" field.
	DefaultOrderIndex int
	// DefaultStartedAt holds the default value on creation for the "started_at" field.
	DefaultStartedAt func() time.Time
)

// OrderOption defines the ordering options for the Shell queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCommand orders the results by the command field.
func ByCommand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommand, opts...).ToFunc()
}

// ByWorkingDir orders the results by the working_dir field.
func ByWorkingDir(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkingDir, opts...).ToFunc()
}

// ByTmuxSessionName orders the results by the tmux_session_name field.
func ByTmuxSessionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTmuxSessionName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByExitCode orders the results by the exit_code field.
func ByExitCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExitCode, opts...).ToFunc()
}

// ByOrderIndex orders the results by the order_index field.
func ByOrderIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderIndex, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByStoppedAt orders the results by the stopped_at field.
func ByStoppedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoppedAt, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
